### ISSUE TITLE
[TI-99] on-modify.timewarrior raises a TypeError on fresh install

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#103]
_Jonathan Wheeler on 2018-01-08T16:36:58Z says:_ 

 Changing lines 57 and 61 from

`  os.system('timew start ' + combined + ' :yes')`

to

`  os.system('timew start ' + combined + ' :yes')`

 

resolves this issue.

**Comment by ecocode** [comment]
there still is an encoding problem. This can be solved:
first replace lines 
  os.system('timew start ' + combined.decode('utf-8') + ' :yes')
back to
  os.system('timew start ' + combined + ' :yes')

then add 
  combined = unicode(combined,'utf-8').encode("utf-8")
after
  combined = ' '.join(['"%s"' % tag for tag in tags]).encode('utf-8').strip()

This should solve the issues
