### ISSUE TITLE
[TI-102] Exclusions stopped working

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#106]
_Christian Decker on 2018-01-16T05:45:01Z says:_ 

 I just installed timew 1.1.0 on cygwin and now my extenstions doesn't work anymore.

My timewarrior.cfg looks like the following.
{code}
import /usr/local/share/doc/timew/doc/holidays/holidays.de-DE
exclusions.monday = <7:00 9:00-9:20 12:00-12:40 >15:40
exclusions.tuesday = <7:00 9:00-9:20 12:00-12:40 >15:40
exclusions.wednesday = <7:00 9:00-9:20 12:00-12:40 >15:40
exclusions.thursday = <7:00 9:00-9:20 12:00-12:40 >15:40
exclusions.friday = <7:00 9:00-9:20 12:00-12:40 >15:40
exclusions.saturday = >0:00
exclusions.sunday = >0:00
{code}

When I exectue (for example) timew month I get different outputs (see attachment).

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2018-01-16T05:45:01Z
Modified: 2018-02-06T05:57:41Z
```

**Comment by taskwarrior** [comment]
_Christian Decker on 2018-01-16T05:54:54Z says:_ 

 I'm sorry I mean exclusions

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2018-01-16T08:07:53Z says:_ 

 With 1.1.0 exclusions are only applied to open intervals only. When the interval is closed, the interval is flattened (i.e. exclusions are applied) and the resulting interval set is stored.

When you see different results, it means your data has not been stored correctly with TimeWarrior 1.0.0.

The limitation to open intervals makes sense when you consider the case that you change your exclusions later, it would modify your stored data otherwise. This is bad, especially if it is work data.

Concerning your problem, we could migrate your data with a script that applies your exclusions to the stored data.

I will investigate that.

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2018-01-18T06:34:50Z says:_ 

 I have attached a test script (TI-102.sh) and two outputs for 1.0.0 (test-1.0.0.log) and 1.1.0 (test-1.1.0.log) which reveal, that the data is written to the database without being flattened (i,e. exclusions applied). I will investigate this issue further

**Comment by taskwarrior** [comment]
_Christian Decker on 2018-01-18T08:12:09Z says:_ 

 Can I help you investigating this issue?

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2018-01-18T09:21:17Z says:_ 

 If you do not mind, you could attach a data file (e.g. 2017-12.data) and the output of `timew export 2017-12-01 - 2018-01-01` and `timew summary 2017-12-01 - 2018-01-01` for this data, both for 1.0.0 and 1.1.0.

**Comment by taskwarrior** [comment]
_Christian Decker on 2018-01-18T11:49:36Z says:_ 

 I uploaded 5 files. The data (2017-12.data). The timew summary output (timewsummary110 and ... 100.txt) and the timew export output (timewexport110 and ...100.txt)

I just changed the tags to empty. I hope that isn't a problem.

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2018-01-19T15:44:44Z says:_ 

 Thanks for the file upload!  Anonymization is perfectly ok.

A first fix is currently pushed to 1.2.0 and reviewed.

I have attached TI-102-test.sh which can be called by source TI-102-test.sh to check for the fix.

**Comment by taskwarrior** [comment]
_Christian Decker on 2018-01-26T05:46:20Z says:_ 

 I pulled the code. Tested 1.2.0 and 1.1.1 but there is still the problem. Maybe I just have to wait until it is reviewed.

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2018-01-26T08:15:23Z says:_ 

 Have you added new intervals which span over exclusions of just called summary on your previous data?

Summary should display the data without the exclusions, because they are not written into the database. This will be fixed by a database correction script I am currently working on...

If you add a new interval (open) then you should see exclusions getting applied in the summary. If you close this interval, the interval should be flattened and the resulting intervals written to the database. Then summary should display the correct intervals.

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2018-02-02T22:14:40Z says:_ 

 Database-correction script is released on the taskwarrior website (https://taskwarrior.org/docs/timewarrior/dbcorrection.html)

**Comment by taskwarrior** [comment]
_Christian Decker on 2018-02-06T05:43:00Z says:_ 

 Thank you very much. I just love timewarrior and taskwarrior :)

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2018-02-06T05:57:41Z says:_ 

 Thank *you* for reporting this issue. :)

**Comment by pbeckingham** [comment]
[TI-102_2017-12.data.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755236/TI-102_2017-12.data.txt)
[TI-102_test-1.0.0.log](https://github.com/GothenburgBitFactory/timewarrior/files/1755237/TI-102_test-1.0.0.log)
[TI-102_test-1.1.0.log](https://github.com/GothenburgBitFactory/timewarrior/files/1755238/TI-102_test-1.1.0.log)
[TI-102_TI-102-test.sh.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755239/TI-102_TI-102-test.sh.txt)
[TI-102_TI-102.sh.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755240/TI-102_TI-102.sh.txt)
[TI-102_timew100export.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755241/TI-102_timew100export.txt)
[TI-102_timew100summary.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755242/TI-102_timew100summary.txt)
[TI-102_timew110export.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755243/TI-102_timew110export.txt)
[TI-102_timew110summary.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755244/TI-102_timew110summary.txt)
![ti-102_version100](https://user-images.githubusercontent.com/7963/36635062-ad994b98-197c-11e8-8ee4-1a761b19a07e.png)
![ti-102_version110](https://user-images.githubusercontent.com/7963/36635063-ada6654e-197c-11e8-8da0-5e04a20baf51.png)
