### ISSUE TITLE
[TI-103] Fix autorange in chart

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#107]
_Thomas Lauf on 2018-01-31T22:54:18Z says:_ 

 Email by Fabian Pflug:

> I had a little bug in Timewarrior, when I wanted to show the week or month with autorange enabled. It would always start at hour 0 even though my tracking starts at 9 o'clock. This only happens during an open time interval.

TODO:
 * Analyse bug and add test
 * apply and review fix

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2018-01-31T22:54:18Z
Modified: 2018-02-05T22:15:15Z
```

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2018-02-05T14:01:57Z says:_ 

 Given the exclusions
{code:java}
exclusions.monday    = <9:00 >20:00
exclusions.tuesday   = <9:00 >20:00
exclusions.wednesday = <9:00 >20:00
exclusions.thursday  = <9:00 >20:00
exclusions.friday    = <9:00 >20:00
exclusions.saturday  = <9:00 >20:00
exclusions.sunday    = <9:00 >20:00
{code}
and the settings
{code:java}
reports.day.hours = auto
reports.week.hours = auto
reports.month.hours = auto
{code}
I can produce a segfault with the current development branch of timew:
{code:java}
timew track "${YESTERDAY}T1200" - "${YESTERDAY}T1400" FOO
timew start "${YESTERDAY}T1900" BAR
timew week :month
{code}
or by
{code:java}
timew track "${YESTERDAY}T1200" - "${YESTERDAY}T1400" FOO
timew track "${YESTERDAY}T1900" - "${YESTERDAY}T2000" BAR1
timew start "${TODAY}T0900" BAR2
timew week :month
{code}
I am therefore rejecting the patch.

Nevertheless, there is an inconsistency in the chart display when an open interval is present. I will investigate that further.

Could you maybe provide your usecase and your configuration? Thanks.

**Comment by pbeckingham** [comment]
[TI-103_rangefix.diff.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755213/TI-103_rangefix.diff.txt)
[TI-103_TI-103-1.sh.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755214/TI-103_TI-103-1.sh.txt)
[TI-103_TI-103-2.sh.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755215/TI-103_TI-103-2.sh.txt)
[TI-103_TI-103-3.sh.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755216/TI-103_TI-103-3.sh.txt)
[TI-103_TI-103-4.sh.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755217/TI-103_TI-103-4.sh.txt)
