### ISSUE TITLE
No rule to make target: test

### ISSUE THREAD

**Issue by tecfu** [GothenburgBitFactory/timewarrior#109]
Replay:
---

Following the installation instructions from tarball:

```sh
...
$ make test
make: *** No rule to make target `test'.  Stop.
```

Expected Result:
---
Tests pass. 

Environment: 
---
Ubuntu 14.04.3
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
cmake version 2.8.12.2
GNU Make 3.81

**Comment by pbeckingham** [comment]
True: the tarball does not contain tests.

**Comment by lauft** [comment]
This should be clarified in the README.

**Comment by lauft** [comment]
README has been updated.
