### ISSUE TITLE
Some tests fail depending on the time of day

### ISSUE THREAD

**Issue by chronitis** [GothenburgBitFactory/timewarrior#111]
Several tests using relative time intervals fail if the test suite is run (eg, by a CI system) in the early morning.

Example: `continue.t:137`. Running this test at 04:00 will result in the `five_hours_before` var wrapping to the previous day, but because the test uses the hours part only, it generates either an invalid interval, or a start time in the future. The generated times probably need to be clamped to the start of the day.

```
not ok 4 - continue.t: Verify that continuing a specified interval with date continues at given date
# ERROR: CommandError on file /tmp/autopkgtest-lxc.aizhw87q/downtmp/autopkgtest_tmp/test/continue.t line 137 in test_continue_with_id_and_date: 'code, out, err = self.t("start FOO {}T{:%H}:00:00".format(now.date(), five_hours_before))':
#        Command '['/tmp/autopkgtest-lxc.aizhw87q/downtmp/autopkgtest_tmp/src/timew', 'start', 'FOO', '2018-02-06T21:00:00']' finished with unexpected exit code '255'.
#        
#        *** Start STDOUT ***
#        
#        *** End STDOUT ***
#        
#        *** Start STDERR ***
#        Time tracking cannot be set in the future.
#        
#        *** End STDERR ***
```

This error appears to affect at least:

```
test_continue_with_id_and_date
test_continue_with_id_and_range
test_lengthen_synthetic_interval
test_move_synthetic_interval_into_exclusion
test_move_synthetic_interval_away_from_exclusion
test_shorten_synthetic_interval
test_tag_synthetic_interval
test_untag_synthetic_interval
test_tags_filtered
```

Sample test log: https://ci.debian.net/data/autopkgtest/unstable/amd64/t/timew/20180206_025754/log.gz

**Comment by lauft** [comment]
With 9a2fe83367fd43417fdb5d6dd065ada04f45b1ee, this should have stabilized. Thanks for the bug report.
