### ISSUE TITLE
Monday, 1st and others does not work in recent versions

### ISSUE THREAD

**Issue by sgf-dma** [GothenburgBitFactory/timewarrior#112]
Hi.

Dates like `monday`, `1st` and probably other does not work in recent versions.
It says `Time tracking cannot be set in the future.` . Or may be i didn't understand how to use?

    $ git checkout dev
    Switched to branch 'dev'
    Your branch is up-to-date with 'origin/dev'.
    $ git submodule update
    Submodule path 'src/libshared': checked out '1fa5dcbf53a280857e35436aef6beb6a37266e33'
    $ cmake .
    -- Configuring C++11
    -- System: Linux
    -- Looking for SHA1 references
    -- Found SHA1 reference: 706ad0b
    -- Configuring cmake.h
    -- Configuring documentation
    -- Configuring holiday documentation
    -- Configuring theme documentation
    -- Configuring extensions
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/sgf/Documents/3rd/timewarrior
    $ make

    Linking CXX executable timew
    [100%] Built target timew_executable
    $ ./src/timew diag
    ..

    timew 1.2.0
           Platform: Linux

    Compiler:
            Version: 4.9.2
               Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
         Compliance: C++11

    Build Features
              Built: Mar  6 2018 17:09:15
             Commit: 706ad0b
              CMake: 3.0.2
         Build type:

    Configuration
      TIMEWARRIORDB: -
                Cfg: /home/sgf/.timewarrior/timewarrior.cfg (-rw- 421 bytes)
           Database: /home/sgf/.timewarrior (drwx 4096 bytes)
            $EDITOR: vi
        Color theme: Built-in default
                     00 01 02 03 04 05 06 07 08 09 10 11 12

    Extensions
           Location: /home/sgf/.timewarrior/extensions (drwx 4096 bytes)
                   (None)

    $ ./src/timew summary monday
    Time tracking cannot be set in the future.

But it had worked in 1.0.0:

    $ git checkout v1.0.0
    Switched to a new branch 'v1.0.0'
    $ git submodule update
    Submodule path 'src/libshared': checked out '577c22e4c78dbcb9b0bc605d54650e791f3ff4ba'
    $ cmake .
    -- Configuring C++11
    -- System: Linux
    -- Looking for SHA1 references
    -- Found SHA1 reference: 6428ce8
    -- Configuring cmake.h
    -- Configuring documentation
    -- Configuring holiday documentation
    -- Configuring theme documentation
    -- Configuring extensions
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/sgf/Documents/3rd/timewarrior
    $ make
    ..

    Linking CXX executable timew
    [100%] Built target timew_executable

    $ ./src/timew diag

    timew 1.0.0
           Platform: Linux

    Compiler:
            Version: 4.9.2
               Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
         Compliance: C++11

    Build Features
              Built: Mar  6 2018 17:06:34
             Commit: 6428ce8
              CMake: 3.0.2
         Build type:

    Configuration
      TIMEWARRIORDB: -
                Cfg: /home/sgf/.timewarrior/timewarrior.cfg (-rw- 421 bytes)
           Database: /home/sgf/.timewarrior (drwx 4096 bytes)
            $EDITOR: vi
        Color theme: Built-in default
                     00 01 02 03 04 05 06 07 08 09 10 11 12

    Extensions
           Location: /home/sgf/.timewarrior/extensions (drwx 4096 bytes)
                   (None)

    $ ./src/timew summary monday

    Wk  Date       Day Tags                    Start      End    Time    Total
    W10 2018-03-05 Mon Outline the tutorial  0:00:00  7:15:00 7:15:00
                       Walkt the dog         7:15:00  8:45:00 1:30:00
                       Research2             8:45:00 14:31:19 5:46:19
                                            14:31:19 14:32:23 0:01:04
                                            14:32:50 14:33:50 0:01:00
                       Software, Using Tags 14:34:26 14:35:09 0:00:43 14:34:06
    W10 2018-03-06 Tue Research             11:30:00 15:00:00 3:30:00
                       Research             16:00:00 16:58:56 0:58:56
                       Research             16:58:56        - 0:08:53  4:37:49

                                                                      19:11:55

**Comment by lauft** [comment]
This seems to be introduced with commit b012bf6fec6bb061b35afabfb0a3425128963e24:

> libshared: Updated to cbe3fd84a8950a42ed271a0dd8e7c4e1564b1333

Using the hint-version still works though (at least for day names): `timew summary :monday`

Pull request in libshared: https://github.com/GothenburgBitFactory/libshared/pull/5

**Comment by ddombrowsky** [comment]
I don't think this has made it into a release yet?

I think it is the root cause of most interval issues, such as using a "month" example right out of the help doc:
```
$ timew month 1st - today
Time tracking cannot be set in the future.
```

I'll try building it from source.

**Comment by ddombrowsky** [comment]
issue still open?

```
$ ./src/timew month 1st - today
Time tracking cannot be set in the future.
$ git describe
Post111ToMaster-58-g65f573d
```

**Comment by ddombrowsky** [comment]
I'll open a new issue
