### ISSUE TITLE
Inconsistent IDs

### ISSUE THREAD

**Issue by fcerbell** [GothenburgBitFactory/timewarrior#120]
~ $ timew --version
1.0.0

IDs are generated at display time and change depending on the displayed (filtered) intervals. They are always sequentials and do not depend on an actual ID attached to the interval. 

Example :
When using a filter to get IDs :
timew sum :id MyTag
the IDs are not the same as without filtering
timew sum :id 
Unfortunately, "timew tag" and "timew untag" relies on the not-filtered IDs... 

The only way I found is to "timew sum :month :id | grep MyTag" to get the ID expected by tag/untag

Suggestions :
- One fixed unique ID attached to the interval forever
- One sliding ID : 1 (last interval), 2 (before the last), ... (independent to filters)

**Comment by lauft** [comment]
Version 1.0.0 is outdated. Can you upgrade to version 1.1.1?

**Comment by fcerbell** [comment]
This is the version packaged in Debian Stable. I prefer to stick as 
much as I can with stable packages

If this issue is already fixed in 1.1.1, the bug can be closed, 
otherwise, it is still relevnt.

**Comment by lauft** [comment]
This bug has been fixed with TI-67 (#72) in 182cd5b0b4f81688c99852c721de5645a03207cb.
