### ISSUE TITLE
on-modify.timewarrior - issues with swedish characters

### ISSUE THREAD

**Issue by crulie** [GothenburgBitFactory/timewarrior#123]
Using on-modify.timewarrior hook in taskwarrior together with tasks containing swedish characters gives me this error:

```
[daniel@wintermute ~]$ task start 1
Traceback (most recent call last):
  File "/home/daniel/.task/hooks/on-modify.timewarrior", line 60, in <module>
    os.system('timew start ' + combined.decode() + ' :yes')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
Hook Error: Expected feedback from a failing hook script.
```

**Timewarrior version:**
timew --version
1.1.1

**OS Version:**
Archlinux
Linux 4.15.14-1-ARCH #1 SMP PREEMPT Wed Mar 28 17:34:29 UTC 2018 x86_64 GNU/Linux

**Python:**
Python 3.6.4

**Comment by lauft** [comment]
Confirmed with version 1.1.1, however, this got fixed when refactoring the on-modify script in #98
