### ISSUE TITLE
Delete multiple time intervals

### ISSUE THREAD

**Issue by grovesteyn** [GothenburgBitFactory/timewarrior#124]
It is sometimes necessary to delete multiple intervals. I have not figured out a smart way of doing this (other than manually typing in the IDs).  Is there a way of generating IDs based on a tag filter? If so this could be used along with the delete command. If not this might be a useful feature to add (like the "ids" command in taskwarrior).

**Comment by lauft** [comment]
Currently `delete @1 @2 @3 ...` is the only way to delete multiple intervals. There is no "delete all intervals which contain <TAG>".

When you allow tags to be used with delete, the question arises, what to do with an interval "foo bar" when you issue "delete foo" - or the otherway round: what to to with "foo" when you issue "delete foo bar".

Maybe you can tell us more about why you have to delete multiple intervals. Is there a use case you can describe?

**Comment by grovesteyn** [comment]
One example will be when one forgets to close an interval and then go
traveling. When you are back in the office and simply start logging time on
a new project without realising that the previous one is running this will
generate a list of intervals for the elapsed time.

**Comment by lauft** [comment]
Would it help to support id ranges? E.g.
```
delete @1..5
delete @1 - @6
```

**Comment by grovesteyn** [comment]
Yes. Id ranges would be a great first step.

A further option would be to use a subprocess to generate ID numbers that
could be used in other commands - like the "ids" command for taskwarrior
(task proj:projectname ids).

**Comment by lauft** [comment]
So you imagine something like
```
timew delete $(timew <command that gives me ids from intervals with specified properties>)
```
where the `timew <...>` part would return something like `@1 @4 @6 @...`?

**Comment by grovesteyn** [comment]
Precisely.

**Comment by lauft** [comment]
I have spawned #126, #125 and #127 from this. #126 and #125 concern the solution proposed above, #127 would be an alternative. Further discussion should take place there.
