### ISSUE TITLE
time stop dumps output twice

### ISSUE THREAD

**Issue by dcousens** [GothenburgBitFactory/timewarrior#128]
As shown in this screenshot.
Fresh install from the Arch `community` repo.
![doubleup](https://user-images.githubusercontent.com/413395/38712749-056709b4-3f11-11e8-837e-237dbd485085.png)

``` bash
$ timew --version
1.1.1
$ uname -a
Linux arch 4.15.15-1-ARCH
```

**Comment by lauft** [comment]
This is fixed in milestone 1.2.0. See #116
