### ISSUE TITLE
libshared is not in github release tarballs

### ISSUE THREAD

**Issue by vyskocilm** [GothenburgBitFactory/timewarrior#129]
Hi, I cant build v1.1.1 from github release page

```
CMake Error at src/CMakeLists.txt:46 (add_library):
  Cannot find source file:

    libshared/src/Args.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: Cannot determine link language for target "libshared".
CMake Error: CMake can not determine linker language for target: libshared
-- Generating done
```

It looks like the libshared is a git submodule, which is empty in release tarball.

**Comment by lauft** [comment]
Hi. The github release tarballs are not the officially supported tarballs (yet).
Use the tarballs [provided on taskwarrior.org](https://taskwarrior.org/download/timew-1.1.1.tar.gz).
