### ISSUE TITLE
Task at month end not getting displayed

### ISSUE THREAD

**Issue by towo** [GothenburgBitFactory/timewarrior#135]
Versions: `timew 1.1.1`, `Python 3.6.5`, Arch Linux.

I'm currently seeing a bug that makes task disappear from the day/week/month report if the task ends at the end of a month.

Living in CEST, this means that when I have

```
inc 20180430T200000Z - 20180430T220000Z # "Some Task"
```

it'll not appear in reports; if I change it to end at `215959Z`, it will be displayed. Also doesn't work for `22100Z` or even an interval end at `20180501T0123456Z`.

**Comment by lauft** [comment]
Bug confirmed, cause determined, bug fixed. Thanks for your report!
