### ISSUE TITLE
Can't properly start or stop tracking

### ISSUE THREAD

**Issue by tom-doerr** [GothenburgBitFactory/timewarrior#146]
```
~/Nextcloud/sonstiges/timewarrior/data $ timew
There is no active time tracking.

~/Nextcloud/sonstiges/timewarrior/data $ timew start test
Tracking test
  Started 2018-05-13T16:36:50
  Current                  50
  Total               0:00:00

~/Nextcloud/sonstiges/timewarrior/data $ timew
There is no active time tracking.

~/Nextcloud/sonstiges/timewarrior/data $ timew summary

Wk  Date       Day Tags                                      Start      End    Time   Total
W19 2018-05-13 Sun morgens                                10:06:25 12:06:25 2:00:00
                   webseite auf server zum laufen bringen 12:15:00 13:00:00 0:45:00
                   test                                   16:36:50        - 0:00:23 2:45:23

                                                                                    2:45:23

~/Nextcloud/sonstiges/timewarrior/data $ timew stop
There is no active time tracking.
```

When I start tracking an activity, it confirms that it started tracking that activity. 
When I check what activities are currently running with 'timew' it says that "There is no active time tracking.". 
Running the 'timew summary' command reveals that the activity indeed was started, but I can't stop it with 'timew stop'.

Could it be that some files are corrupted?  
I already deleted the activity from the file 2018-05.data, but once I start tracking an activity I'm in the same situation as before.

**Comment by lauft** [comment]
I cannot confirm this behaviour neither with `dev` nor with `1.1.1`. Which version of Timewarrior are you using? Can you maybe provide the output of your `timew diagnostics` command?

**Comment by tom-doerr** [comment]
```
~/Nextcloud/sonstiges/timewarrior/data $ timew diagnostics

timew 1.1.1
       Platform: Linux

Compiler:
        Version: 5.4.0 20160609
           Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
     Compliance: C++11

Build Features
          Built: Feb 16 2018 20:48:39
          CMake: 3.5.1
     Build type: release

Configuration
  TIMEWARRIORDB: -
            Cfg: /home/tom/.timewarrior/timewarrior.cfg (-rw- 0 bytes)
       Database: /home/tom/.timewarrior (lrwx 4096 bytes)
    Color theme: Built-in default
                 00 01 02 03 04 05 06 07 08 09 10 11 12

Extensions
       Location: /home/tom/.timewarrior/extensions (drwx 4096 bytes)
               (None)

```

Could it be that the file in which the active time tracking information is stored is corrupted? Is there such a file?

**Comment by lauft** [comment]
The time tracking information is stored in `${TIMEWARRIORDB}/data/` in files with the name schema `YYYY-MM.data`. An open interval is simply an interval without end date:
```
inc 20180513T155349Z # foo
```

**Comment by lauft** [comment]
You could setup a temporary test environment and see whether the problem persists:
```
# Setup
mkdir -p /tmp/timewarrior/data
export TIMEWARRIORDB=/tmp/timewarrior
:> ${TIMEWARRIORDB}/timewarrior.cfg
# Test
timew
timew start foo
timew
```

**Comment by tom-doerr** [comment]
Thank you for your help! 

It worked in the test environment, so I copied all of my current files in the test environment and deleted files until it worked again. 

Turns out it was the file '1970-01.data' that cause the issues.  
I thought it was as strange design choice to have a file for every month since 1970, but I probably just entered some invalid timestamp while editing a record.

```
-rw-rw-r-- 1 tom tom      4 May 13 20:42 1970-01.data
-rw-rw-r-- 1 tom tom      0 May 13 20:42 1970-02.data
-rw-rw-r-- 1 tom tom      0 May 13 20:42 1970-03.data
-rw-rw-r-- 1 tom tom      0 May 13 20:42 1970-04.data
-rw-rw-r-- 1 tom tom      0 May 13 20:42 1970-05.data
...
```

**Comment by the-kenny** [comment]
I just ran into this issue today and was pretty confused before resorting to checking Github Issues for this problem.

Is there anything implemented to prevent this from happening again?
