### ISSUE TITLE
Extract human readable active duration

### ISSUE THREAD

**Issue by fdietze** [GothenburgBitFactory/timewarrior#148]
Is it possible to print the active duration in a human readable format?
I'd like to display the duration in my statusbar, but using the DOM prints the duration in ISO 8601 format:

```bash
$ timew get dom.active.duration
PT56M8S
```

**Comment by lauft** [comment]
It is always difficult which formats should be supported. Your "human readable format" may not be the one another user wishes and making it configurable may lead to code bloat...

As a quick workaround you could use the python package `isodate` and this little script:
```
#!/usr/bin/env python

import sys
from isodate import parse_duration

print(parse_duration(sys.stdin.read()))
```
Save it as `how_long.py` and pipe through Timewarrior's output so you get:
```
$ timew get dom.active.duration | ./how_long.py
1:39:13
```

**Comment by fdietze** [comment]
Ok thank you!

**Comment by trev-dev** [comment]
The Python solution is fine, I guess, but since we spoke about bloat here and I can't seem to google my way out of this one, either, how would someone parse an ISO duration with bash?

So far as I can search, it's easier to subtract $then from $now than it is to simply use `dom.active.duration` - which makes me wonder why ISO 8601 is the go-to output for Timewarrior.

**Comment by trev-dev** [comment]
Thanks for taking the time to reply. I get that no output standard is going to make everyone happy :)

After I was done grumping over how manual/fiddly parsing ISO 8601 is, I just used Python to get a live timer/status on my tiling wm bar. I am rarely without Python, and I did install isodate. Hopefully I remember that if I migrate.

I also parsed the output of `timew summary :day` to show the consolidated amount of productive time I had done in a given day in said tiling bar, which involved splitting and looping backwards.

I love, and sometimes snerk, at how simple and free Time/Taskwarrior can be. You can get whatever you want if you just abstract it yourself.
