### ISSUE TITLE
Allow for time overlap (multi-tasking)

### ISSUE THREAD

**Issue by a7hybnj2** [GothenburgBitFactory/timewarrior#151]
I have a situation where I need to track more then one time event at once. My current use case is:  
I am monitoring machines which, means I need to be in proximity to them. While I am in proximity I can complete other tasks but am still technically 'monitoring machines'.

A simpler (fake) use case. If I needed to 'watch the 6 o'clock news and make dinner. Well, as long as I had a t.v. in viewing distance from the stovetop I could be completing both of those tasks at once.

In taskwarrior I will often 'task 6 7 start' which, doesn't play nicely with timew.

**Comment by a7hybnj2** [comment]
Another good use case would be total time vs project time.

For instance: 
If I “clocked in“ at the start of a day and worked on five “projects“ during the day and wanted to specifically track the duration of each project.

**Comment by lauft** [comment]
Human multitasking is an illusion... ;)

In a way Timewarrior allows for multitasking via tags. You can assign multiple tags to a single interval, e.g. in your case
```
timew start MONITORING PROJECT1 # monitoring all day, starting with project 1
timew start MONITORING PROJECT1 PROJECT2 # adding project 2 to the pool
timew stop PROJECT1 # done with project 1, still monitoring and working at project 2
timew start MONITORING PROJECT2 PROJECT3 # adding project 3
... # something similar with PROJECT4 and PROJECT5
timew stop # done for today
```
This creates a consecutive chain of non-overlapping intervals in the database, keeping it thus sane and clean.

What you want is rather a report, which fuses/filters your simultaneous work into something like
```
timew my-report
MONITORING 8h
PROJECT1 4h
PROJECT2 2h
PROJECT3 5h
...
```

I agree that one could simplify the lines in the topmost example such that one must not re-enter the still running tags when starting a new one. Analogous to
```
timew start FOO BAR BAZ
stop FOO
```
which only would stop tracking for `FOO` but will keep tracking running for `BAR` and `BAZ`, e.g.
```
timew start FOO
timew start :add BAR
```
which would stop tracking for `FOO` and then create a new interval with tags `FOO BAR`.

**Comment by a7hybnj2** [comment]
Yes, that would be a great solution to what I wanted to do. Especially if this could be wrapped into the Hooks as well.

**Comment by lauft** [comment]
I split this into two separate issues and am therefore closing this
