### ISSUE TITLE
Allow mixing of relative and absolute dates/times

### ISSUE THREAD

**Issue by NotAFile** [GothenburgBitFactory/timewarrior#153]
This might just not be well documented, but I find myself often needing to specify absolute times on relative dates. Currently, I need to resort to either calculating it in my head "142 hours, 49 minutes ago" or specifying the full date and time.

For example, one thing that happens frequently, is that I forget to stop time tracking. Then, the next morning, I come back and see the following:

```
Tracking thing
  Started 2018-06-05T16:40:27
  Current         06T12:18:46
  Total              42:23:34
```

I know I stopped doing `thing` at 22:00 yesterday. However, there seems to be no good way to express this:

```
$ timew stop 22:00
Time tracking cannot be set in the future.
$ timew stop yesterday 20:00
Unrecognized date range: '<date> <date>'.
$ timew stop yesterday T22:00
The end of a date range must be after the start.
$ timew stop yesterdayT22:00
The current interval does not have the 'yesterdayT22:00' tag.
$ timew stop last 22:00
Time tracking cannot be set in the future.
$ timew stop yesterday at 22:00
Unrecognized date range: '<date> <date>'.
```

Similar problems arise when you try to specify things like "last Tuesday", or "the 25th of last month". I think the inability to specify a time on a relative date is the most inconvenient in daily usage, though.

I think the most intuitive thing would be to provide an "at" specifier that allows you to override a dates time?

**Comment by lauft** [comment]
Related to #130

**Comment by sruffell** [comment]
I run into this quite often as well in my past year of using timewarrior.  Often times I'll start my day, adding intervals. I will not realize that I left an interval open until I look at my summary for the week, and at that time I have to either edit the database file by hand or do relative time calculations.

This is what I often find myself trying to do, but failing:
```shell
$ timew stop @6 2018-11-08T16:32:00
There is no active time tracking.
$ timew shorten @6 2018-11-08T16:32:00
Shortened @6 by 0:00:00
```

**Comment by lauft** [comment]
Feel free to join a discussion on this topic in #196
