### ISSUE TITLE
[Question] Overlapping zero-width intervals

### ISSUE THREAD

**Issue by janikrabe** [GothenburgBitFactory/timewarrior#164]
While working on a fix for #101 and a related issue I noticed that a zero-width interval `Z = [p, p)` is **not** considered to overlap an interval `[p, q)`, where `q ≥ p`.

Currently, the following intervals overlap, as they should:

```text
a  p  q
[-----)
   Z
```

However, these two intervals do not overlap, even though the first interval is half-closed.

```text
p     q
[-----)
Z
```

This behavior is easy to change and would allow for zero-width intervals to be stored at the beginning of a datafile segment. Currently, attempting to add a zero-width interval to the beginning of a segment results in an assertion failure because there is no overlap and therefore nothing to store in the datafile. (#101)

```text
    Jan        Feb
[---------)[---------)
           Z

=> overlap(Feb, Z) = false
=> Feb ∩ Z = [NULL, NULL)
```

However, this change would make it impossible for users to store multiple intervals with the same start time. For example:

```text
[---)                 # Unrelated interval A
               [---)  # Unrelated interval B
        Z             # Zero-width interval at point p
[------------------)  # Interval computed by Timewarrior for overlap checking
        [---)         # Interval the user attempts to add
```

In this case, the zero-width interval overlaps the computed interval, so it is used for overlap checking. The zero-width interval would then (with this change) overlap the new interval the user wanted to add, because both intervals cover point `p`, and Timewarrior would cancel the transaction.

Two tests currently rely on being able to start an interval `[p, ∞)` when there already is a zero-width interval `Z = [p, p)` in the database:

* [`TestClock.test_start_additional`](https://github.com/GothenburgBitFactory/timewarrior/blob/1.1.1/test/clock.t#L96)
* [`TestClock.test_start_subtract`](https://github.com/GothenburgBitFactory/timewarrior/blob/1.1.1/test/clock.t#L120)

Worse, this change would cause problems with existing databases. For this reason it is necessary to leave the overlap checking in [`validate.cpp`](https://github.com/GothenburgBitFactory/timewarrior/blob/1.1.1/src/validate.cpp#L106) unchanged.

Proposed solutions, in order of preference:

* Create a `lenientOverlap()` method with the current behavior for use during overlap checking, and change the current [`overlap()`](https://github.com/GothenburgBitFactory/timewarrior/blob/1.1.1/src/Range.cpp#L133) method to use the more consistent and logically correct behavior. This is the best solution in my opinion.
* Do the opposite, creating a `strictOverlap()` method instead.
* Make the `overlap()` method asymmetric, so that `A` may overlap `Z` without `Z` overlapping `A`. I find this solution counter-intuitive and would not recommend it.

Any thoughts? @lauft

**Comment by lauft** [comment]
After pondering this a while I think we have to separate whether we want to check
- if an interval *encloses* another interval or
- if an interval *overlaps with* another interval.

Your zero-width interval `Z` lies within the segment but the overlap (with other intervals) is zero. There already is the function `Range::encloses(const Range& other)` which serves this purpose. So can we use this to determine in which datafile the interval should be stored?
