### ISSUE TITLE
getTracked behaves incorrectly when latest interval is empty

### ISSUE THREAD

**Issue by janikrabe** [GothenburgBitFactory/timewarrior#166]
```text
$ timew start
  Tracking […]

$ timew stop
  Recorded […]

$ timew resize @1 0
  Resized @1 to 0:00:00

$ timew start
  Tracking  […]

$ timew stop
  Recorded  […]

$ timew resize @1 0
  Resized @1 to 0:00:00

$ timew summary :year :ids
  (shows both IDs, @1 and @2, as expected)

$ timew move @2 2018-01-01
  ID '@2' does not correspond to any tracking.
```

This is due to how `getTracked()` computes the default filter if no other filter is specified: it uses the earliest start time and the latest end time of any interval in the database. This results in an interval like this:

```text
filter:  [----------)
     A:  Z
     B:             Z
```

Here, `B` is a zero-width interval, so it does not overlap `filter` and is excluded from the list of tracked intervals returned by `getTracked()`.

This also means that attempting to modify `@n` will instead modify `@n+1`.

**Comment by lauft** [comment]
Somehow github did not recognize the manual merge of your pull request. So I close this manually as well. :)
