### ISSUE TITLE
Create new database in ~/.timewarrior (yes/no)

### ISSUE THREAD

**Issue by lasers** [GothenburgBitFactory/timewarrior#168]
Hi. When a script runs `timew export` and there is no database, the script can be stuck there waiting because of `Create new database in ~/.timewarrior (yes/no)` question.

How can I skip this behavior? Another question... If `~/.timewarrior` is not initialized (eg nonexistent dir), why do you need to ask us this first instead of initializing? Sorry, I'm not familiar with `timew`. 

This is not a big problem because I can initialize it manually. I think the behavior could be different when we use `timew export` or other commands without a database. Thank you.

**Comment by janikrabe** [comment]
If you don't mind initializing a new database you can pass the `:yes` hint to Timewarrior:

```sh
timew export :yes
```

Some people choose to store their database in a different location by setting `$TIMEWARRIORDB`. In this case, the prompt you mentioned prevents people from accidentally storing some of their logs in `~/.timewarrior` when `$TIMEWARRIORDB` is not set.

**Comment by lasers** [comment]
Thank you for responding back with `:yes`. I don't see anything about `:no`.

Would you like to test my script? https://github.com/ultrabug/py3status/pull/1150 You need to be on `i3wm` and `i3pystatus` to test this module. The specific problem is that I don't want my module to automatically initialize databases and at same time, skip (instead of `:yes`) when there is no database.

I can work on that module some more to better cater to yours and other users' needs to ensure that everybody are going to have a great timew.

**Comment by lauft** [comment]
Done. Thank you for using and promoting TimeWarrior!
