### ISSUE TITLE
[TI-10] The 'total' summands in the month report are not aligned with the column name

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#18]
_Tomas Babej on 2016-06-12T14:57:38Z says:_ 

 See attached picture for illustration. Any data file containing at least one interval can reproduce this.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-06-12T14:57:38Z
Modified: 2016-07-02T10:01:50Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-06-29T00:16:35Z says:_ 

 I have tried every combination I can think of, and cannot reproduce this with HEAD.  Do you have an example?

**Comment by taskwarrior** [comment]
_Tomas Babej on 2016-07-01T12:36:00Z says:_ 

 I'm starting to think this might be somewhat terminal related, since I cannot not reproduce it with HEAD (unless I truncate all my timew data) :)

**Comment by taskwarrior** [comment]
_Tomas Babej on 2016-07-02T10:01:39Z says:_ 

 Okay, the problem was that I was still tracking master instead of 1.0.0 branch. Issue is fixed.

**Comment by pbeckingham** [comment]
![ti-10_selection_011](https://user-images.githubusercontent.com/7963/36635164-4b142d6a-197e-11e8-8435-de73bd2ad649.png)
