### ISSUE TITLE
Typo with a lot of spanes and repeating letters results in std::bad_alloc error on ubuntu, and slow high cpu% behavior on mac [V 1.1.1]

### ISSUE THREAD

**Issue by arooni** [GothenburgBitFactory/timewarrior#184]
I meant to record this a bit differently but it lead to an interesting error.  Saw this on both timewarrior on mac and ubuntu v1.1.1 in both cases.

inc 20181025T201745Z - 20181025T211103Z # "settinnnnnnnnnnnnnnnnnnnnnnnnnng up kitty                           finisssssssssssssssssssssssssshing up"

my keyboard was a bit laggy and lead to this as i was describing setting up kitty terminal emulator (amazing btw).

Anyway when I ran timew day; on ubuntu I saw std::bad_alloc whereas on mac it took just about forever and ran up 90% of the cpu for a long while before spitting out output.

Not sure if this is useful but hopefully it is.

**Comment by lauft** [comment]
I could not reproduce this on my system (ubuntu 16.04), so which are you using?
Can you reproduce this in an isolated environment like this:
```
# Setup
mkdir -p /tmp/timewarrior/data
export TIMEWARRIORDB=/tmp/timewarrior
:> ${TIMEWARRIORDB}/timewarrior.cfg
# Test
timew track 17:45 - 21:11 "settinnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn up kitty...."
timew day
```
?
