### ISSUE TITLE
Plumbing commands for scripting

### ISSUE THREAD

**Issue by Valodim** [GothenburgBitFactory/timewarrior#187]
Hey folks,

great project, thanks for your work so far!

I noticed there is no zsh completion and wanted to contribute one. However, all timewarrior commands seem to be UI and unsuitable for use as scripting. Perhaps I missed something, but I unable for instance to find a command that just outputs all tags in a machine-readable manner. `timew get` looks like it might to be intended for this purpose, but it's fairly limited so far.

Are there any plans to improve timewarrior's machine-readable interface?

**Comment by lauft** [comment]
Hi!
Improving `timew get` (also to deliver tags) is planned (see e.g. #126) but not worked on at the moment. I am opening a new issue for your request concerning tags...

[bash completion](https://github.com/lauft/timew-bashcompletion) works around this via 
```timew tags | awk '{if(NR>3)print $1}'```

**Comment by Valodim** [comment]
> bash completion works around this via
> timew tags | awk '{if(NR>3)print $1}'

that's pretty awful and I'd like to avoid it if at all possible :) definitely also looking forward to query commands for ids and their properties. I'm not sure how the issues are managed here, seems like there is some redundancy now. Feel free to close this one if it doesn't add useful info.

**Comment by lauft** [comment]
I agree, but as said, it is a workaround. :)

I try to keep issues small and concise, so I rather spawn new tickets from generic ones than to narrow them down. Saying this, is there anything else that would be helpful for your zsh completion? Currently DOM-Query tickets are not in any milestone, but increasing demand definitely heightens priority...
