### ISSUE TITLE
Configuration is not consistent with taskwarrior

### ISSUE THREAD

**Issue by somospocos** [GothenburgBitFactory/timewarrior#193]
My observations are based on stable 1.1.1 version, but I have skimmed through the most recent version of the manpage of the repository on github and the situation is the same.

1. Taskwarrior has a simple and elegant config approach: ~/.taskrc with settings, for Timewarrior the default location is rather ~/.timewarrior/timewarrior.cfg This is the first double inconsistency: the naming one (why not .timewrc?) and the location one. I like the Taskwarrior approach more, the config file is separate from the database files

2. Taskwarrior even has a separate manpage for taskrc that only focuses on content of that file

3. Taskwarrior has an elegant way to separate customization of config and data locations through TASKRC and TASKDATA environment variables, as well as data.location setting in .taskrc. While Timewarrior has a section named CONFIGURATION FILE AND OVERRIDE OPTIONS in the manpage while suggests "using the environment variable $TIMEWARRIORDB can be set to override this location". Notice the inconsistency in wording: "location" (what location? the config file itself? the ~/.timewarrior directory?) as well as in naming. What does this variable actually change? The location of configuration file? The one of data? The location of the whole default ~/.timewarrior directory? Super confusing. What disappointed me even more is that the current situation seems to look fine to more experienced Timewarrior users, so this is an established inconsistency. See this comment for example https://github.com/GothenburgBitFactory/timewarrior/issues/168#issuecomment-415311815 Notice how this comment says "the database" which kind of conflicts with what's stated in the manpage (again, I repeat that the manpage mentions this in context of the config file!) unless I'm misunderstanding it.

For me as an end user not being able to dive into Timewarrior code and modify it myself, it would be highly more comfortable if Timewarrior supported the same approach so I wouldn't have to maintain two inconsistent sets of config files for two pieces of software that share the same authors, serve similar purposes and can even work together:

- Timewarrior could have a ~/.timewrc default config file
- this config file would have its own manpage just like Taskwarrior
- ~/.timewarrior directory would only contain data files, this default location could be changed through a similar data.location setting in ~/.timewrc
- $TIMEWARRIORDB would just disappear in favor or $TIMEWRC and $TIMEWDATA

I would be extremely happy if the next stable release of Timewarrior would scratch this itch

**Comment by lauft** [comment]
I am afraid this itch will last a bit longer - the configuration setup will definitely not be changed with 1.2.0.

Timewarrior data is connected to its configuration, especially if it comes to exclusions and chart
configurations. So it makes sense to me to store them in the same place. 

Your suggestions will be taken into account for the further development of Timewarrior, however I cannot promise they will be implemented as suggested - except for the separate man page for the configuration file. This is coming soon...

**Comment by somospocos** [comment]
> Timewarrior data is connected to its configuration, especially if it comes to exclusions and chart
configurations. So it makes sense to me to store them in the same place.

I really hope this makes it to the mentioned manpage, perhaps even a bit more detailed. The perspective of a developer who knows the codebase best will help new users understand certain design choices.

**Comment by lauft** [comment]
Man pages have been updated 7538cbf2..3780966c. Not perfect, but it is a start.
