### ISSUE TITLE
Clarification around "track" for previous days

### ISSUE THREAD

**Issue by gms8994** [GothenburgBitFactory/timewarrior#195]
https://taskwarrior.org/docs/timewarrior/track.html suggests that you can use `:yesterday` or `9am - 11am` to track missed time. Can you combine these? For example, I forgot to track a meeting I was in yesterday from 9am - 11am. Would that be something like `timew track "2018-12-12 9am" - "2018-12-12 11am" "Meeting with the Bobs"`?

**Comment by lauft** [comment]
Currently date ranges have to be specified as ISO-Datetimes
```
timew track 2018-12-12T09:00 - 2018-12-12T11:00 
timew track 20181212T0900 - 20181212T1100
```
 or (simple) times
```
timew track 09:00 - 11:00
timew track 9am - 11am
```
but the latter assumes today as current date.

**Comment by lauft** [comment]
Feel free to join the discussion on #196 about this topic.
