### ISSUE TITLE
Generate a warning when a new tag is used on the command line

### ISSUE THREAD

**Issue by pbeckingham** [GothenburgBitFactory/timewarrior#2]
A new tag could be an indicator of a spelling mistake, and a warning could be useful.  It should be configurable.

This feature was added in the past and then removed because it was implemented at the DB level, and the "modify" API call performed a "delete" then "add" call, which triggered a false positive for this warning.

**Comment by lauft** [comment]
#42 is the corresponding bug ticket

**Comment by lauft** [comment]
I think Timewarrior needs a dedicated tag database which keeps track of the tags. Such a database would also be an solution for #102
