### ISSUE TITLE
Wrap annotations in summary

### ISSUE THREAD

**Issue by varac** [GothenburgBitFactory/timewarrior#205]
Please wrap the annotation into multiple colums, otherwise it doesn't make too much sense if you can't read it in the summary:

```
 timew summary :annotations :id oas    

Wk Date       Day ID Tags      Annotation        Start     End    Time   Total
W6 2019-02-07 Thu @1 +123, oas Working my a... 0:31:51 0:32:50 0:00:59 0:00:59
                                                                              
                                                                       0:00:59
```

i.e. like this:

```
 timew summary :annotations :id oas    

Wk Date       Day ID Tags      Annotation        Start     End    Time   Total
W6 2019-02-07 Thu @1 +123, oas Working my ass  0:31:51 0:32:50 0:00:59 0:00:59
                               off after an al-
                               ready long day                     
                                                                       0:00:59
```

**Comment by grovesteyn** [comment]
While you are at it, it will also be useful to allow the summary report to be wider.  This will be very useful if the report contains more or longer fields as shown above (numerous tags and annotations).

Perhaps this relates to all timew output which might be premised on a standard screen width.

A wider screen width (or report width) preference could be specified in timewarrior.cfg.

**Comment by CreativeLibre** [comment]
@grovesteyn You write that you can configure this in timewarrior.cfg, but how? Unfortunately the documentation is very poor and I can't find anything at all. What do I have to enter in the config so that the column width of the annotation becomes wider with the "summary" command?

**Comment by drebs** [comment]
> @grovesteyn You write that you can configure this in timewarrior.cfg, but how?

Currently, the maximum length of 15 chars for the annotations column in the summary is [hard-coded and can't be configured](https://github.com/GothenburgBitFactory/timewarrior/blob/c8a85850ea01befc652e57fd6c2de73a1ed0eee9/src/commands/CmdSummary.cpp#L233).

(I believe @grovesteyn was proposing one possible way to change the configuration (by saying "could be specified in timewarrior.cfg"), and not referring to something that is already implemented.)

Making the annotations column length in summary configurable seems to be a fairly simple change, I wonder whether author(s) would be interested in a patch and, in such case, whether they have any concerns that should be taken care of in implementation proposals.

**Comment by lauft** [comment]
I'd be happy if a PR making the maximum width of the annotations column configurable would also take unicode character widths into account (see https://github.com/GothenburgBitFactory/timewarrior/pull/529#issuecomment-1508193650).

A more complete solution (apart from wrapping) would be to let the annotations column width grow until the summary table hits the terminal width an only then to apply the cut off. 🤔 (Currently, the summary table width is [fixed to 1024 characters](https://github.com/GothenburgBitFactory/timewarrior/blob/84fdf76f9aba22d9badbcbdf92942714cb5e254f/src/commands/CmdSummary.cpp#L124).)

**Comment by lauft** [comment]
Version 1.6.0-dev and onward now wrap the annotation column in the summary table.
<img width="500" alt="Timewarrior - Summary Table" src="https://github.com/GothenburgBitFactory/timewarrior/assets/8539295/146870b2-796c-44db-b4de-f1aecdb40f4c">

The table (maximum) width is also no longer hardcoded/fixed, but set to the current width of the terminal.
