### ISSUE TITLE
Add :all hint

### ISSUE THREAD

**Issue by varac** [GothenburgBitFactory/timewarrior#206]
It would be great to have a `:all` hint which could be used to display all intervals over the years (or is there already a function for this that I'm not aware of?).

**Comment by lauft** [comment]
You could use the Datetime aliases `soy` and `eoy` to achieve (some of) this:
```
timew summary soy - eoy
```
An `:all` hint could be handy for commands `summary` and `month`/`week`/`day` nevertheless...

**Comment by sruffell** [comment]
I think this needs to stay open. The summary command, as it is currently implemented, does not work with open ranges as a filter, since it will auto close any open interval to a day after the start.

**Comment by lauft** [comment]
@sruffell As all current test are currently passing I would open a new issue with a respective reproducer/test.
