### ISSUE TITLE
Assign a dedicated color to a tag

### ISSUE THREAD

**Issue by wuxua** [GothenburgBitFactory/timewarrior#211]
I frequently use  `month` and `week` without filtering a tag to visualize and compare how much I worked on different projects. It would enhanced the visualization aspect if I could assign a dedicated color to a tag. I would also like to assign a dark color to wasted time and a lighter color to productive time.

**Comment by lauft** [comment]
You can assign a specific color to a tag by `timew config tags.<tag>.color <color>` where `<tag>` is your dedicated tag and `<color>` is something like `white`, `red`, `gray8` or `"black on yellow"` or `rgb345`.

Alternatively you can enter the following lines into your `${TIMEWARRIORDB}/timewarrior.cfg`:
```
tags.PROD1.color = red
tags.PROD2.color = gray8 
tags.WASTE1.color = black on yellow
tags.WASTE2.color = rgb345
```

**Comment by wuxua** [comment]
Perfect, thank you.

**Comment by limdingwen** [comment]
Would it make sense to document this inside something like `man timew-tags`?

**Comment by lauft** [comment]
> Would it make sense to document this inside something like `man timew-tags`?

Sure, documentation updates are always welcome. 🙂
