### ISSUE TITLE
unable to delete or split interval

### ISSUE THREAD

**Issue by psychoslave** [GothenburgBitFactory/timewarrior#213]
Hello,

I'm just starting to use timewarrior, so first thanks for this FLOSS time tracking solution.

# The quick report

```
$ cat /etc/fedora-release 
Fedora release 29 (Twenty Nine)

$ timew --version # I lazily installed the software through dnf
1.1.1

$ timewarrior s :yesterday :ids | tail -n4 | head -n1
                  @6  some_tag                            21:04:25  0:00:00 2:55:35 23:59:59

$ s split @6
timew: /builddir/build/BUILD/timew-1.1.1/src/Datafile.cpp:111: void Datafile::deleteInterval(const Interval&): Assertion `_range.overlap (interval.range)' failed.
Aborted (core dumped)
```

# Some context

I want to track my whole day, sleeping time included. As I'm just starting I might just need more guidance regarding how to better manage my reporting, but it seems I fall into some bug while trying to change my last entry of yesterday in order to add what I've done in the mid time.

I also tried to simply delete @6 above, but it failed in the same way.

# Side note

I'm also interested with hints and tips on how to better handle my input of yesterday. I like the way `track` assume the inputed time pertain in the current day hour, in the past. But when I'm in the morning, just typing `timew track 22:00` won't lead to assume I mean from yesterday 22:00 to now. Is there an handy way to state just that?

**Comment by lauft** [comment]
Is `some_tag` a placeholder or the actual tag? If a placeholder, does the original tag contain any characters besides `[a-zA-Z0-9]`?

**Comment by lauft** [comment]
Currently, Timewarrior assumes `today` for every time (without date) entered. So in the morning `22:00` is in the future, not yesterday. There is #196, where a future feature to support a bit more flexible data format on the command line, e.g. `timew track :yesterday 22:00`.

**Comment by psychoslave** [comment]
Thank you @lauft. Yes, my example tag was a placeholder. the actual tags where the following:

                  lecture, l’existence a-t-elle un sens, philosophie                            21:04:25  0:00:00 2:55:35 23:59:59

So I guess the problem is that I used a `’` character (a typographic apostrophe). I'm astonished with a limitation to `[a-zA-Z0-9]` for tags, if it is indeed how it is coded. Something like `[:alphanum:]` would be a better start for such field, wouldn't it?

But I would be ok to remove the `’` for now. I guess the quickest way to do so is to edit the text files that constitute my DB, doesn't it?

**Comment by psychoslave** [comment]
So, as indicated above, I just edited the file directly with `$EDITOR` and that was it for bypass the issue, although a better support of unicode would remains a good idea.

Cheers

**Comment by lauft** [comment]
Unicode support is definitely the desired goal.
