### ISSUE TITLE
Please support descriptions for ids/booked times

### ISSUE THREAD

**Issue by bzed** [GothenburgBitFactory/timewarrior#214]
Hi,

please support to add a description for every booked time range.
Using tags is perfect to assign a time range to a customer or project, but if you need to provide a detailed description of what you've done for a customer/project at the end of the month, you'll have to track it in an extra file/tool. So something like

timew describe \<id\> "description here"

would be really awesome to have.

Thanks,

Bernd

**Comment by lauft** [comment]
Timewarrior 1.2.0 will have a command `annotate` which you can use like 
```
timew annotate @<id> "Lorem ipsum..."
```
see also #68

**Comment by bzed** [comment]
Thanks @lauft , then I'll close this bug again, tracking it in #68 is enough.
