### ISSUE TITLE
[TI-14] Warn when new tags are being created

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#22]
_Matthias Rieber on 2016-06-24T08:20:58Z says:_ 

 I think it would be nice to have a warning when a new tag is added to avoid typos like:

```
$ timew start meeeting
WARNING new tag: meeeting \[y/n\]
```

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-06-24T08:20:58Z
Modified: 2018-01-13T08:52:26Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-06-24T11:59:49Z says:_ 

 That's a good idea!  Thanks.

**Comment by taskwarrior** [comment]
_Daniel Shahaf on 2016-06-25T09:56:54Z says:_ 

 Is this something that can be handled by shell completion?  So `timew start mee<TAB>` would complete to `meeting`?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-06-25T11:16:17Z says:_ 

 Yes, that would be nice.  But right now, there is no completion support command that would enumerate tags.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-07-02T17:59:50Z says:_ 

 Feature added as verbose feedback when a new tag is encountered, but not an error.  Mathias added as contributor.

**Comment by taskwarrior** [comment]
_lumbric on 2017-11-28T14:52:30Z says:_ 

 I think this needs to be reopend. The feature has been commented out in 45b09986d (on 23rd July 2016, i.e. before releasing v1.0.0).

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-12-02T18:54:32Z says:_ 

 New tags are hard to spot because of the API used. I think I see a nice workaround.  Reopening.

**Comment by lauft** [comment]
#2 #42

**Comment by lauft** [comment]
I am closing everything related to this topic except for #2. Further discussion should take place there.
