### ISSUE TITLE
TimeWarrior v1.2.0 cannot handle 0-9 hours without leading zeros (in date+time format)

### ISSUE THREAD

**Issue by sskras** [GothenburgBitFactory/timewarrior#223]
Short format interval is fine:
```
$ timew summ 2019-03-29 - 2019-05-02 | wc -l
542
```

Long format interval gives an error:
```
$ timew summ 2019-03-29T14:50:55 - 2019-05-02T8:43:02 | wc -l
Unrecognized date range: '<date> -'.
0
```

It would help automating my monthly reports a lot.

**Comment by lauft** [comment]
Try to use leading zeros when specifying hours. Does it work with
```
timew summ 2019-03-29T14:50:55 - 2019-05-02T08:43:02
                                            ^
```
?

**Comment by sskras** [comment]
Yes, this way it works:
```
$ timew summ 2019-03-29T14:50:55 - 2019-05-02T08:43:02 | wc -l
524
```

How did I come to this?  I just concatenated two parts of the TimeW output plus a "T", and it didn't work.

Help says:
```
  extended-time:
    hh:mm[:ss]Z                         Hours, minutes, optional seconds, UTC
    hh:mm[:ss][+/-hh:mm]                Hours, minutes, optional seconds, TZ
```

I expected an output time format to match an input one.
Is it a bug or a feature?

**Comment by lauft** [comment]
Rather a feature. Help says:
> Timewarrior supports the following date formats based on ISO-8601
Concatenating date and time with "T" implies ISO-8061 and according to ISO-8601, padding zeros are required.

**Comment by sskras** [comment]
Thanks.  Can you remind me whether it can output an ISO-8601 date too?  
I think I saw it in an output of some command but cannot remember which it was.

**Comment by lauft** [comment]
`timew get` outputs ISO-8601 date times, e.g.:
```
timew get dom.tracked.<id>.start
timew get dom.tracked.<id>.end
```

**Comment by sskras** [comment]
Thank you. Should I get some inconsistency in output in future, I will create another issue.
