### ISSUE TITLE
Using those date aliases don't function as intended

### ISSUE THREAD

**Issue by RainbowSwirls** [GothenburgBitFactory/timewarrior#228]
Trying to create date intervals with the date aliases doesn't seem to work for me. All I get is the error message "Time tracking cannot be set in the future.".

Examples:
```
$ timew summary 26th - 30th
Time tracking cannot be set in the future.
$ timew summary monday - now
Time tracking cannot be set in the future.
$ timew summary april - may
Time tracking cannot be set in the future.
```

Timew --version
`1.1.1`

OS Info
```
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.0.4
DISTRIB_CODENAME=Illyria
DISTRIB_DESCRIPTION="Manjaro Linux"
```

python --version
`Python 3.7.3`

**Comment by lauft** [comment]
Thanks for your report. The problem was already partially fixed in the dev branch, the pull request https://github.com/GothenburgBitFactory/libshared/pull/17 should have done the rest.
