### ISSUE TITLE
Taskwarrior on-modify.timewarrior hook: Error: Expected 1 JSon task(s), found 0

### ISSUE THREAD

**Issue by joehannes** [GothenburgBitFactory/timewarrior#229]
I'm on xubuntu 18.04, zsh, tried various combination (self-compiled) of taskwarrior, timewarrior, plus various official hook versions.
Always the same result.

The script doesn't print a proper json task, such that the hook returns an error msg plus while timew gets kicked off taskwarrior isn't doing anything -> broken.

I solved it by hacking the hook script.
Instead of printing a json.dumps version of new I do the following:

```
rawnew = sys.stdin.readline()
new = json.loads(rawnew)
print(rawnew)
```

that solves the issue for me

**Comment by lauft** [comment]
Could you provide a minimal example to reproduce the error? Thanks

**Comment by joehannes** [comment]
It's probably a setup issue:
I'm on Xubuntu 18.04
python = python 2
python3 = python 3.6.7
taskwarrior = 2.5.1
timewarrior = 1.1.1

but I tried various versions/constellations, so it might be down to (x)ubuntu (18.04)
basically:
just try to start any task with taskwarrior and the timewarrior hook set in place

Example:
> task 1 start
# Hook Error: Expected 1 JSON(s), found 0
-> taskwarrior doesn't start the task, timew does ... since taskwarrior didn't start the task a conscutive task 1 stop will also not stop timew.

Analysing the situation I found that it must be down to the output of the hook, which then taskwarrior uses to continue it's work. Since it doesn't get anything, it errors out with that message.
printing the raw unparsed new instead of the first json.loads then json.dumps new I don't get the error, it returns a json taskwarrior understands, everything works fine.
Cheers, J
Johannes Neugschwentner
There's more to it ...

E: johannes.neugschwentner@gmail.com (https://link.getmailspring.com/link/ED5EA977-0814-4DE4-963F-5363CAEEFF8E@getmailspring.com/0?redirect=mailto%3Ajohannes.neugschwentner%40gmail.com&recipient=cmVwbHkrQUFMSzNCM0tESlFUT0NJN0ZFQ1NBRjUzQU8yU1JFVkJOSEhCVjNKUkJZQHJlcGx5LmdpdGh1Yi5jb20%3D)
P: +1 829 9079479 (tel:+1%20829%209079479)

**Comment by ytee** [comment]
I also face this issue, but unlike @joehannes mentioned, i could not get it working with the temporary json dumps too. Can you share your on-modify hook file?

**Comment by lauft** [comment]
Could you provide a minimal reproducer like below?
```
# Setting up the evironment...
export TASKRC=/tmp/taskwarrior/taskrc
export TASKDATA=/tmp/taskwarrior/task
mkdir -p ${TASKDATA}
rm -rf ${TASKDATA:?}/*
:> ${TASKRC}

# The commands that reproduce the error...
task ...
```

Doing
```
$ task add Foo
$ task 1 start
```
should result in Taskwarrior emitting the something like two following JSON-lines:
```
{"description":"Foo","entry":"20190820T201911Z","modified":"20190820T201911Z","status":"pending","uuid":"53fc2940-f1a3-4225-8f11-0d0fb7eead54"}
{"description":"Foo","entry":"20190820T201911Z","modified":"20190820T201911Z","start":"20190820T201911Z","status":"pending","uuid":"53fc2940-f1a3-4225-8f11-0d0fb7eead54"}
```

What is the output of taskwarrior in `/tmp/on-modify.dump` if you install this `on-modify.dump` hook-script:
```
#!/bin/sh

read original_task
read modified_task
echo "${original_task}" > /tmp/on-modify.dump
echo "${modified_task}" >> /tmp/on-modify.dump
echo "${modified_task}"
echo 'on-modify'
exit 0
```
and call e.g. `task 1 start`?

**Comment by Walsen** [comment]
Hi, 

I'm having the same problem.
I'm on Fedora 31.
taskwarrior: 2.5.1.
timewarrior: 1.1.1.

 This is what I did:
```sh
❯ task add test issue
Created task 6.
❯ task 6 start
/home/user/.task/hooks/on-modify.timewarrior: line 39: syntax error near unexpected token `('
/home/user/.task/hooks/on-modify.timewarrior: line 39: `old = json.loads(sys.stdin.readline())'
```
I tried the hook mentioned in the previous comment and got this:
```json
{"description":"test issue","entry":"20191206T020017Z","modified":"20191206T020017Z","status":"pending","uuid":"c8bd3be3-bd85-422a-865a-938507c393c7"}
{"description":"test issue","entry":"20191206T020017Z","modified":"20191206T020017Z","start":"20191206T020024Z","status":"pending","uuid":"c8bd3be3-bd85-422a-865a-938507c393c7"}
```

Thanks for the help.

**Comment by lauft** [comment]
Judging from the output `... line 39:  'old = json.loads(sys.stdin.readline())'` your `on-modify.timewarrior` seems outdated. 

Can you copy the current hook from Timewarrior 1.2.0 to your extension directory and check whether the problem persists?

**Comment by Walsen** [comment]
After replacing the file `on-modify.timewarrior` with the one in the repo, it is working well. Thanks very much!
