### ISSUE TITLE
Unicode Encode Error when calling totals.py after using the tag `lektüre`

### ISSUE THREAD

**Issue by esthet1cs** [GothenburgBitFactory/timewarrior#231]
1. Problem: UnicodeEncodeError when calling `timew totals`. I think this has to do with me using non-ASCII characters within my tags, in this case probably `ü`.

2. Reproduce: Put `ü` into a tag, e.g. `lektüre` (fancy german word for reading), and then run `timew totals`

The error message reads:

`Traceback (most recent call last):
  File "/home/cms/.timewarrior/extensions/totals.py", line 158, in <module>
    for line in calculate_totals(sys.stdin):
  File "/home/cms/.timewarrior/extensions/totals.py", line 138, in calculate_totals
    output.append("{:{width}} {:10}".format(tag, formatted, width=max_width))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 4: ordinal not in range(128)`

My system:
Debian Linux unstable
timew version 1.1.1
Python 2.7.16 / 3.7.3

Solution in my case: Demand Python 3 at the beginning of the script `totals.py` explicitly with 
`#/usr/bin/env python3`. It would probably also work to just use Python 3 by default, but on some systems this might not be feasible.

Since this problem might affect other installations that use Python 2 and Python 3 I'm putting this here also for documentation purposes.

**Comment by lauft** [comment]
Obsolete with the switch to python 3 (#259)
