### ISSUE TITLE
Not Found Documentation on Timewarrior site

### ISSUE THREAD

**Issue by xdhmoore** [GothenburgBitFactory/timewarrior#238]
The timewarrior documentation link on the home page seems to lead to a "Page Not Found":

https://taskwarrior.org/docs/timewarrior/

**Comment by xdhmoore** [comment]
Looks like it's back up.

**Comment by lauft** [comment]
Documentation has been moved from https://taskwarrior.org/docs/timewarrior/ to https://timewarrior.net/docs/
