### ISSUE TITLE
Configure interval aliases

### ISSUE THREAD

**Issue by croesch** [GothenburgBitFactory/timewarrior#242]
I would like to specify custom intervals like "the last two weeks" or "the last four weeks". Because at the beginning of the week, month, quarter or year I don't have a lot of entries to summarize.

So I'd like to have something like
```
$ timew summary 2*:week
or
$ timew summary :two_weeks
```

**Comment by lauft** [comment]
This already works:
```
$ timew summary 2weeks
$ timew summary 2w
```

**Comment by croesch** [comment]
Oh - just thanks ;)
