### ISSUE TITLE
Use embedded database for data files

### ISSUE THREAD

**Issue by sruffell** [GothenburgBitFactory/timewarrior#244]
This is more of a question, but I did not see any reference to mailing list for for asking questions.

I was looking at issue #155 and one non-trivial problem is ensuring that the writes to the db, tags, and undo file are atomic with respect to one another. I believe this is something that an embedded database, like sqlite, would excel at. 

Is this something that the project would consider? Are there too many dependencies on the specific format of the database file?

If you're open I could do the work, but I don't want to waste my time if there is a reason you wouldn't consider the change.

**Comment by lauft** [comment]
I have already thought about this myself. However I see some issues which need to be addressed - first and foremost:

* Timewarrior shares the [Taskwarrior project philosophy](https://taskwarrior.org/docs/philosophy.html) which states
    > Your data is kept as plain text, and never held hostage by a proprietary format.

This is not neccessarily the death blow to your proposal, but a very important point to consider. A solution to this could be to make the choice of database an option for the user. To achieve this we need to address

* How can we make the choice of database configurable?
* Abstraction: Timewarrior should use the database via an abstraction layer. This should make it easier to switch databases.
* Dependency management: How is squlite (or any other database) included? I do not like the thought having another git-module included into the project. Could a package-manager like [conan](https://conan.io) help with that...?

I am already working on an abstraction layer for the database, which I want to push to dev as soon as release 1.2.0 is out. As soon as this is done we can go on with the next steps...

**Comment by sruffell** [comment]
Ok, I won't spend too much time until I've had a chance to look at the database abstraction layer.

To address some of your points / questions:

>- How can we make the choice of database configurable?

I would prefer to **not** make the choice of database configurable, especially if there are potentially different features provided by each backend. If the project needs to support the current data format going forward, then I believe any attention should just be focused on making a single format work as best we can.

>- Abstraction: Timewarrior should use the database via an abstraction layer. This should make it easier to switch databases.

I do not disagree here. However, If the database abstraction layer provides the concepts of transactions across different data files, then I personally would not have a strong reason to switch to another backend. I've never had any performance problems with the current data formats.

>- Dependency management: How is squlite (or any other database) included? I do not like the thought having another git-module included into the project. Could a package-manager like conan help with that...?

If timewarrior did eventually want to incorporate something like sqlite, my recommendation would be to just add the [amalgamation](https://www.sqlite.org/amalgamation.html) file directly to the source.

**Comment by bzed** [comment]
Plain text files have a big advantage: if something goes wrong, you can still use your favourite editor. Getting a backup and restoring parts of the data is also easy. 
For those with performance issues: is it really an issue, or just slower than a fresh install?

**Comment by tom-doerr** [comment]
It is an issue if you use timewarrior a lot. If I would have not deleted the database I would be waiting multiple hours a year just for timewarrior to start and stop the tracking. 
Having said that, this issue could be fixed without using an embedded database if we optimize the way timewarrior accesses the data files. It's just that this optimization might be unnecessary if timewarrior switches to a more powerful database.

**Comment by sruffell** [comment]
Closing this out. With the speed and consistency changes made recently, I'm not sure I see a huge advantage anymore to switching to an embedded database.
