### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by tom-doerr** [GothenburgBitFactory/timewarrior#245]
### The issue 
Executing `timew start test` takes around 0.9 seconds when there is no active tracking and around 1.4 seconds when there is.
Compared to 0.004 seconds on a fresh install, this seems rather slow.
Currently I wait almost an hour per month for the tracking to start.

### What I tried 
* Remove undo.data
* Remove extensions

### Setup
Currently I have 17000 records in my database, 1000 of them are from this month.

`timew diag`:
```
timew 1.0.0
       Platform: Linux

Compiler:
        Version: 7.2.0
           Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
     Compliance: C++11

Build Features
          CMake: 3.9.5
     Build type: None

Configuration
  TIMEWARRIORDB: -
            Cfg: /home/tom/.timewarrior/timewarrior.cfg (-rw- 0 bytes)
       Database: /home/tom/.timewarrior (lrwx 4096 bytes)
    Color theme: Built-in default
                 00 01 02 03 04 05 06 07 08 09 10 11 12

Extensions
       Location: /home/tom/.timewarrior/extensions (drwx 4096 bytes)
               (None)

```

### Theory
I installed timewarrior in a docker container and added around 4500 records. Starting tracking when timewarrior already is tracking something took 0.3 seconds.
Since I only have 1000 records for this month and it takes 1.4 seconds, this suggests timewarrior is accessing the whole database and not just the file for the current month.

Is there any way to increase performance?

### Update
I moved the data files for the months prior to this one, which results in a 20x speedup. 
It would still be nice if we could find a better solution, since now it is not possible to view older data. 
#244 could be the solution.

**Comment by lauft** [comment]
Thank you for your detailled report!
You already pinpointed the problem: Timewarrior is loading the complete database when accessing data. 
The solution is to make data access more efficient, i.e. only load the actually needed data. This is definitely something to be worked on in the near future, as this issue becomes more and more severe with a growing database.
Another topic would be performance tests in general. I think it would be helpful to have a suite of tests to gauge performance regularly...

**Comment by sruffell** [comment]
This is just a heads up that I've started looking into this on the following WIP branch:
https://github.com/sruffell/timewarrior/commits/wip-investigate-performance

On that branch is a test database, db.tar.gz in the root, that contains 20K entries I was using for testing, and just eliminating the load of the entire database in intervalSummarize, sruffell/timewarrior@45bba869d7889  (called after each command), results in a noticeable increase in speed.

Here are two command using 1.2.0, you can see that just running `src/timew` takes almost a second.
```
$ rm -fr db
$ tar xvfz db.tar.gz
$ export TIMEWARRIORDB=$(pwd)/db
$ time src/timew
Tracking t1
  Started 2019-11-26T17:25:36
  Current      12-02T10:26:08
  Total             137:00:32

real    0m0.966s
user    0m0.953s
sys     0m0.013s
$ time src/timew start shaun1
Recorded t1
  Started 2019-11-26T17:25:36
  Ended        12-02T10:26:19
  Total             137:00:43
Note: 'shaun1' is a new tag.
Tracking shaun1
  Started 2019-12-02T10:26:20
  Current                  22
  Total               0:00:02

real    0m3.613s
user    0m3.589s
sys     0m0.022s
```

Here is the same sequence of commands but with the database I'm using, which saves a second in both cases.
```
$ rm -fr db
$ tar xvfz db.tar.gz
$ export TIMEWARRIORDB=$(pwd)/db
$ time src/timew
Tracking t1
  Started 2019-11-26T17:25:36
  Current      12-02T10:30:39
  Total             137:05:03

real    0m0.099s
user    0m0.083s
sys     0m0.016s
$ time src/timew start shaun1
Recorded t1
  Started 2019-11-26T17:25:36
  Ended        12-02T10:30:44
  Total             137:05:08
Note: 'shaun1' is a new tag.
Tracking shaun1
  Started 2019-12-02T10:30:45
  Current                  46
  Total               0:00:01

real    0m1.868s
user    0m1.832s
sys     0m0.034s
```

I've started modifying getTracked in src/data.cpp as well but those changes do not yet pass all the tests but hopefully I can get those tests passing in the next week or so.

One question I had for @lauft is whether templates are to be explicitly avoided.  I do not see any templates defined in the code base so I was avoiding them, but I think it would allow me to get rid of some boilerplate.

**Comment by sruffell** [comment]
OI've pushed an update to my wip-investigate-performance branch that passes all the tests and does not experience the same large slowdowns here: sruffell/timewarrior@4120489db2ece879

I can clean it up and submit a pull request if interested.

**Comment by lauft** [comment]
@sruffell I have written a small script to do some performance testing and got the following results:

![timew-performance-d4155007](https://user-images.githubusercontent.com/8539295/70087256-3efac400-1614-11ea-9081-bcde9c752e59.png)

My plan is to convert this into a small performance test suite that can be used to assess Timewarrior. 

Looking at your commits it seems like we both had the same ideas and identified the same culprits. :) So I am interested in how the tests turn out with your contribution.

There is no general ban on templates in this project, but I consider them equally as powerful and dangerous. So I would use them only if there is a good cause for it and if they do not obfuscate the code.

**Comment by sruffell** [comment]
> I have written a small script to do some performance testing...
> My plan is to convert this into a small performance test suite that can be used to assess Timewarrior.

Nice! That will be helpful.

Speaking of performance, I originally started looking at #244 and there was a huge increase in speed when when reading in the entire database. When I profiled 1.2.0 with callgrind, by far the most time was spent parsing the datetimes from the text files. When I stored the inclusions in sqlite, I stored times in the database as binary unix time and eliminated most of that parsing (and also eliminated problems with escaping JSON strings in tags and annotations). But I thought I should follow up on this issue first so that performance didn't factor into any discussion about an embedded database.

>Looking at your commits it seems like we both had the same ideas and identified the same culprits. :) So I am interested in how the tests turn out with your contribution.

Thanks. I'll fix up the commits into a proper pull request.

>There is no general ban on templates in this project, but I consider them equally as powerful and dangerous. So I would use them only if there is a good cause for it and if they do not obfuscate the code.

Thanks for the info here as well. I believe that I can write one template for the Database::iterator / Database::reverse_iterator that will eliminate most of the code duplication in the implementation of those two classes. I'll make that change in the pull request.

Thanks again.

**Comment by lauft** [comment]
@sruffell I have pushed my performance test scripts with 2f6d12f. 
Within `test` you find `performance-test.sh` and `performance-plot.py`, which you can call like
```
./performance-test.sh output-dir  # = /tmp/timew-performance if not given
./performance-plot.py output-dir  # Parameter output-dir is mandatory here!
```
The test may be crude, but they already show the big time consumers. Let's see how they evolve...

> Speaking of performance, I originally started looking at #244 and there was a huge increase in speed when when reading in the entire database. When I profiled 1.2.0 with callgrind, by far the most time was spent parsing the datetimes from the text files. When I stored the inclusions in sqlite, I stored times in the database as binary unix time and eliminated most of that parsing (and also eliminated problems with escaping JSON strings in tags and annotations). But I thought I should follow up on this issue first so that performance didn't factor into any discussion about an embedded database.

I agree that we should keep the performance issue separated from the backend discussion. :)

**Comment by sruffell** [comment]
While I've not yet cleaned up the branch, I rebased on the upstream dev branch so I can run your tests.

On my machine, this is what I got against GothenburgBitFactory/timewarrior@2f6d12fc9ec72f6e4c8d04 :
![before](https://user-images.githubusercontent.com/87230/70337908-8c905000-1811-11ea-97e0-8130abf6bc0e.png)

And this is what I get against sruffell/timewarrior@09db150ee5bce30f2 : 
![after](https://user-images.githubusercontent.com/87230/70337927-931ec780-1811-11ea-91e4-4bb3500270ad.png)

I should be able to issue the pull request this weekend.

**Comment by lauft** [comment]
@sruffell any updates?

**Comment by sruffell** [comment]
I started looking into why release mode on macOS is segfaulting yesterday, but it is still inconclusive.

My best theory right now is that clang, when building for release, didn’t quite like the const_cast I had in allLines (even though the Datafile itself is not const). I am not sure why this is.

I’m currently reworking the patch set to remove the const_cast which I should have done tomorrow and can then issue the merge request.

**Comment by sruffell** [comment]
Just following up on this issue that the pull request #269 should be ready for review. 

Just a note that I know the `timew gaps` command does still load the entire database unnecessarily. It has the last call to "getAllInclusions" as part the getUntracked function call.

**Comment by sruffell** [comment]
I've removed the getAllInclusions on the branch (which improved the performance of the `timew gaps` command since that command needed to be changed in order to not require it).

When I went back to run the performance test, I looked at the current tests that do not complete in 0.00 seconds with 2000 entries in the database as seen below:

```
$ cd /tmp/timew-performance/
$ (for file in $(ls) ; do REAL=$(tail -n 1 $file | cut -f 3); if [ "$REAL" != "0.00" ] ; then echo -e "$file:\t$REAL"; fi; done) | sort -k2 -n -r
timew-untag-performance.log:    0.07
timew-tag-performance.log:      0.07
timew-split-performance.log:    0.07
timew-shorten-performance.log:  0.07
timew-resize-performance.log:   0.07
timew-move-performance.log:     0.07
timew-modify-start-performance.log:     0.07
timew-modify-end-performance.log:       0.07
timew-lengthen-performance.log: 0.07
timew-join-performance.log:     0.07
timew-delete-performance.log:   0.07
timew-continue-performance.log: 0.07
timew-annotate-performance.log: 0.07
```

These commands use `getTracked` along with an empty filter which is the equivalent of using getAllInclusions. So while this branch is still represents a nice performance improvement for many of the commands (below you can see the same output as above but against the the current dev branch), I'll keep working on the commands from the tests above to eliminate the parsing of the entire database into Intervals.

```
$ cd /tmp/timew-performance/
$ (for file in $(ls) ; do REAL=$(tail -n 1 $file | cut -f 3); if [ "$REAL" != "0.00" ] ; then echo -e "$file:\t$REAL"; fi; done) | sort -k2 -n -r
timew-continue-performance.log: 0.23
timew-split-performance.log:    0.22
timew-track-performance.log:    0.15
timew-shorten-performance.log:  0.15
timew-resize-performance.log:   0.15
timew-move-performance.log:     0.15
timew-modify-start-performance.log:     0.15
timew-modify-end-performance.log:       0.15
timew-lengthen-performance.log: 0.15
timew-join-performance.log:     0.15
timew-start-performance.log:    0.14
timew-month-performance.log:    0.08
timew-export-performance.log:   0.08
timew-week-performance.log:     0.07
timew-untag-performance.log:    0.07
timew-tags-performance.log:     0.07
timew-tag-performance.log:      0.07
timew-summary-performance.log:  0.07
timew-stop-performance.log:     0.07
timew-gaps-performance.log:     0.07
timew-delete-performance.log:   0.07
timew-day-performance.log:      0.07
timew-annotate-performance.log: 0.07

```

**Comment by sruffell** [comment]
I finished the other commands. The performance plot is showing flat lines for the tests when run against sruffell/timewarrior@0a4c629 :

![Figure_1](https://user-images.githubusercontent.com/87230/71794250-409a1c00-3006-11ea-894f-98cc2cc44460.png)
