### ISSUE TITLE
Holidays feature isn't working anymore as there are no files for 2019+

### ISSUE THREAD

**Issue by bioxz** [GothenburgBitFactory/timewarrior#246]
The feature to integrate holidays in timewarrior (timewarrior/doc/holidays/, documented at https://timewarrior.net/docs/holidays.html) isn't working anymore as the remote source for the holiday data wasn't updated since 2018.

**Comment by lauft** [comment]
At least the data for locale de-DE has been updated for 2019/2020 (see https://github.com/GothenburgBitFactory/holidata.net/commit/861bd900520409ee9307b901f039b9ca7e9e14b5 and https://github.com/GothenburgBitFactory/holidata.net/commit/3ff136a22c9970529be6cdc3f875bfeb7ab4e863). Other locales will follow...

**Comment by lauft** [comment]
The locales for `da-DK`, `de-AT`, `de-BE`, `de-CH`, `de-DE`, `en-GB`, `en-NZ`, `en-US`, `es-ES`, `es-US`, `fr-BE`, `nb-NO`, `nl-BE`, `nl-NL`, `ru-RU` have been updated for 2019 and 2020 for formats CSV and JSON.
If you require a different format or locale, please open an issue in the [holidata project](https://github.com/GothenburgBitFactory/holidata/issues) to get the migration of the locale prioritized.
