### ISSUE TITLE
Timewarrior Database Correction Script fails exporting the database

### ISSUE THREAD

**Issue by JonasDralle** [GothenburgBitFactory/timewarrior#249]
Hi. The current version of the [timew-dbcorrection.py](https://github.com/GothenburgBitFactory/timewarrior/files/3600911/timew-dbcorrection-current-version.zip) Script for fixing #106 halts at the exporting step.

I just upgraded from Version 1.0.0 to 1.1.1 and I get the following Python Traceback caused by json serialization:
<details>
<summary>ValueError: Expecting ',' delimiter: line 48 column 75 (char 4870)</summary>
	> python timew-dbcorrection.py

	TIMEWARRIOR DATABASE CORRECTION SCRIPT

	Use this script when you have used
	 - TimeWarrior earlier than version 1.1.1
	 - Exclusions

	If none of the above applies, you probably do not need to run this script.

	The script will only correct the database for ONE set of exclusions. If you
	have changed your exclusions

	This script will export your stored intervals, purge your database and re-enter
	your data such that exclusions will be applied and written properly to the
	database.

	For further information on this see
	https://timewarrior.net/docs/dbcorrection.html

	!!! YOU ARE STRONGLY ADVISED TO BACKUP YOUR DATABASE BEFORE PROCEEDING !!!

	Proceed? [y/N] y
	Gathering information...
	TimeWarrior binary: 'timew'
	TimeWarrior version: '1.1.1'
	Database path: '/home/user01/.timewarrior'
	(you can change this by setting environment variable TIMEWARRIORDB)
	Found files: 2019-07.data, 2019-08.data, 2019-09.data, undo.data

	The script will now extract your data, purge your database, and re-enter your intervals.
	Proceed? [y/N] y
	Exporting database...
	Traceback (most recent call last):
	  File "timew-dbcorrection.py", line 101, in <module>
		intervals = json.loads(subprocess.check_output([timew_binary, "export"]).decode("UTF-8").strip())
	  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
		return _default_decoder.decode(s)
	  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
		obj, end = self.raw_decode(s, idx=_w(s, 0).end())
	  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
		obj, end = self.scan_once(s, idx)
	ValueError: Expecting ',' delimiter: line 48 column 75 (char 4870)
</details>

Installed Python Version is 2.7.16.

<details>
<summary>TimeWarrior Diagnostics</summary>
	timew 1.1.1
		   Platform: Linux

	Compiler:
			Version: 7.3.0
			   Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
		 Compliance: C++11

	Build Features
			  Built: May  6 2018 14:55:39
			  CMake: 3.11.1
		 Build type: None

	Configuration
	  TIMEWARRIORDB: -
				Cfg: /home/user01/.timewarrior/timewarrior.cfg (-rw- 256 bytes)
		   Database: /home/user01/.timewarrior (drwx 512 bytes)
		Color theme: Built-in default
					 00 01 02 03 04 05 06 07 08 09 10 11 12

	Extensions
		   Location: /home/user01/.timewarrior/extensions (drwx 512 bytes)
				   (None)
</details>

Hope this helps.
I can provide additional data if required.

**Comment by lauft** [comment]
The underlying error has been fixed with fac5d6a

An updated version of the timew-dbcorrection.py Script can be found [here](https://github.com/lauft/timew-dbcorrectionscript). With the new version you can now inject the corrected data via the environment-variable `TIMEW_EXPORT_DATA`:
```
$ TIMEW_EXPORT_DATA=path/to/data.json python timew-dbcorrection.py
```
