### ISSUE TITLE
timew track time offset/timezone confusion?

### ISSUE THREAD

**Issue by chron-isch** [GothenburgBitFactory/timewarrior#252]
Maybe I'm just missing something, but I've read the manpage and the documentation and can't find anything about timezones or how track can make changes to entered times.

When you use `timew track` times unexpectetly change.

Example, from 08:00 to 09:00
```
# timew track 2019-09-01T08:00:00Z to 2019-09-01T09:00:00Z Test
Recorded Test
  Started 2019-09-01T10:00:00
  Ended              11:00:00
  Total               1:00:00
```
Turns into 10:00 to 11:00
```
 # timew summary 2019-09-01 - 2019-09-02 :ids
Wk  Date       Day ID  Tags    Start      End    Time   Total
W35 2019-09-01 Sun @10 Test 10:00:00 11:00:00 1:00:00 1:00:00
                                                             
                                                      1:00:00
```
```
 # timedatectl                                                                                       [17:31:03]
               Local time: Di 2019-09-17 17:31:03 CEST
           Universal time: Di 2019-09-17 15:31:03 UTC
                 RTC time: Di 2019-09-17 15:31:03
                Time zone: Europe/Berlin (CEST, +0200)
System clock synchronized: yes
              NTP service: inactive
          RTC in local TZ: no
```
Considering it's offset by 2 hours and I live in CEST+2 I'm guessing it's related to timezones, but I'm not sure how since it's backwards (+2h instead of -2 for UTC) and timew start/stop doesn't behave the same way.

**Comment by lauft** [comment]
You enter your times as UTC (note the "Z" at the end), but `timew summary` displays local time.

Drop the "Z" and you get the desired result:
```
$ timew track 2019-09-01T08:00:00 to 2019-09-01T09:00:00 Test
Note: 'Test' is a new tag.
Recorded Test
  Started 2019-09-01T08:00:00
  Ended              09:00:00
  Total               1:00:00

$ timew summary 2019-09-01 - 2019-09-02 :ids

Wk  Date       Day ID Tags   Start     End    Time   Total
W35 2019-09-01 Sun @1 Test 8:00:00 9:00:00 1:00:00 1:00:00
                                                          
                                                   1:00:00
```

**Comment by chron-isch** [comment]
Thanks, I kind of feel a little embarassed now. :)

Now that I know that, I managed to find it in the manpage as well, but 'UTC' an 'TZ' are only mentioned twice each and 'timezone' or 'localtime' not at all, maybe that section should be a little expanded?

Anyway thanks for the help.

**Comment by lauft** [comment]
> Now that I know that, I managed to find it in the manpage as well, but 'UTC' an 'TZ' are only mentioned twice each and 'timezone' or 'localtime' not at all, maybe that section should be a little expanded?

That is definitively a good thing. Can you tell me the man pages where you found the references and/or better, tell me where you expected to find the relevant information?

Thanks

**Comment by chron-isch** [comment]
`man 1 timew`, it's mentioned in the DATES section. It absolutly makes sense to put it there but I missed it because I was just searching for 'timezone' not 'UTC' or 'TZ'.

Maybe just an additional sentence like "Appending 'Z' to time(-format) detones the use of UTC instead of the local timezone" or something at the top of that section?
```
DATES
       Timewarrior supports the following date formats based on ISO-8601:

         <extended-date> [T <extended-time>]   Extended date, optional extended time
         <date> [T <time>]                     Date, optional time
         <extended-time>                       Extended time
         <time>                                Time

         extended-date:
           YYYY-MM-DD                          Year, month, day
           YYYY-MM                             Year, month, 1st
           YYYY-DDD                            Year, Julian day 001-366
           YYYY-WwwD                           Year, week number, day number
           YYYY-Www                            Year, week number, day 1

         extended-time:
           hh:mm[:ss]Z                         Hours, minutes, optional seconds, UTC
           hh:mm[:ss][+/-hh:mm]                Hours, minutes, optional seconds, TZ

         date:
           YYYYMMDD                            Year, month, day
           YYYYWww                             Year, week number, day number
           YYYYDDD                             Year, Julian day 001-366

         time:
           hhmm[ss]Z                           Hour, minutes, optional seconds, UTC
           hhmm[ss][+/-hh[mm]]                 Hour, minutes, optional seconds, TZ
```
