### ISSUE TITLE
Cannot affect IDs from last quarter.

### ISSUE THREAD

**Issue by Andonome** [GothenburgBitFactory/timewarrior#256]
I've found a 12 hour timeslot - looks like I fell asleep. It's ID 72.  But when I do:

> timew shorten @72 12h

I just get this:

"ID '@72' does not correspond to any tracking."

All in all, I can't change anything from last quarter (1 hour ago), without manually editing the data.

**Comment by lauft** [comment]
Is this timeslot at a special date (1st/last day of month)? Does it span over two days or is it contained within a single day?

What exactly do you mean by "I can't change anything from last quarter (1 hour ago)"?

What commands did you try and what is the error output?

**Comment by Andonome** [comment]
This problem was solved by the dbcorretions python script.

https://timewarrior.net/docs/dbcorrection.html

> Is this timeslot at a special date (1st/last day of month)? Does it span over two days or is it contained within a single day?

It was contained within a single day.  All items from before October could not be affected, only viewed.

The error was:

"ID '@72' does not correspond to any tracking."

This occurred with all such items.

Anyway - seems all good now.  The documentation states the script is meant for exclusions and earlier versions of timewarrior, neither of which I use.  But it worked fine.
