### ISSUE TITLE
make error FS.cpp on freebsd 12.1

### ISSUE THREAD

**Issue by choppy812** [GothenburgBitFactory/timewarrior#258]
Trying to build either dev or 1.2.0, there is a make failure with FS.cpp.

FreeBSD version: 
FreeBSD  mymachine.local 12.1-RELEASE FreeBSD 12.1-RELEASE r354233 GENERIC  amd64

timew version: 
n/a at the moment, won't make. trying 1.2.0 currently, but same with dev branch.

python version:
Python 3.6.9

Scanning dependencies of target libshared
make -f src/CMakeFiles/libshared.dir/build.make src/CMakeFiles/libshared.dir/build
[ 30%] Building CXX object src/CMakeFiles/libshared.dir/libshared/src/Args.cpp.o
cd /home/user/gh/timewarrior/src && /usr/bin/c++   -I/home/user/gh/timewarrior -I/home/user/gh/timewarrior/src -I/home/user/gh/timewarrior/src/commands -I/home/user/gh/timewarrior/src/libshared/src -Wall -Wextra -Wsign-compare -Wreturn-type -std=c++11  -g -o CMakeFiles/libshared.dir/libshared/src/Args.cpp.o -c /home/user/gh/timewarrior/src/libshared/src/Args.cpp
[ 32%] Building CXX object src/CMakeFiles/libshared.dir/libshared/src/Color.cpp.o
cd /home/user/gh/timewarrior/src && /usr/bin/c++   -I/home/user/gh/timewarrior -I/home/user/gh/timewarrior/src -I/home/user/gh/timewarrior/src/commands -I/home/user/gh/timewarrior/src/libshared/src -Wall -Wextra -Wsign-compare -Wreturn-type -std=c++11  -g -o CMakeFiles/libshared.dir/libshared/src/Color.cpp.o -c /home/user/gh/timewarrior/src/libshared/src/Color.cpp
[ 33%] Building CXX object src/CMakeFiles/libshared.dir/libshared/src/Composite.cpp.o
cd /home/user/gh/timewarrior/src && /usr/bin/c++   -I/home/user/gh/timewarrior -I/home/user/gh/timewarrior/src -I/home/user/gh/timewarrior/src/commands -I/home/user/gh/timewarrior/src/libshared/src -Wall -Wextra -Wsign-compare -Wreturn-type -std=c++11  -g -o CMakeFiles/libshared.dir/libshared/src/Composite.cpp.o -c /home/user/gh/timewarrior/src/libshared/src/Composite.cpp
[ 34%] Building CXX object src/CMakeFiles/libshared.dir/libshared/src/Configuration.cpp.o
cd /home/user/gh/timewarrior/src && /usr/bin/c++   -I/home/user/gh/timewarrior -I/home/user/gh/timewarrior/src -I/home/user/gh/timewarrior/src/commands -I/home/user/gh/timewarrior/src/libshared/src -Wall -Wextra -Wsign-compare -Wreturn-type -std=c++11  -g -o CMakeFiles/libshared.dir/libshared/src/Configuration.cpp.o -c /home/user/gh/timewarrior/src/libshared/src/Configuration.cpp
[ 35%] Building CXX object src/CMakeFiles/libshared.dir/libshared/src/Datetime.cpp.o
cd /home/user/gh/timewarrior/src && /usr/bin/c++   -I/home/user/gh/timewarrior -I/home/user/gh/timewarrior/src -I/home/user/gh/timewarrior/src/commands -I/home/user/gh/timewarrior/src/libshared/src -Wall -Wextra -Wsign-compare -Wreturn-type -std=c++11  -g -o CMakeFiles/libshared.dir/libshared/src/Datetime.cpp.o -c /home/user/gh/timewarrior/src/libshared/src/Datetime.cpp
[ 37%] Building CXX object src/CMakeFiles/libshared.dir/libshared/src/Duration.cpp.o
cd /home/user/gh/timewarrior/src && /usr/bin/c++   -I/home/user/gh/timewarrior -I/home/user/gh/timewarrior/src -I/home/user/gh/timewarrior/src/commands -I/home/user/gh/timewarrior/src/libshared/src -Wall -Wextra -Wsign-compare -Wreturn-type -std=c++11  -g -o CMakeFiles/libshared.dir/libshared/src/Duration.cpp.o -c /home/user/gh/timewarrior/src/libshared/src/Duration.cpp
[ 38%] Building CXX object src/CMakeFiles/libshared.dir/libshared/src/FS.cpp.o
cd /home/user/gh/timewarrior/src && /usr/bin/c++   -I/home/user/gh/timewarrior -I/home/user/gh/timewarrior/src -I/home/user/gh/timewarrior/src/commands -I/home/user/gh/timewarrior/src/libshared/src -Wall -Wextra -Wsign-compare -Wreturn-type -std=c++11  -g -o CMakeFiles/libshared.dir/libshared/src/FS.cpp.o -c /home/user/gh/timewarrior/src/libshared/src/FS.cpp
/home/user/gh/timewarrior/src/libshared/src/FS.cpp:481:14: error: expected value in expression
#elif FREEBSD
             ^
/home/user/gh/timewarrior/src/libshared/src/FS.cpp:486:61: warning: missing field 'l_sysid'
      initializer [-Wmissing-field-initializers]
    struct flock fl = {F_WRLCK, SEEK_SET, 0,       0,     0 };
                                                            ^
/home/user/gh/timewarrior/src/libshared/src/FS.cpp:504:14: error: expected value in expression
#elif FREEBSD
             ^
/home/user/gh/timewarrior/src/libshared/src/FS.cpp:509:61: warning: missing field 'l_sysid'
      initializer [-Wmissing-field-initializers]
    struct flock fl = {F_WRLCK, SEEK_SET, 0,       0,     0 };
                                                            ^
2 warnings and 2 errors generated.
*** Error code 1

Stop.
make[2]: stopped in /usr/home/user/gh/timewarrior
*** Error code 1

Stop.
make[1]: stopped in /usr/home/user/gh/timewarrior
*** Error code 1

Stop.
make: stopped in /usr/home/user/gh/timewarrior

**Comment by lauft** [comment]
This seems to be an issue with libshared.

**Comment by lauft** [comment]
Did you succeed to compile an earlier version of Timewarrior?

**Comment by choppy812** [comment]
Thank you for your question. For my work, I really need to use both tags and annotations, which the earlier version doesn't support. I need to list multi-level 'cost centers' which I do with tags like 'b.a.net' (b is company, a is admin, net is network), then I also need to record the activity in an annotation, like "b.a.net" "review logs" and "b.a.net" "install application". The reason I can't do this all in the tag is I depend on totals.py to list summaries of total time for a cost center tag. If the tags are different, it includes a new total for each unique tag, making the totals incorrect. So, my solution is to wait for a new release that supports annotations and find other time tracking software for the moment.

**Comment by lauft** [comment]
If you could compile an earlier version of timewarrior, this would give us a "good" commit of libshared. With `git bisect` one could then determine the commit in between, which introduced the breaking change.

**Comment by lauft** [comment]
Currently I do not have a freebsd installation at hand, so I cannot test/analyze this. If someone could checkout libshared and find and fix the problem that would be great.

**Comment by choppy812** [comment]
attempting to compile 1.1.1 

~/gh/timewarrior(1.1.1) » cmake -DCMAKE_BUILD_TYPE=release
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- Configuring C++11
-- System: FreeBSD
-- Looking for SHA1 references
-- Found SHA1 reference: f5fbdc8
-- Configuring cmake.h
-- Configuring documentation
-- Configuring holiday documentation
-- Configuring theme documentation
-- Configuring extensions
CMake Deprecation Warning at test/CMakeLists.txt:6 (cmake_policy):
  The OLD behavior for policy CMP0037 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Configuring done
CMake Error at src/CMakeLists.txt:46 (add_library):
  Cannot find source file:

    libshared/src/Args.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at src/CMakeLists.txt:46 (add_library):
  No SOURCES given to target: libshared


CMake Generate step failed.  Build files cannot be regenerated correctly.
------------------------------------------------------------------

**Comment by silent-at-gh** [comment]
Here is the fix for original issue (fixes compilation of versions 1.2.0 and 1.3.0 on FreeBSD12.1). 
```
[silent@beastie][/tmp/timew/timewarrior.git/src/libshared]uname -a
FreeBSD beastie.intra 12.1-RELEASE-p1 FreeBSD 12.1-RELEASE-p1 r355272 GENERIC  amd64
[silent@beastie][/tmp/timew/timewarrior.git/src/libshared]git diff
diff --git a/src/FS.cpp b/src/FS.cpp
index c152654..fb8235e 100644
--- a/src/FS.cpp
+++ b/src/FS.cpp
@@ -475,10 +475,10 @@ bool File::lock ()
   _locked = false;
   if (_fh && _h != -1)
   {
-#ifdef DARWIN
+#if defined(DARWIN)
                     // l_start l_len l_pid l_type   l_whence
     struct flock fl = {0,      0,    0,    F_WRLCK, SEEK_SET};
-#elif FREEBSD
+#elif defined(FREEBSD)
                     // l_type   l_whence  l_start  l_len  l_pid  l_sysid
     struct flock fl = {F_WRLCK, SEEK_SET, 0,       0,     0,     0 };
 #else
@@ -498,10 +498,10 @@ void File::unlock ()
 {
   if (_locked)
   {
-#ifdef DARWIN
+#if defined(DARWIN)
                     // l_start l_len l_pid l_type   l_whence
     struct flock fl = {0,      0,    0,    F_WRLCK, SEEK_SET};
-#elif FREEBSD
+#elif defined(FREEBSD)
                     // l_type   l_whence  l_start  l_len  l_pid  l_sysid
     struct flock fl = {F_WRLCK, SEEK_SET, 0,       0,     0,     0 };
 #else
```

**Comment by kbcb** [comment]
Above Patch works for timew v. 1.2.0 on FreeBSD 12.1 but not for timew v. 1.3.0 because there is another error coming up in CmdHelp.cpp:

`
[ 75%] Building CXX object src/commands/CMakeFiles/commands.dir/CmdHelp.cpp.o
/home/user/timew-1.3.0/src/commands/CmdHelp.cpp:123:13: error: use of undeclared identifier 'WIFEXITED'
    return (WIFEXITED (ret)) ? WEXITSTATUS (ret) : -1;
            ^
/home/user/timew-1.3.0/src/commands/CmdHelp.cpp:123:32: error: use of undeclared identifier 'WEXITSTATUS'
    return (WIFEXITED (ret)) ? WEXITSTATUS (ret) : -1;
                               ^
2 errors generated.
*** Error code 1
`

**Comment by sruffell** [comment]
I do not have a FreeBSD system setup, so I cannot verify. But does the following change resolve it for you?

```diff
diff --git a/src/commands/CmdHelp.cpp b/src/commands/CmdHelp.cpp
index 5da034b1..4ea79780 100644
--- a/src/commands/CmdHelp.cpp
+++ b/src/commands/CmdHelp.cpp
@@ -24,6 +24,9 @@
 //
 ////////////////////////////////////////////////////////////////////////////////

+#include <sys/types.h>
+#include <sys/wait.h>
+
 #include <commands.h>
 #include <algorithm>
 #include <iostream>
```

**Comment by kbcb** [comment]
Yes, thank you. It builds and installs on FreeBSD 12.1-RELEASE-p7. 

Could you make sure that your patch (and the previous) makes it into the HEAD-branch? That would make porting so much easier.  ;-)

Thanks again.

**Comment by lauft** [comment]
PR #362 merged, should be fixed.

**Comment by sruffell** [comment]
@lauft, I still think there is the problem in libshared FS.cpp.

If @pbeckingham is tied up, I wonder if there is someone else who could step up and merge some of the less controversial changes to libshared?
