### ISSUE TITLE
Migrate to python 3

### ISSUE THREAD

**Issue by lauft** [GothenburgBitFactory/timewarrior#259]
With python 2 reaching its end of life (see https://pythonclock.org/), it is time to move on...
Most/all python files should run with python 3 already but now it should be made explicit.

**Comment by lauft** [comment]
ToDos:
* Migrate tests to python 3 (-> adapt setup for docker containers!)
* Migrate hook scripts to python 3 (-> extract to separate repository?)

**Comment by lauft** [comment]
Current status:
Done:
* test suite migrated to python3
* Travis runs all tests on python3
To do:
* Migrate hook script `on-modify.timewarrior` to python 3
* Migrate reports to python 3

**Comment by sruffell** [comment]
@lauft Just a note that `test/problems` has not yet been switched.
