### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by sorsasampo** [GothenburgBitFactory/timewarrior#263]
The [1.2.0 milestone](https://github.com/GothenburgBitFactory/timewarrior/milestone/3) does not contain any open issues. Is anything preventing a release?

On a related note, can the nix release be updated as well, or is it maintained by a third party?

**Comment by sruffell** [comment]
What are the differences between the "vX.X.X" and "sX.X.X" tags?

I had always thought that 1.2.0 was already released since [s1.2.0](https://github.com/GothenburgBitFactory/timewarrior/releases/tag/s1.2.0) is already tagged.

**Comment by lauft** [comment]
> The 1.2.0 milestone does not contain any open issues. Is anything preventing a release?

In short: housekeeping 🙂 The release is now published.

> On a related note, can the nix release be updated as well, or is it maintained by a third party?

If you mean the packages for Timewarrior, for those the respective maintainers are in charge.

**Comment by lauft** [comment]
> I had always thought that 1.2.0 was already released since s1.2.0 is already tagged.

Sorry about that. I really need to clean up the old tags... 😉
