### ISSUE TITLE
How to view annotations

### ISSUE THREAD

**Issue by harryleesan** [GothenburgBitFactory/timewarrior#266]
In the docs [timew-annotate](https://timewarrior.net/docs/timew-annotate.1.html), it only explained how to create annotations but does not explain how to view it.

Currently, it seems like using the summary report is the only way:
`timew summary :annotations :yesterday`

However, the annotation doesn't wrap and we cannot view the full annotation (#205)

How are annotations meant to be viewed?

**Comment by sruffell** [comment]
I am not sure if this is how they are meant to be used, but when I want to look at any annotations I use `timew export`

They are also available in the input for any custom reports you may write (I just do not use the annotations in the report I normally use).

**Comment by harryleesan** [comment]
Thanks for pointing me in the `export` direction and writing a custom report. I will give it a shot.

**Comment by lauft** [comment]
> How are annotations meant to be viewed?

Currently annotations are only fully available via `export` or `report`. Further support to manage annotations will be added with future releases.

**Comment by nodens** [comment]
Hi,

I had the same issue and arrived to the same conclusion on my own after checking the code (use custom report or export), but I would have liked to see this discussion when I looked at the open issues - or the same information in timew-annotate manpage ;)

How about leaving this open as "enhancement" so people like me find it faster?

Thanks!

**Comment by ahillio** [comment]
Timew-report now lets you get annotations `pip install git+https://github.com/lauft/timew-report.git@f8d6cf4c60228a84217e1e5de640c79d8cae0973` so in your custom reports you can invoke `interal.get_annotation()`.

**Comment by xerus2000** [comment]
Please reopen this issue until that is fixed. I was about to open an issue for this as well.

I think it would also be a good idea to mention [on the website](https://timewarrior.net/docs/timew-annotate.1.html) that you currently need to use `report` or `export` to view them.

**Comment by Spreadcat** [comment]
same problem here. The website does not seem to state how to view annotations. This I only found when looking through the closed issues in the issue tracker. There's IMHO some room for improvement here to just update the docs with a sentence or two.

**Comment by sskras** [comment]
Yep, I didn't find the explanation on the docs page, so I started googling and found this.
It would be nice to fix the docs.

**Comment by lauft** [comment]
I have updated the man page for the annotation command.

**Comment by Spreadcat** [comment]
Went down the rabbit hole to found the change in the commit log. Guess that change will do as it adds the required information at the relevant point in the documentation. It still feels a bit obfuscated, but I can't come up with better way than adding it to the documentation at this point. Therefore: thumbsup
