### ISSUE TITLE
Minimum required gcc version to build timewarrior

### ISSUE THREAD

**Issue by Tronde** [GothenburgBitFactory/timewarrior#268]
Hi,  
The following pages say that you need gcc >= 4.7 to build timewarrior:

- https://timewarrior.net/docs/download.html

- https://github.com/GothenburgBitFactory/timewarrior

The [INSTALL](https://github.com/GothenburgBitFactory/timewarrior/blob/dev/INSTALL) file in every branch however say that gcc 4.9 is needed.

Because I was able to build timewarrior with gcc version 4.8 I would guess the version information in  [INSTALL](https://github.com/GothenburgBitFactory/timewarrior/blob/dev/INSTALL) is incorrect and should be fixed.

Best regards,  
Tronde

**Comment by lauft** [comment]
Thanks for pointing that out. The documentation should be at least consistent.
