### ISSUE TITLE
Stdout meta information as JSON or consumable output

### ISSUE THREAD

**Issue by makepanic** [GothenburgBitFactory/timewarrior#271]
Hi, thanks for building this great tool.

I'm currently in the progress of migrating away from https://github.com/projecthamster/ to timewarrior.
Everything worked fine so far, when importing existing time entries.

I'm also wrote myself a small [rofi](https://github.com/davatorium/rofi) script to allow quick control over task tracking.
With `hamster`, I could easily query things like `tags` as a newline separated list in its stdout.

It seems like timewarrior supports similar query options but always outputs to an ASCII table. 

Is it possible to get the output of `timew tags` and others as JSON or something that is easily consumable by other environments?

**Comment by lauft** [comment]
Currently only `timew export` produces JSON output. There is a feature request for a DOM-query for tags (#188) which is more the low-level plumbing command you require

**Comment by lauft** [comment]
@makepanic A small update: The upcoming release of Timewarrior now has DOM querys for tags (#188). So you can do
```
timew get dom.tracked.tags [range] [tag...]
```
to get all tags from all intervals within the specified `range` filtered by the given `tag...`.
