### ISSUE TITLE
SHA256 Checksum on Website is not correct

### ISSUE THREAD

**Issue by Jaffex** [GothenburgBitFactory/timewarrior#276]
Hello guys,

unfortunately the checksum on the website does not fit for Version 1.2.0.
On the website (https://timewarrior.net), directly below the Download Link, the SHA256-Checksum stated is:
ff231424acff0ba156b720120b7eeeff961473c37f0f16d1e9dceeb7f0b91d7c

However, when I download and try to verify the Checksum, I get the following:
2c4d153105a32536ae328038246ebd846a5abd96df7ed29c11100866eaed8e3c

That has kept me from updating so far. Hope it's okay to post this here, but I got no response via mail.

Maybe you can look into it?

**Comment by johanbove** [comment]
@lauft The checksum on the[ TimeWarrior site](https://github.com/GothenburgBitFactory/ti.net) is not correct. Can you please verify this? See https://github.com/GothenburgBitFactory/ti.net/commit/591839cc3f4aee4dc62475e14e7c4c716cb7230e

**Comment by lauft** [comment]
The checksum is not for the zip file, but for the unzipped tar.

**Comment by Jaffex** [comment]
Ah, okay thanks - I‘ll verify and if the sha256 matches, I‘ll upgrade.  
But I still think it’s a bit confusing, because for Version 1.1.1, the checksum is for the zipfile and not for the unzipped tar.  
Also, usually people unzip and untar in one command with `tar -xzf` and would usually not first unzip, then verify, and finally untar.

**Comment by lauft** [comment]
The checksum for `timew-1.1.1` mentioned on the website (`1f7d9a62e55fc5a3126433654ccb1fd7d2d135f06f05697f871897c9db77ccc9`)is also for the tar file:
```
1f7d9a62e55fc5a3126433654ccb1fd7d2d135f06f05697f871897c9db77ccc9  timew-1.1.1.tar
7cf63bd03c146536a651b5fe17214f6bb0759bede08fea8cecd74b9258afbae8  timew-1.1.1.tar.gz
```
I found the same for the sha1sum for the `1.1.0` and `1.0.0` release as well, which is why I adopted it  for `1.2.0`. 

I agree it's confusing, it confused me as well, but on the other hand I saw the pattern of the previous releases and carried on with it.

I'll ask the group whether there have been similar issues with the previous releases.

**Comment by Jaffex** [comment]
That's confusing to me, I just tried downloading timew-1.1.1.tar.gz and verifying the checksum and I get very different results from you:

```
sha256sum timew-1.1.1.tar ; sha256sum timew-1.1.1.tar.gz 
038651ef98e02043950ca0957b6d1f2e8d9a44ad23c86bd2faf596806659346c  timew-1.1.1.tar
1f7d9a62e55fc5a3126433654ccb1fd7d2d135f06f05697f871897c9db77ccc9  timew-1.1.1.tar.gz
```
Anyways so far I'm happy with being able to install 1.2.0.

**Comment by lauft** [comment]
With http://github/GothenburgBitFactory/ti.net/commit/847a4f7f the website should now display the correct checksum - for the tar.gz-file as expected:
```
2c4d153105a32536ae328038246ebd846a5abd96df7ed29c11100866eaed8e3c
```

The reason for my mistake was [this bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1470011), which leads to double-zipped files. 🤦‍♂ 
Sorry for the confusion...
