### ISSUE TITLE
Add :fortnight hint

### ISSUE THREAD

**Issue by quazgar** [GothenburgBitFactory/timewarrior#278]
A fortnight is two weeks, it is often convenient to see the last week in addition to the current one, e.g. to do `timew continue @...` with a task from last week.

**Comment by quazgar** [comment]
The merge request would allow commands like this:

```
timew summary :fortnight
```

**Comment by lauft** [comment]
Added in 13fb0ad8e3a265df8fc79f9171b214374d8f5be1
