### ISSUE TITLE
tags.data modification date updated when file is not modified

### ISSUE THREAD

**Issue by CNG** [GothenburgBitFactory/timewarrior#284]
Hello, I've noticed every time `timew` is run, tags.data is not only accessed but written, which updates the modification timestamp on the file even though the content was not modified. IMO the file should only be written to if the content is actually changing. Running the bare `timew` should be idempotent and cause no changes to the filesystem.

This can be particularly problematic if `timew` is being run frequently, such as by a system status bar, and if the file is under version control or being synced to cloud storage. tags.data is then constantly being reuploaded, and it makes the version history feature of Google Drive useless, for example, as the last 100 (the maximum) versions are all identical. This is especially insidious if, God forbid, you happen to have multiple systems running `timew` attempting to stay in sync. Granted this is not likely an advisable scenario, but it's interesting to know the tiny time discrepancy across my systems apparently confused my Google Drive sync so badly that it created dozens of copies of my data folder that all somehow ended up with 0 byte files. I have since disabled outputting my current time tracking status to my status bar, and started over, and haven't had a problem. I would, however, like to actually use my status bar to help me remember my status.

Here's a demonstration of the issue. I check the modification date of the tags.data file, run `timew` and check the date again. I would not expect the modification date to change, but it does.

```
$ stat /home/cgorichanaz/GDrive/Main/Tracking/time/data/tags.data
  File: /home/cgorichanaz/GDrive/Main/Tracking/time/data/tags.data
  Size: 1321            Blocks: 8          IO Block: 4096   regular file
Device: fe02h/65026d    Inode: 36702578    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/cgorichanaz)   Gid: ( 1002/cgorichanaz)
Access: 2020-02-05 21:58:31.011955127 -0800
Modify: 2020-02-05 21:58:30.991954904 -0800
Change: 2020-02-05 21:58:30.991954904 -0800
 Birth: 2020-02-05 16:32:40.445637145 -0800
#  21:58:33  0.013  ~
$ timew
There is no active time tracking.
#  21:58:39  0.014  ~  ↵ 1
$ stat /home/cgorichanaz/GDrive/Main/Tracking/time/data/tags.data
  File: /home/cgorichanaz/GDrive/Main/Tracking/time/data/tags.data
  Size: 1321            Blocks: 8          IO Block: 4096   regular file
Device: fe02h/65026d    Inode: 36702578    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/cgorichanaz)   Gid: ( 1002/cgorichanaz)
Access: 2020-02-05 21:58:41.062067311 -0800
Modify: 2020-02-05 21:58:41.015400124 -0800
Change: 2020-02-05 21:58:41.015400124 -0800
 Birth: 2020-02-05 16:32:40.445637145 -0800
```

When I run `strace timew`, it seems the tags.data file is read as read only at one point, and then after the program prints its final output, the tags.data file is opened again, this time in write only mode!

```
...
write(1, "There is no active time tracking"..., 34There is no active time tracking.
) = 34
openat(AT_FDCWD, "/home/cgorichanaz/GDrive/Main/Tracking/time/data/tags.data", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
writev(3, [{iov_base=NULL, iov_len=0}, {iov_base="{\"1:1\":{\"count\":1},\"CM-IM correc"..., iov_len=1321}], 2) = 1321
close(3)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

Here are my versions:
```
$ uname -r
5.4.15-arch1-1
#  22:01:17  0.008  ~
$ python --version
Python 3.8.1
#  22:01:23  0.010  ~
$ timew --version
1.2.0
```

**Comment by lauft** [comment]
@sruffell do your changes in #283 solve this?

**Comment by sruffell** [comment]
Yes, #283 does contain a fix for this.

The last commit in that series, sruffell/timewarrior@75de07375626, specifically addresses this issue.

**Comment by sruffell** [comment]
I went ahead and tagged this issue in that specific commit since it was still waiting to be merged.

**Comment by CNG** [comment]
Hey cool, how timely! Thanks a lot!
