### ISSUE TITLE
Pass record id to extensions

### ISSUE THREAD

**Issue by j6s** [GothenburgBitFactory/timewarrior#285]
Currently, extensions only receive start, end, tags and annotations through stdin. I am currently building a extension that sends certain entries to the tempo jira plugin (for work). As such I need to somehow track which entries have already been sent to tempo and which ones have not.

From my tests I have not yet found a way to get from a JSON line in an extension to the record in order to update it.

I am not 100% comfortable with C++ - but I will try to have a stab at implementing this since it sounds fairly straight forward.

**Comment by sruffell** [comment]
> Currently, extensions only receive start, end, tags and annotations through stdin. I am currently building a extension that sends certain entries to the tempo jira plugin (for work). As such I need to somehow track which entries have already been sent to tempo and which ones have not.

👍 on this change. I have a report that I use in which having the id in the exported data would save another call to `timew summary`.

However, based on your comment, since the ids are always changing, how can you use them to know what was sent to tempo as you add different intervals in timew?

**Comment by lauft** [comment]
> However, based on your comment, since the ids are always changing, how can you use them to know what was sent to tempo as you add different intervals in timew?

I second that concern. Ids in Timewarrior are only guaranteed to be valid until an interval is added/deleted/changed. As I am not familar with the tempo JIRA plugin, can you elaborate a bit more on your usecase? Why do you need to know which intervals have been sent? How would your id then be used in tempo/JIRA?

**Comment by j6s** [comment]
When sending a time span to tempo, they will return a uuid for it to identify it in their system. My idea was to save a string such as `[tempo-id:{UUID}]` in an intervals annotation in order to figure out if something has been sent to tempo before or not (in order to prevent double-tracking in tempo).

For this use case the (temporary) record id of timewarrior is enough since it is only needed to modify the interval at this very moment.

**Comment by sruffell** [comment]
> For this use case the (temporary) record id of timewarrior is enough since it is only needed to modify the interval at this very moment.

If this is the case, I would imagine the ID timewarrior provides does not add any additional value over generating ids in the extension (i.e. using the index in the JSON array)? I only ask to make sure I understand.

**Comment by j6s** [comment]
True, I could generate the ID in the extension (from what i understand it is an incrementing number starting at 1 for the newest record - but explicitly passing it to extensions would remove the ambiguity of basically having to 'guess' it as well as making extensions more robust when it comes to future changes in timewarriors API / data model.

All in all this is not an important thing, more of a extension development quality of life improvement.

**Comment by sruffell** [comment]
Ok, I think I understand.

That said, I'm still in favor of this change. I would like to create a report for say, last week, that includes the ids in the report in case I need to adjust tags or annotations for the intervals without having to run `timew summary :ids :lastweek` just to get the IDS.

**Comment by lauft** [comment]
> My idea was to save a string such as [tempo-id:{UUID}] in an intervals annotation ...

First, let's agree that this an abuse of the interval annotation. 😄
Don't worry this just point out that we **really** need a way to flexibly store interval meta data. (see #288)

Second, I agree that this addition would avoid the extra call to Timewarrior to figure out the respective interval ids and makes it also more stable in case the interval ids do not match with the array index.

Concerning your PR: Please - apart from the things @sruffell already pointed out in the review - also update/add the documentation of the respective commands. 

At last: Please consider to publish your add-on. 😉
