### ISSUE TITLE
Output `timew start MyTag` shows negative total across years

### ISSUE THREAD

**Issue by johanbove** [GothenburgBitFactory/timewarrior#287]
Since a couple of weeks I am seeing negative `total` calculation in the output when I start working on a project "AProjectName" which spans over multiple years. Not sure why this happens? How can I debug this? Thanks!

Output:
```bash
~ ⏰  $ timew 
There is no active time tracking.
 ~ ⏰  $ timew start
Tracking 
  Started 2020-02-12T17:14:17
  Current                  17
  Total               0:00:00
 ~ ⏰  $ timew stop
Recorded 
  Started 2020-02-12T17:14:17
  Ended                    20
  Total               0:00:00
 ~ ⏰  $ timew start AProjectName
Tracking AProjectName
  Started 2020-02-12T17:14:30
  Current                  30
  Total         -8478:-26:-52
 ~ ⏰  $ timew diagnostics

timew 1.2.0
       Platform: Darwin

Compiler:
        Version: 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)
           Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
     Compliance: C++11

Build Features
          Built: Dec 17 2019 10:04:37
          CMake: 3.15.2
     Build type: release

Configuration
  TIMEWARRIORDB: -
            Cfg: /Users/johan/.timewarrior/timewarrior.cfg (-rw- 468 bytes)
       Database: /Users/johan/.timewarrior (drwx 160 bytes)
    Color theme: Built-in default
                 00 01 02 03 04 05 06 07 08 09 10 11 12

Extensions
       Location: /Users/johan/.timewarrior/extensions (drwx 64 bytes)
               (None)

```

Configuration:
```
# This does not do anything yet
#weekstart = monday
 
import /usr/local/share/doc/timew/doc/holidays/holidays.de-DE
 
# Setting limits for a regular workweek
# https://taskwarrior.org/docs/timewarrior/workweek.html
define exclusions:
  monday    = <9:00 12:00-13:00 >18:30
  tuesday   = <9:00 12:00-13:00 >18:30
  wednesday = <9:00 12:00-13:00 >18:30
  thursday  = <9:00 12:00-13:00 >18:30
  friday    = <9:00 12:00-13:00 >18:30
  saturday  = >0:00
  sunday    = >0:00
```

**Comment by sruffell** [comment]
@johanbove The output you posted is very strange. For example, your first start / stop commands look like they should have taken 3 seconds, but the total for that empty interval is 0 seconds?

Before I look into this more, are you still having this problem?  I'm wondering if it was because of your system clock slewing?

If you are still seeing this, would it be possible for you to post the output of `timew export :day` after running the same sequence of commands you ran above?

**Comment by sruffell** [comment]
Related to #248 since that issue wants to generally change what is reported in the intervalSummarize function.

**Comment by lauft** [comment]
I am closing this as a stale issue. Maybe #368 solves this anyway...

**Comment by johanbove** [comment]
Today I figure out what was going on. I had a file in the `~/.timewarrior/data` folder which was set in the future. I removed that file and the total calculation is correct again.
