### ISSUE TITLE
Please allow tag exclusion in summary

### ISSUE THREAD

**Issue by nodens** [GothenburgBitFactory/timewarrior#297]
Hi,

it would be great to allow exclusion of certain tags in summary.
For instance, !tag or something similar to exclude entries containing !tag in the output.

I currently tag intervals with "invoiced" and "paid", and I can just use grep to filter, but then I don't get a sum of the time involved

I would like to be able to do something like:
`timew summary customer !invoiced` to know what I have yet to put in invoice, or
`timew summary !paid` to know which customer I need to send a reminder to.

Thanks!

**Comment by sruffell** [comment]
Hi nodens, just a heads up that this is a duplicate of #209 and is related to #281.

**Comment by nodens** [comment]
oh, right. Thanks. I'll close this one then. Thanks!
