### ISSUE TITLE
tests failing for template.t

### ISSUE THREAD

**Issue by sskras** [GothenburgBitFactory/timewarrior#303]
I run TimeW in Msys2 (the Cygwin fork):
```
$ uname -a
MSYS_NT-10.0 SAUKRSXM1 2.11.1(0.329/5/3) 2018-09-10 14:19 x86_64 Msys
```

After I build the source tree, I run tests and get following failure:
```
$ make test
  ...
# template.t
1..4
not ok 1 - template.t: Test something that fails and we know or expect that # TODO
# EXPECTED_FAILURE: AssertionError on file /home/saukrs/src/timewarrior/test/template.t line 107 in test_expected_failure: 'self.assertEqual(1, 0)':
#                   1 != 0
ok 2 - template.t: Running tests using libfaketime # skip
# SKIP:
#       libfaketime/faketime is not installed
```

Another failure follows soon, I reported it at the end of https://github.com/GothenburgBitFactory/timewarrior/issues/67#issuecomment-614186469

I am not sure whether this is useful to report.

**Comment by lauft** [comment]
`template.t` is not meant to be run, thus it should not be executable. Can you check this?

`template.t` is - as the name suggests - just a template for test files. Maybe we should move it somewhere else/delete it...

**Comment by lauft** [comment]
Diagnosis data: `v1.2.0-d73143b (Apr 14, 2020)`

**Comment by lauft** [comment]
I have removed `template.t` from the repository. I think the existing test files are sufficient as templates.
