### ISSUE TITLE
At least one tag must be specified 

### ISSUE THREAD

**Issue by dennis-tra** [GothenburgBitFactory/timewarrior#306]
Hi everyone,

thanks for your work - I just started using timewarrior.

Unfortunately I cannot tag a time slot with `daily`:
```
$ timew tag @2 'daily'                                                                                                                                                     
At least one tag must be specified. See 'timew help tag'.
```

For some reason if I omit the `d` it works with `aily`.

I suspect it's a problem with parsing the command line arguments?

**Comment by lauft** [comment]
Timewarrior interprets `daily` as a datetime statement (see #60). The command line parsing is a bit to eager at this point. This is know and will be worked on in a future release.

**Comment by lauft** [comment]
Duplicate of #60

**Comment by dennis-tra** [comment]
Great thanks for the fast reply
