### ISSUE TITLE
`timew` command reports incorrect running time in cygwin

### ISSUE THREAD

**Issue by daytonb** [GothenburgBitFactory/timewarrior#308]
When I run the `timew` command, I often get the wrong amount of running time on my Windows computer where I compiled and use timew in a cygwin terminal. To confirm the issue, I compiled on a CentOS 8 machine using the same build commands. Also, the time is correctly reported when I run `timew sum`.

Windows machine (cygwin)
```
$ ~/opt/timew-test-install/bin/timew.exe
Tracking sapphire
  Started 2020-04-28T06:25:00
  Current               58:42
  Total               2:31:41

$ ~/opt/timew-test-install/bin/timew.exe sum

Wk  Date       Day Tags       Start End    Time   Total
W18 2020-04-28 Tue sapphire 6:25:00   - 0:33:44 0:33:44

                                                0:33:44


$ ~/opt/timew-1.1.1/bin/timew.exe diagnostics

timew 1.1.1
       Platform: Cygwin

Compiler:
        Version: 7.4.0
           Caps: +stdc +stdc_hosted +200809 +200809 +LP64 +c8 +i32 +l64 +vp64 +time_t64
     Compliance: C++11

Build Features
          Built: Jan 29 2020 10:59:44
          CMake: 3.14.5
     Build type: release

Configuration
  TIMEWARRIORDB: -
            Cfg: /home/username/.timewarrior/timewarrior.cfg (-rw- 231 bytes)
       Database: /home/username/.timewarrior (drwx 0 bytes)
    Color theme: Built-in default
                 00 01 02 03 04 05 06 07 08 09 10 11 12

Extensions
       Location: /home/username/.timewarrior/extensions (drwx 0 bytes)
               (None)
```

Linux machine
```
$ ~/opt/timew-1.1.1/bin/timew
Tracking
  Started 2020-04-28T06:25:00
  Current               59:43
  Total               0:34:43
$ ~/opt/timew-1.1.1/bin/timew sum

Wk  Date       Day Tags   Start End    Time   Total
W18 2020-04-28 Tue      6:25:00   - 0:34:49 0:34:49

                                            0:34:49

$ ~/opt/timew-1.1.1/bin/timew diagnostics

timew 1.1.1
       Platform: Linux

Compiler:
        Version: 8.3.1 20190507 (Red Hat 8.3.1-4)
           Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
     Compliance: C++11

Build Features
          Built: Apr 28 2020 06:42:17
          CMake: 3.11.4
     Build type:

Configuration
  TIMEWARRIORDB: -
            Cfg: /home/username/.timewarrior/timewarrior.cfg (-rw- 0 bytes)
       Database: /home/username/.timewarrior (drwx 72 bytes)
    Color theme: Built-in default
                 00 01 02 03 04 05 06 07 08 09 10 11 12

Extensions
       Location: /home/username/.timewarrior/extensions (drwx 10 bytes)
               (None)
```

**Comment by daytonb** [comment]
Oh yeah, I meant to post the commands I used to compile timew on both machines:
```
$ curl -O https://taskwarrior.org/download/timew-1.1.1.tar.gz
$ tar xf timew-1.1.1.tar.gz
$ cd timew-1.1.1/
$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=$HOME/opt/timew-1.1.1 ..
$ cmake --build . --target install --config Release
```

**Comment by lauft** [comment]
As a first measure I would always recommend upgrading to the latest Timewarrior version if possible - in this case 1.3.0 which was released on 19 Apr.

When you say "often" this implies to me "not always", which hints that there is something else that may cause this behaviour.

Ideally, one should be able to reproduce the behaviour with a script like this:
```
export TIMEWARRIORDB=/tmp/timewarriordb
rm -rf ${TIMEWARRIORDB}
mkdir -p ${TIMEWARRIORDB}/data
:> ${TIMEWARRIORDB}/timewarrior.cfg

# do something else that is necessary here...

timew start
timew summary
```

**Comment by daytonb** [comment]
I didn't realize that there was a release newer than 1.1.1. I was following the instructions on https://timewarrior.net/docs/download.html. Now I know to go check the releases section on the github project.

I wasn't certain if the issue was happening 100% of the time because I often don't pay close attention to the time reported by running just the timew command without arguments. Usually when I do that I'm just checking to see that I did start my time tracker. However, I'm pretty sure it was always happening. 

I can't reproduce the bug now with 1.1.1 (which is the version I reported with). I wonder if it was something peculiar about the system. It was happening on my work laptop, but it has since been re-imaged due to general IT changes. Maybe the re-imaging swapped out whatever weird quirk was causing the issue with timew. I'm going to co ahead a close the ticket since even I can't reproduce it now. I'll open it back up if I notice the behavior again.

**Comment by lauft** [comment]
> I was following the instructions on https://timewarrior.net/docs/download.html.

Thanks for the notice, this should be updated...

**Comment by lauft** [comment]
@daytonb The documentation has been updated. The instructions can now be found on https://timewarrior.net/docs/install.html and are hopefully a bit more up-to-date now.

**Comment by daytonb** [comment]
I caught it doing in correct math again, so maybe it is reproducible somehow:

```
$ timew stop
Recorded SENTRi
  Started 2020-08-13T07:28:16
  Ended              15:53:16
  Total              11:19:41

$ timew sum

Wk  Date       Day Tags     Start      End    Time   Total
W33 2020-08-13 Thu SENTRi 7:28:16 15:53:16 8:25:00 8:25:00

                                                   8:25:00


$ timew diagnostics

timew 1.3.0
       Platform: Cygwin

Compiler:
        Version: 9.3.0
           Caps: +stdc +stdc_hosted +200809 +200809 +LP64 +c8 +i32 +l64 +vp64 +time_t64
     Compliance: C++11

Build Features
          Built: Aug 11 2020 08:08:41
          CMake: 3.14.5
     Build type:

Configuration
  TIMEWARRIORDB: -
            Cfg: /home/bboulton/.timewarrior/timewarrior.cfg (-rw- 0 bytes)
       Database: /home/bboulton/.timewarrior (drwx 0 bytes)
    Color theme: Built-in default
                 00 01 02 03 04 05 06 07 08 09 10 11 12

Extensions
       Location: /home/bboulton/.timewarrior/extensions (drwx 0 bytes)
               (None)
```

**Comment by lauft** [comment]
@daytonb Do the adjacent intervals (i.e. `@2`, `@3`,...) happen to have the same tag `SENTRi`? Currently Timewarrior summarizes not only over the recently recorded interval but over all intervals with the same tag(s). 

Quoting from the code:
> Walk backwards through the inclusions, and stop as soon as the tags no longer match interval. This means the 'total' is the sum of all time in the most recent set of intervals for the same tags. This is the acceptable definition of "the current task".

**Comment by daytonb** [comment]
I see that makes sense. It also would explain why I had different behavior
when I tried to test in the Linux machine. I didn’t have any past activity
on that one.

Byron

**Comment by sruffell** [comment]
Looks like a duplicate of #248.

**Comment by daytonb** [comment]
I agree with @sruffell. This is a duplicate of #248.
