### ISSUE TITLE
Show time as hours with decimal instead of number of minutes?

### ISSUE THREAD

**Issue by ahillio** [GothenburgBitFactory/timewarrior#311]
Is there a way to get timew reports to show decimals instead of number of hours?

There are times when I need to know "number of hours" and not "time in minutes" so instead of `3:11:08` I need to see `3.18`.

I've searched timewarrior.net/docs/ and the man page but don't see anything about this.

Does timewarrior provide a flag/paramater/commandline option to specifiy this format instead of the default?  Is there an extension that does this?  Do I need to write me own?

**Comment by lauft** [comment]
Currently there is no such option.

If you want to write your own extension you might want to try https://github.com/lauft/timew-report which can help you parsing the interval data.

**Comment by ahillio** [comment]
Thank you for clarifying.

**Comment by xged** [comment]
What about just ignoring seconds?
