### ISSUE TITLE
bash-completion missing in tagged release

### ISSUE THREAD

**Issue by algent-al** [GothenburgBitFactory/timewarrior#314]
Hi! In the source there is a `timew-completion.bash` file but this is missing on `timew-1.3.0.tar.gz`.
Don't know if this is intentional, so I open this issue.

**Comment by lauft** [comment]
You are right, thanks for reporting this.

This is fixed in the tar-file with checksum c04c3ebefddd485323784409987ae66c11c3ce4c882a290c10934336a196f3e8.
