### ISSUE TITLE
Make date format more permissive

### ISSUE THREAD

**Issue by xerus2000** [GothenburgBitFactory/timewarrior#321]
- days of the week currently require at least three letters, while two-letter specifications are the norm and should not interfere with anything - otherwise this should be documented to avoid confusion
- I tried to enter a time as `20200511T23:40` and it reported "No updated time specified." - it took me ages to figure out that I was trying to combine a date with an extended time. Why wouldn't you allow combining these?
- Also, the message I got above was not particularly helpful - maybe add some more info if specifying a wrong format?

**Comment by lauft** [comment]
In short: KISS. Following a standard (e.g ISO 8601 in this case) strictly makes parsing and validation easy. Allowing deviations from the standard may demand more efforts to discriminate typos/errors from valid input.

In any case we are always grateful for updates in documentation. If you could add some more information on where you encoutered the unhelpful "no updated time specifed" message, we maybe can work on improving the error message.

**Comment by xerus2000** [comment]
You are already deviating by allowing `YYYYMMDDTHHMM`

What I am asking for is an independent parsing of date and time. So if the input contains a "T", then split it and parse the right one as a time and the left one as a date.
That way, you could easily allow the pairing of any of the date formats with any of the time formats

YYYY-MM-DD
YYYYMMDD
yesterday

18:00
1040

`yesterdayT1900` is actually the combination I am missing most, but also a combination of date and extended time (`20200511T20:00`) or of weekdays and time could be very handy.

**Comment by lauft** [comment]
> You are already deviating by allowing YYYYMMDDTHHMM

Nope, this agrees with ISO 8601 (https://en.wikipedia.org/wiki/ISO_8601) 😉 

Combining date and time a bit more freely is already on the agenda (see #196), however this proposal wont allow `yesterdayT1900` or `20200511T20:00` but `yesterday 1900` and `20200511 20:00`. The constraint being that within the specification of either date, time or datetime the format has to be consistent.

**Comment by xerus2000** [comment]
Oh, I wasn't aware of that. Yes, that would satisfy me as well, and for the error message I have opened a separate issue, so I think we can close this :)
