### ISSUE TITLE
Reports do not support :id

### ISSUE THREAD

**Issue by cazador481** [GothenburgBitFactory/timewarrior#323]
I would like to create reports with the :id intact.  this would allow me to customize the output of timewarrior, so I can use it with FZF easier.

**Comment by sruffell** [comment]
The recently released 1.3.0 will pass the id to extensions (which includes reports).

See #285

**Comment by lauft** [comment]
Keep in mind that ids are only valid until the database gets modified. For further support it would be helpful if you could elaborate more on your usecase.

**Comment by cazador481** [comment]
right now I am using fzf to help me find the id so that I can continue a previous run.  The command that I am using to do that is
     

timew continue \`timew summary :id :month |fzf |rg '@\d+' -o`

I can the type jira:<jiraid> that cmd line will continue from the previous jira entry. 

I want to be able to filter what is coming from the summary command, so that I can hide tags that I don't care about, as some of my tasks have a large number of tags.

If https://github.com/GothenburgBitFactory/timewarrior/pull/241 gets merged in, then the need for this gets reduced

**Comment by lauft** [comment]
@cazador481 I don't know whether it would help (as I am not that familiar with `fzf` and `rg`), but with #126 there is now the possibility to query Timewarrior for ids filtered by tags and date range, e.g.:
```
timew get dom.tracked.ids <from> - <to> <tags>
```
