### ISSUE TITLE
Make tags.data easier to handle with version control

### ISSUE THREAD

**Issue by quazgar** [GothenburgBitFactory/timewarrior#325]
# Use case
I am working on a setup to use timewarrior on multiple machines, with merging data using git.

# Suggestion
- one tag per line

Version control of the timewarrior directory would be simplified if `tags.data` had just one tag per line. This way, diffs between different versions on different machines are easy to manage.

**Comment by quazgar** [comment]
This can probably be implemented by simply adding a `\n` in this line: 
https://github.com/GothenburgBitFactory/timewarrior/blob/c71eeb6dfd080ba09547a281a8bddd6bac0392d1/src/TagInfoDatabase.cpp#L119

**Comment by quazgar** [comment]
See #342

**Comment by lauft** [comment]
Thanks for your suggestion and your PR. 👍
I also updated the tests for the `TagInfoDatabase` such that this JSON output format is ensured.
