### ISSUE TITLE
update apt repo

### ISSUE THREAD

**Issue by OpenCoderX** [GothenburgBitFactory/timewarrior#328]
`apt install timewarrior` installs 1.0.0

**Comment by OpenCoderX** [comment]
@lauft is this possible?

**Comment by lauft** [comment]
@OpenCoderX if the maintainer has not upgraded the package, yes. 

Please contact the maintainer of the package about that.

**Comment by OpenCoderX** [comment]
@lauft is @pbeckingham the maintainer?

**Comment by lauft** [comment]
@pbeckingham is the maintainer of Taskwarrior. 

System packages for Timewarrior are a community effort. See the your package index for the respective mainainer. 

E.g. for Ubuntu Bionic (https://packages.ubuntu.com/bionic/timewarrior) it is the [Ubuntu MOTU Developers](mailto:ubuntu-motu@lists.ubuntu.com).
