### ISSUE TITLE
Summary command fails with `:all` hint

### ISSUE THREAD

**Issue by lauft** [GothenburgBitFactory/timewarrior#333]
With #206 (c9eec956e4866c8af47f73b27c2f3975ffd01a35) the `summary` command displays an empty table when being called with the `:all` hint (specifying a range works):

```
$ timew track 2020-06-04T10:00:00 - 2020-06-04T11:00:00
$ timew track 2020-06-05T10:00:00 - 2020-06-05T11:00:00
$ timew track 2020-06-06T10:00:00 - 2020-06-06T11:00:00

$ src/timew summary :all

Wk Date Day Tags Start End Time   Total
-- ---- --- ---- ----- --- ---- -------                                       
                                0:00:00


$ src/timew summary 2020-06-04 - 2020-06-13

Wk  Date       Day Tags    Start      End    Time   Total
--- ---------- --- ---- -------- -------- ------- -------
W23 2020-06-04 Thu      10:00:00 11:00:00 1:00:00 1:00:00
W23 2020-06-05 Fri      10:00:00 11:00:00 1:00:00 1:00:00
W23 2020-06-06 Sat      10:00:00 11:00:00 1:00:00 1:00:00
                                                         
                                                  3:00:00
```

For `:all` the CLI returns an empty filter which `CmdSummary` terminates as any open interval to `start + 1d`.

This does not impede retrieving the right intervals as the filter gets manipulated in `src/data.cpp:497` to an open interval (ouch! 🤕) starting at the first inclusion.

However, when displaying the data, the filter is used to determine the day range to diplay the intervals day by day. This loop aborts as the loop variable is checked whether it is less than `filter.end` (which is 0 and thus the check is always false) leaving the table empty.

**Comment by lauft** [comment]
One partial fix to the problems with the `:all` hint was to change `CmdSummary:118` from
```
for (Datetime day = filter.start; day < filter.end; day++)
...
```
to
```
auto days_start = filter.start == 0 ? tracked.front ().start : filter.start;
auto days_end   = filter.end == 0   ? tracked.back ().end    : filter.end;

for (Datetime day = days_start; day < days_end; day++)
...
```
because for an open interval (`filter.end = 0`) the for loop was never entered. With this change open filters are handled better. Now even something like `summary until <date>` should be possible.

**Comment by sruffell** [comment]
This looks good to me.  The way the code is right now, the update to days_start is redundant since getTracked already modifies the passed filter to match the first interval if it is otherwise open (but honestly, I would like to make getTracked take a constant reference to the filter, since it is not obvious that it is returning it this way)

Also, my preference would be to use `filter.is_started ()` instead of `filter.start == 0` since 0 is overloaded with the way filters use it (i.e. does it mean it's undefined, or that it's the UNIX Epoch?)

**Comment by lauft** [comment]
I agree with your idea to turn the filter into a const reference in `getTracked`. Filters should be immutable objects.
