### ISSUE TITLE
Timeserver for synchronization

### ISSUE THREAD

**Issue by RasmusBertell** [GothenburgBitFactory/timewarrior#340]
I'd like to be able to use multiple computers to track my time depending on my location.
I looked if there was anything similar to taskserver for timewarrior, but couldn't find anything.

One solution is to have timewarrior run on the server and ssh into it, but in my opinion, a dedicated service would be a better choice, since it would also open up the possibility to use timewarrior with a mobile app or a web service through an API.

I understand if this issue is out of scope for timewarrior, but as I stated, I couldn't find any similar issues and thought I would bring this to attention. Also if there is any way to do this currently without ssh I would like to know.

Thank you for this awesome product and for taking the time to review my feature request.

**Comment by SGOrava** [comment]
Hello,
this topic was kind of discussed at https://github.com/GothenburgBitFactory/taskserver/issues/129 and the reselt is something like (if nothing changed): 
t is a lot of work, feel free to contribute.

Best regards
PS: I am just passing by

**Comment by lauft** [comment]
@quazgar is "working on a setup to use timewarrior on multiple machines, with merging data using git." see #325 
I am not sure about the current status of his project, but it may be a quicker solution than implementing a _timeserver_.

**Comment by quazgar** [comment]
What I have: Two scripts to synchronize a local `.timewarrior` directory with a git repo.

The user still needs to manually check that lines to the data files are only added, not removed while merging. And I do not have any logic yet to check the tag counters for consistency. For now I only make sure (manually while merging) that the counters only increase, never decrease.

These drawbacks sometimes result in problems when I only merge times from different computers after the time tracking data already has diverged. I can share the scripts though, if anyone wishes.

**Comment by quazgar** [comment]
The scripts are here, if you want, I can write a PR for them:

https://github.com/quazgar/timewarrior/commit/448209c7a50ec10c5c2a31278dcc7c54b8eb8c60

**Comment by sruffell** [comment]
What if timewarrior had an `import` command that could read / parse the output of the existing `export` command?  In this way it would be possible to use timewarrior on multiple machines and import any records into a "master" timewarrior database over ssh:

```
timew export :week | ssh <myserver> 'timew import'
```

**Comment by lauft** [comment]
Setting up (and maintaining) a Timeserver project is outside the current capabilities of the Timewarrior project/Gothenburg Bit Factory. Timewarrior may ease some pains that come with syncing different Timewarrior databases (e.g. #342 or #359), but for the time being thats about it.

Enthusiast who are willing to take on such an endeavour are still welcome to contact us, but they should present a stable long term plan.

**Comment by lauft** [comment]
One may want to try out https://github.com/timewarrior-synchronize

**Comment by cwegener** [comment]
@danisztls FWIW, I have been putting my `~/.timewarrior` folder into Syncthing and that works great for my use case (single user, multiple machines)

**Comment by danisztls** [comment]
@cwegener I'm worried about Syncthing due to poor observability over conflcts and changes in case I mass rename a tag or have to modify a record.

**Comment by cwegener** [comment]
I regularly modify records without ever having had any problems caused by Syncthing.
I haven't done any mass renaming of tags, so I can comment on that.
The only comment I do have is that editing the files in `~/.timewarrior` directly with a text editor is probably the only "scary" thing to do. I always use the CLI to do modifications.
