### ISSUE TITLE
[TI-27] Continue tracking by ID

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#35]
_Dennis Schubert on 2016-07-26T09:32:19Z says:_ 

 It would be useful if we could continue a tracking by using the ID, since people often switch between tasks:

{code}
timew continue @2
{code}

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-07-26T09:32:19Z
Modified: 2017-04-06T20:51:11Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-07-26T12:56:57Z says:_ 

 This is planned for 1.1, where `(at)ids` will be allowed interchangeably with date ranges or tag lists.

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2017-02-02T20:32:25Z says:_ 

 Is this feature already in development? As I am really craving for it I take the plunge and supply some tests.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-02-05T22:23:00Z says:_ 

 Thank you Thomas.  Tests gratefully accepted, merged and pushed.

The current focus is getting Taskwarrior 2.6.0 and Taskserver 1.2.0 out, so ti will be a little while longer before this is implemented.  It's already tagged for 1.1.0, and will be in the next version.

Meanwhile it's a matter of contributors, patches and time.  Your tests definitely help.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-02-25T19:21:14Z says:_ 

 The implict @1 will solve several issues.

**Comment by pbeckingham** [comment]
[TI-27_0001-TI-27-Add-tests-for-continue-with-ids.patch.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755267/TI-27_0001-TI-27-Add-tests-for-continue-with-ids.patch.txt)
