### ISSUE TITLE
Empty tags.data

### ISSUE THREAD

**Issue by flippipe** [GothenburgBitFactory/timewarrior#353]
Hi,

Today when I run timew it returns what ever switch or command

```
Error: expected '{' or '[' at position 0
```

After some troubleshoot I've found the file tags.data was empty

```
-rw-rw-r-- 1 fc fc      0 ago  3 09:33 tags.data
```

After restore from a backups, it start working fine.

```
-rw-rw-r-- 1 fc fc   6243 ago  3 13:50 tags.data
```

**Comment by sruffell** [comment]
@flippipe if you update to timewarrior v1.3.0, it should now regenerate the tags database if there are any parsing problems.

**Comment by flippipe** [comment]
Indeed I'm using a old version: 1.2.0
