### ISSUE TITLE
Meaning of tags.data

### ISSUE THREAD

**Issue by rudolfschmidt** [GothenburgBitFactory/timewarrior#355]
I am wondering why you had to use a counter in tags.data. 

What happens when you delete data from date.data or you change the content from tags.data, change the counter?

**Comment by lauft** [comment]
The purpose of the `tags.data` is to detect whether a tag is new so that Timewarrior can notify the user (`Note: 'FOO' is a new tag.`).
When you add/delete/modify intervals via Timewarrior commands, the tag counter gets updated. 

As always you should not manipulate the data files directly to avoid inconsistencies in the database. When `tags.data` gets out of sync with the interval data you can delete it and Timewarrior will recreate it from the interval data.

**Comment by rudolfschmidt** [comment]
If you ask me I would remove the file completely and calculate everything internally by considering the data files. Some microseconds do not change the life but make the files less verbose and more lean, leading to less discussion. Before I became usual with your commands I deleted the interval lines from data myself to test around and wondered if I can do the same with the tags and when not. 
Now I understood that I can delete it whenever I feel its not synced, thanks for clarification.

**Comment by lauft** [comment]
If the database becomes big, those microseconds sum up to some considerable delay. See #245 and everything related.

**Comment by rudolfschmidt** [comment]
Never tested, but ok I believe it is like you say.
My strive is to make the files as less fragile as possible.

**Comment by lauft** [comment]
> you mentioned in your docs that is fine to delete undo.data or the content of it (lines)

Deleting lines of `undo.data` is IMHO false information and should be corrected. Can you tell me the exact location? On https://timewarrior.net/docs/files.html I only find
> The undo.data file stores transactions for the undo command. ... deleting it periodically only affects your ability to undo changes.

which says nothing about deleting parts of `undo.data`, only the total file.

On the same page there also is the general advice for all files:
> There should never be a situation where you need to manually edit these files.

**Comment by rudolfschmidt** [comment]
> > you mentioned in your docs that is fine to delete undo.data or the content of it (lines)
> 
> Deleting lines of `undo.data` is IMHO false information and should be corrected. Can you tell me the exact location? On https://timewarrior.net/docs/files.html I only find
> 
> > The undo.data file stores transactions for the undo command. ... deleting it periodically only affects your ability to undo changes.

Its wirtten:

> "This file grows indefinitely, and deleting it periodically only affects your ability to undo changes."

tells me, you are not supposed to, but it is ok to delete lines because the file grows indefinitely AND it affects only your ability to undo something, nothing more.

> 
> which says nothing about deleting parts of `undo.data`, only the total file.

hm...

> 
> On the same page there also is the general advice for all files:
> 
> > There should never be a situation where you need to manually edit these files.

True.
