### ISSUE TITLE
MacOS is missing ID when installed through Homebrew

### ISSUE THREAD

**Issue by Alacho2** [GothenburgBitFactory/timewarrior#357]
When installing through Homebrew, it looks like Timewarrior is lacking IDs when creating stopwatches. It's possible to add tag, but the @1, @2, @3, etc is missing. [Provided screenshot](https://imgur.com/a/hihGBLN).

Running macOS Catalina, 10.15.5. Will provide more information if required. :)

**Comment by sruffell** [comment]
@Alacho2 did you pass the `:ids` hint to the summary command?

For example, without :ids 
```
$ src/timew summary

Wk  Date       Day Tags   Start End    Time   Total
W32 2020-08-06 Thu foo  0:16:02   - 2:00:13 2:00:13

                                            2:00:13
```

and with :ids

```
$ src/timew summary :ids

Wk  Date       Day ID Tags   Start End    Time   Total
W32 2020-08-06 Thu @1 foo  0:16:02   - 2:00:16 2:00:16

                                               2:00:16
```

**Comment by Alacho2** [comment]
@sruffell Thanks for the quick response.
I did not, sorry about that! It is working as it should then :D
