### ISSUE TITLE
Summary configuration

### ISSUE THREAD

**Issue by davidoskky** [GothenburgBitFactory/timewarrior#389]
The daily, weekly and monthly report can be configured with many parameters, the summary can not.
I prefer the summary as it just gives me a list without graphics, but I would love it to be a little bit more configurable.
It is impossible, for example, to remove the week number or the name of the day from the report.
Would it be possible to add the same options available for the other reports to the summary as well?
I would like such a feature mainly to remove all the data I do not care for and unclutter a bit the report, which would allow me to keep it in a smaller window.

**Comment by sruffell** [comment]
Hmm, I'm personally not sure what a good set of configuration parameters for the summary report would be.

That said, there is a way to make a report that is customized for exactly you want to see if you feel comfortable editing python. For example, here I create three intervals that I display with the totals report that is shipped as part of the source:

```
$ rm -fr $TIMEWARRIORDB
$ mkdir -p $TIMEWARRIORDB/extensions
$ cp ext/totals.py $TIMEWARRIORDB/extensions
$ src/timew :quiet start 10h ago proja
$ src/timew :quiet stop 9h ago
$ src/timew :quiet start 8h ago projb
$ src/timew :quiet stop 7h ago
$ src/timew :quiet start 6h ago projc
$ src/timew :quiet stop 5h ago
$ src/timew report :day totals

Total by Tag, for 2020-09-29 00:00:00 - 2020-09-30 00:00:00

Tag        Total
proja    1:00:05
projb    1:00:05
projc    1:00:06

Total    3:00:16
```

So, by writing your own or modifying one of the existing python scripts (or any programming language of your choice) you can produce output that fits your requirements exactly.

**Comment by lauft** [comment]
@davidoskky I will not rule out that there could be a bit more configuration for the summary, but I rather aim to keep this report lean and simple. Its main purpose is to give you a quick overview and - most important - show you the ids you need to modify intervals. 

> It is impossible, for example, to remove the week number or the name of the day from the report.

This might be a good idea... 🤔 

> Would it be possible to add the same options available for the other reports to the summary as well?

In general, no - however this depends on which option you mean. IMHO `timew summary` will never be able to satisfy every user's need, so I think it should not try at all/too hard to have configurations for everything. Some column selection should be possible (as it is already with `:ids` and `:annotations`).

For everything more complex Timewarrior should rather try to enable users to plug in their own specific reports (as @sruffell already suggested).

**Comment by lauft** [comment]
FYI, @davidoskky, with 6f141f63 and 1a6d5cac, it has become possible to configure the display of columns `ids`, `tags` and `annotation` in the summary report.
