### ISSUE TITLE
dom.tracked.X.tag.Y always returns dom.tracked.1.tag.Y

### ISSUE THREAD

**Issue by pweaver2019** [GothenburgBitFactory/timewarrior#390]
If I start a new entry with a unique tag then dom.tracked.x.tag.1 always returns the dom.tracked.x.tag.1 value. You can see that dom.tracked.20.tag.count returns 3, but dom.tracked.20.tag.2 is not valid and dom.tracked.20.tag.1returns the same as dom.tracked.1.tag.1.

I know that we are on an old version, but this is the most recent version, but it is the recent version available as a pre-built package on CENTOS.

$ timew --version
1.0.0
$ timew start 'new tag for testing'
...
Tracking "new tag for testing"
  Started 2020-09-30T13:09:24
  Current                  24
  Total               0:00:00
$ timew get dom.tracked.1.tag.1
new tag for testing
$ timew get dom.tracked.2.tag.1
new tag for testing
$ timew get dom.tracked.3.tag.1
new tag for testing
$ timew get dom.tracked.20.tag.count
3
$ timew get dom.tracked.20.tag.2
DOM reference 'dom.tracked.20.tag.2' is not valid.
$ timew get dom.tracked.20.tag.3
DOM reference 'dom.tracked.20.tag.3' is not valid.
$ timew get dom.tracked.20.tag.1
new tag for testing

**Comment by lauft** [comment]
Your problem is also present `1.4.2`:
```
$ timew start 'new tag for testing' 2h ago
...
$ timew start 'TAG2' 1h ago
...
$ timew start 'TAG3'
...
$ timew get dom.tracked.1.tag.1
TAG3
$ timew get dom.tracked.2.tag.1
TAG3
$ timew get dom.tracked.3.tag.1
TAG3
```

I found the problem and fixed it. Thanks for spotting it!

However, you should try to contact your package maintainers and ask them to upgrade the package so you can get the fix with the next version. Or you switch to a manual install.
