### ISSUE TITLE
Environment Variables for data directory and config file?

### ISSUE THREAD

**Issue by ekiim** [GothenburgBitFactory/timewarrior#392]
Is there a way to set the configuration and data files, instead of just letting them sit directly on home? 
Task warrior includes a way to overwrite does locations by using environment variables. 
I don't see in the man pages anything about that.

**Comment by lauft** [comment]
You can use `TIMEWARRIORDB` to define the directory where data and config are stored. This usually defaults to `~/.timewarrior`. 
This is mentioned in `man 7 timew-config`, but I think this could need a reference/mention in `man 1 timew-config` (and elsewhere) as well.

**Comment by ekiim** [comment]
In principle, the `timewarrior.cgf` file would be inside the directory that I assign to the `TIMEWARRIORDB` variable? 
Shouldn't it be a different variable like `TIMEWARRIORRC` or something?, because in some sense the _database_ it can be considered a _cache_ directory, and the other a _config_.
Anyway I came around that by linking the file to a file on my `$HOME/.config` directory.

**Comment by lauft** [comment]
Currently, `TIMEWARRIOR` is the only environment variable for this. There is no `TIMEWARRIORRC` like in Taskwarrior. There are plans to move to the XDG Base Directory Specification (see #207), but this needs a careful migration plan.
