### ISSUE TITLE
Switch libshared from submodule to subtree

### ISSUE THREAD

**Issue by sruffell** [GothenburgBitFactory/timewarrior#396]
Currently libshared is a submodule, but the upstream maintainer has been generally inaccessible.

Switching timewarrior to use a subtree merge strategy for the libshared would make it easier (IMO) to carry local changes until such a time that they are merged into the upstream project.

Would a PR that switches from a submodule to a subtree be welcome?

**Comment by lauft** [comment]
I am not sure about subtrees, both methods (submodules and subtrees) have their curses and blessings... 🤔 

I have decided to move a bit more boldy when it comes to libshared, so PRs concerning Timewarrior will be merged faster. Parallel I try to get setup continuous integration with libshared to get quicker insights on sideeffects.

**Comment by lauft** [comment]
@sruffell I have merged your PRs on libshared and updated Timewarrior to the respective HEAD of libshared.

**Comment by sruffell** [comment]
> I have decided to move a bit more boldy when it comes to libshared, so PRs concerning Timewarrior will be merged faster. Parallel I try to get setup continuous integration with libshared to get quicker insights on sideeffects.

Thanks! That works for me.  Closing this out unless someone else wants to reopen it....
