### ISSUE TITLE
Multiple language support

### ISSUE THREAD

**Issue by Spreadcat** [GothenburgBitFactory/timewarrior#401]
Would it be possible to add language support for languages other than english?
I'm working up to three languages simultaneously and I find myself using f.eks. values for "due:" in other languages than english - which ofc. fails.
I could probably just recompile timewarrior after updating the `DateTimeParser.cpp`, but that would:

1. lock me still into only one language
2. not fix the problem for anybody else
3. make an upgrade harder.

While I cannot provide a PR in C for the necessary adjustments (simply because I cannot write C), I can certainly help with translations.

What it the general status quo on a multi-language support?

**Comment by lauft** [comment]
Currently internationalzation/localization is not on the agena.

It is not completely ruled out, but it has to be done right (see also issue #215). I haven't analyzed the issue in depth, but I think apart from delivering localized output messages, the parsing of localized input might pose the biggest hurdle in all of this.

**Comment by Spreadcat** [comment]
Yes, I can see your point. I can also see the point of the other commentator in #215 . I'm not saying that the application is only available in english is a show-stopper for me, quite the contrary. But: You might have at least some people at hand to outsource the translations and get some help from there - me included.
