### ISSUE TITLE
New DateTime literal "earlier"/"before"

### ISSUE THREAD

**Issue by quazgar** [GothenburgBitFactory/timewarrior#407]
Similarly to "later"/"someday", I suggest an new literal "earlier"/"before" for a time way in the past. See the PR below. (I also created one for libshared, is that necessary?)

**Comment by lauft** [comment]
Currently everything that affects `DatetimeParser` will need a corresponding change in `Datetime` in `libshared`. In the long term, `DatetimeParser` should be transferred to `libshared` and the date parsing should be migrated from `Datetime` to `DatetimeParser` altogether.

**Comment by tbabej** [comment]
While I do not see a huge problem with this proposal, the use case is not fully fleshed out in my mind. @quazgar  Could you draft an example (ideally couple of bash lines) of how this would be used in an useful manner? What modes of operation does it enable?

**Comment by quazgar** [comment]
Maybe I am missing an important bit of the syntax, but so far I cannot see a way to define a time range which begins infinitely long ago. For example if I want to find out when time was spent doing `sometag`:

```sh
timew summary sometag             # for today
timew summary sometag soy - later # since the start of the year until end of time
timew summary sometag earlier     # since the beginning of time
timew summary sometag before to yesterday
```

An alternative way to do this would also be welcome, I could also write the documentation for that.

**Comment by lauft** [comment]
Instead of `timew summary TAG earlier` you could use `timew summary TAG :all`... 🤔

**Comment by quazgar** [comment]
Indeed I did not know about `:all` and added documentation about it to the man pages.

**Comment by quazgar** [comment]
I added a bit more information to the man page to explain this choice.

**Comment by lauft** [comment]
After thinking about the topic a long time (see https://github.com/GothenburgBitFactory/timewarrior/pull/408#issuecomment-859332788) I think it would be better, if Timewarrior would support date range constructs like
```
timew ... until/before <datetime>
timew ... since/after <datetime>
```
with this Timewarrior can be used with
```
timew summary since :yesterday
```
instead of
```
timew summary before to yesterday
```
