### ISSUE TITLE
Summary by tag?

### ISSUE THREAD

**Issue by esbenboye** [GothenburgBitFactory/timewarrior#413]
During the day, I work on several tasks (using task name as tag) and sometimes I have multiple entries under the same tag, e.g. if I'm working on something before and after a break or a meeting. 

At the end of the day, I want to report my time to our time tracking system, but I manually have to find and sum up the tags (using the summary function). 

This can be a bit of a hassle, so I was wondering if it is possible to sum a day (or a period) by tag name and the sum of time spent?

**Comment by sskras** [comment]
For me it just works. Let's say I have following tags:
```
$ tw su

Wk Date       Day ID Tags          Start     End    Time   Total
W9 2021-03-04 Thu @4 PROJ1, tag1 0:01:00 0:02:00 0:01:00
                  @3 PROJ1, tag2 0:02:00 0:12:00 0:10:00
                  @2 PROJ2, tag3 0:13:00 0:33:00 0:20:00
                  @1 PROJ2, tag4 0:34:00 0:44:00 0:10:00 0:41:00

                                                         0:41:00
```
Then I can easily get summaries by a single tag:
```
$ timew summ :id PROJ1

Wk Date       Day ID Tags          Start     End    Time   Total
W9 2021-03-04 Thu @4 PROJ1, tag1 0:01:00 0:02:00 0:01:00
                  @3 PROJ1, tag2 0:02:00 0:12:00 0:10:00 0:11:00

                                                         0:11:00

$ timew summ :id PROJ2

Wk Date       Day ID Tags          Start     End    Time   Total
W9 2021-03-04 Thu @2 PROJ2, tag3 0:13:00 0:33:00 0:20:00
                  @1 PROJ2, tag4 0:34:00 0:44:00 0:10:00 0:30:00

                                                         0:30:00
```

What I am unable achieve is generating summary by several tags at once:
```
$ timew summ :id PROJ2 PROJ1
No filtered data found in the range 2021-03-04T00:00:00 - 2021-03-05T00:00:00 tagged with PROJ1, PROJ2.
```
Not sure which case do you mean.

**Comment by lauft** [comment]
Unfortunately tag filtering is currently limited to `AND` (to make this more flexible is planned).

As @sskras suggested, you could give all your work related tasks the same tag, along with the task name, and then use the `summary` command to get the total:
```
$ timew track WORK TASK1 9:00 - 10:00
$ timew track COFFEE 10:00 - 10:15
$ timew track WORK TASK2 10:15 - 12:00
$ timew track LUNCH 12:00 - 12:30
$ timew track WORK TASK1 12:30 - 18:00

...
$ timew summary WORK
Wk Date       Day Tags           Start      End    Time   Total
W9 2021-03-04 Thu TASK1, WORK  9:00:00 10:00:00 1:00:00
                  TASK2, WORK 10:15:00 12:00:00 1:45:00
                  TASK1, WORK 12:30:00 18:00:00 5:30:00 8:15:00

                                                        8:15:00

```

**Comment by esbenboye** [comment]
@sskras 
Thank you for this - It has helped me a lot to be able to at least be able to summarize by a single tag at a time. 

@lauft 
> to make this more flexible is planned

Sounds good - I will look forward to this :)

I think I have gotten what I came for, so I will close this.

**Comment by astr0gator** [comment]
It's very old issue, is there any way to achieve the result in a current version of timewarrior?
The intentions is the same: group `timew summary` by taskwarrior project
