### ISSUE TITLE
timewarrior /doc/* entries not established on install (linuxbrew)

### ISSUE THREAD

**Issue by G-S-Paris** [GothenburgBitFactory/timewarrior#414]
Hi all,

I have reason to believe that timewarrior did not install the /doc/* entries upon 'brew install timew' (linuxbrew).
before I declare this a real issue, can someone give me steps to try and recreate this part of the install process? C++ / builds are not an area of experience for me, so guidance would be appreciated. I have a feeling this could either be due to permissions for /usr/ on the system I working with, or it could be linuxbrew related.  I've checked /usr/local/share and /usr/share, done a fair share of filename grepping and ran diagnostics on both time and task - if its installed in a different location I can't quite tell where; ideas appreciated. 

For context, I came across the missing paths/entries when I was looking for the on-modify for taskwarrior integration. 

I will be happy to provide any further information / clarify as needed, and I'm also willing to "turn it off / turn it back on again" and double check anything I've already tried.

**Comment by lauft** [comment]
Hello!

What system are you using?

You could take a look at the linuxbrew output and see what it reports on what is installed where...
I am not sure how linuxbrew works (from a quick lookup I saw that it is now integrated in homebrew), but I did not find any linux specific stuff in the formula. The macOS bottles do contain the file `timew/ext/on-modify.timewarrior`...

**Comment by G-S-Paris** [comment]
Thank you for the suggestion, and apologies for my delay! 
From your advice I was able to find the file here `~/.linuxbrew/Cellar/timewarrior/1.4.2/share/doc/timew/ext/on-modify.timewarrior`. 

FWIW I'm a user on a debian setup that I don't control
