### ISSUE TITLE
Broken links inside man page

### ISSUE THREAD

**Issue by draupadi77** [GothenburgBitFactory/timewarrior#419]
The links inside the man page are broken.
Sections:
- DESCRIPTION: https://taskwarrior.org/docs/timewarrior
- REPORTING BUGS: https://github.com/Gothenburg‐BitFactory/timewarrior/issues (hyphen on linebreak/nl, depends on terminal size)

**Comment by lauft** [comment]
@draupadi77 Thanks for reporting. Can you please report how to reproduce the error?

- If you call the man page from the terminal, which version of Timewarrior are you using? Which man pages are affected?
- If you found it on the website, what is the URL?

**Comment by draupadi77** [comment]
Yes, I can.
OS:
- Kubuntu 20.10
timewarrior package:
- from default kubuntu repository
- 1.3.0+ds.1-1 amd64 feature-rich time tracking utility

Link inside DESCRIPTION: is wrong at all.

Link inside REPORTING BUGS:
Reproduce:
- open terminal ("Kosole")
- resize to 70 columns
- `man timew`
- scroll to bottom

(I'll try to insert a screenshot:)
![Screenshot_20210422_103346](https://user-images.githubusercontent.com/14162206/115684525-b939fe80-a357-11eb-9512-b8050ebc16cb.png)

Pleas tell me, if you need more information.

Best regards,
  Christoph

**Comment by draupadi77** [comment]
Whoops, on 70 columns the link inside FURTHER DOCUMENTATION is modified. But the behaviour is the same for REAPORTING BUGS. Just play around with the amount of columns.
Best regards,
  Christoph

**Comment by lauft** [comment]
The current version of Timewarrior is `1.4.2`. Is it possible for you to upgrade?

**Comment by draupadi77** [comment]
I have just discovered the package list of kubuntu 21.04 (hirsute hippo), but it's not stable by now. It contains the current version of timewarrior:
- timewarrior (1.4.2+ds.1-3ubuntu1) [universe] feature-rich time tracking utility
I will upgrade kubuntu once it there is a stable release.

Because I don't like to twist the apt-repositories, I would not like to upgrade by hand.
If you want me to test version 1.4.2, I will do so inside virtual machine, but this will take some time.

**Comment by lauft** [comment]
The wrong link to the docs in the description has been fixed in 90081afb9783151c27006113c283434cb9980771, which is included in `1.4.2`.

The issue with the line break in the link will need some further investigation. Especially as we switched to Asciidoctor for generating the man pages. We need to find out how/whether we can preserve links here.

**Comment by lauft** [comment]
With the switch to Asciidoctor generated man pages links are preserved in man pages.
This will be then included in the next release.
