### ISSUE TITLE
[TI-37] No warning about new tags

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#42]
_Michael Meier on 2016-08-21T16:38:51Z says:_ 

 There is no longer any warning displayed when a new tag is used.

Example: 

```
timew start "A test" testing
Tracking "A test" testing
  Started 2016-08-21T18:26:23
  Current                  23
  Total               0:00:00
```
Expected:

```
timew start "A test" testing
Tracking "A test" testing
  Started 2016-08-21T18:26:23
  Current                  23
  Total               0:00:00
New tags: "A test", testing added
```
It seems the feature got lost somewhere between the resolution of Issue TI-14 and the release.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-08-21T16:38:51Z
Modified: 2018-01-13T08:52:26Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-08-21T17:44:40Z says:_ 

 Feature was temporarily disabled.  It was triggering too often, and the fix is a bigger change than I wanted to make, post-beta.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-05-21T17:02:10Z says:_ 

 This was triggered too often because the low-level data update code implements 'update' as a 'delete' followed by an 'add'.  This means that a tag that is only used once is always generating the warning about it being a new tag, on update.  This is wrong.  Moving to backlog.

**Comment by lauft** [comment]
I am closing everything related to this topic except for #2. Further discussion should take place there.
