### ISSUE TITLE
Improve documentation of named dates

### ISSUE THREAD

**Issue by khaeru** [GothenburgBitFactory/timewarrior#421]
I'd like to show all intervals from 3 days ago until the current time, without typing the exact date.

`timew summary 3d` shows this range but does not show intervals in the current day (i.e. started after 00:00 of the current day).

`timew help` shows:
```
Usage: timew [--version]
       …
       timew summary [<interval>] [<tag> ...]
…
Interval:
       [from] <date>
       [from] <date> to/- <date>
       [from] <date> for <duration>
       <duration> before/after <date>
       <duration> ago
       [for] <duration>
```

So (without typing the entire date), only the last 3 options allow to specify without mentally computing and typing the specific start datetime. None of these shows tracked intervals in the current day:
```
$ timew summary 3d before now
$ timew summary 3d ago
$ timew summary for 3d
```
(So “now” apparently means “the start of the current day,” and not “the current time”.)

The following *does* show intervals in the current day, but is (a) verbose and (b) unintuitive:
```
$ timew summary 3d before tomorrow
```

Perhaps there's an easy way to do this but—having read the help text and tutorial several times—I haven't been able to see it. If so, I'd request an example added to the documentation to make this clearer.

**Comment by lauft** [comment]
With Timewarrior 1.4.3, I can only confirm the non-intuitive behavior for `3d before today`.
Creating the following intervals on Mon Jan 16 22:21:00 CET 2023:
```
$ timew track 20230115T0800 - 20230115T1200 FOO
$ timew track 20230116T200000 - 20230116T210000 BAR
$ timew track 20230116T210000 BAZ
```
`timew summary 3d before now` then yields
```
Wk Date       Day Tags    Start      End    Time   Total
W2 2023-01-15 Sun FOO   8:00:00 12:00:00 4:00:00 4:00:00
W3 2023-01-16 Mon BAR  20:00:00 21:00:00 1:00:00
                  BAZ  21:00:00        - 1:19:39 2:19:39
                                                        
                                                 6:19:39
```
which includes all intervals of the current day.
In contrast to this `timew summary 3d before today` yields only yesterday's interval:
```
Wk Date       Day Tags   Start      End    Time   Total
W2 2023-01-15 Sun FOO  8:00:00 12:00:00 4:00:00 4:00:00
                                                       
                                                4:00:00
```
because `today` is defined as _start of current day_, independent of whether it is used as start of or end of a range (see also #267).
