### ISSUE TITLE
The Get command does not produce the correct information about tags

### ISSUE THREAD

**Issue by grovesteyn** [GothenburgBitFactory/timewarrior#427]
For instance: `timew get dom.tracked.2.tag.1` produces the first tag from @1, not from @2
`get dom.tracked.3.tag.1` produces the first tag from @1 not from @3
while `get dom.tracked.3.tag.2` produces the second tag from @2, not from @3

This appears to be wrong?

**Comment by lauft** [comment]
Hello @grovesteyn!

What version of Timewarrior are you using? This issue should be resolved with `1.4.3` with https://github.com/GothenburgBitFactory/timewarrior/commit/5b1deaab5954aa93e7b51d8208988f06087d5ce2
(see #390)

**Comment by grovesteyn** [comment]
Using 1.4.2  will update and check.

**Comment by grovesteyn** [comment]
Problem solved.
