### ISSUE TITLE
Add Sync Capability

### ISSUE THREAD

**Issue by OmarMohamedKhallaf** [GothenburgBitFactory/timewarrior#428]
Taskwarrior has Taskserver which syncs tasks and auto-merges them. Why isn't this supported by timewarrior.

**Comment by lauft** [comment]
In short: Syncing involves a lot of effort to support and maintain it which unfortunately I do not have the time and capacity for.

Luckily the folks of [Timewarrior Synchronize](https://github.com/timewarrior-synchronize) do, so you may want to try their tools:
* https://github.com/timewarrior-synchronize/timew-sync-server
* https://github.com/timewarrior-synchronize/timew-sync-client
