### ISSUE TITLE
Timew track start - end `n` fails to link to taskwarrior tasks

### ISSUE THREAD

**Issue by Robinlovelace** [GothenburgBitFactory/timewarrior#438]
A typical usage of timewarrior is 

```bash
task add 'some task' # becomes number 17
task start 17
# ...
task stop 17
```

If you forget to start at the right time, it's useful to track the time historically.
Unfortunately this fails:

```
timew track 08:00 - 08:45 17
```

I've searched the documentation for a solution but cannot find it so suspect this is a bug. Am I missing something?

**Comment by lauft** [comment]
@Robinlovelace To debug this, it would be helpful to know whether you have the hook on-modified.timewarrior installed (and what versions of `task` and `timew` you use) and how your mentioned command fails, i.e. the console output.

If the hook is present, it should have created a interval associated with your task via tags. Can you check this? What is the output of `timew sum` after you have started task `17`?

**Comment by Robinlovelace** [comment]
> What is the output of `timew sum` after you have started task `17`?

I get this:

```
➜ task 17 start 
Starting task 4bb561e8 'Slides for 3pm with Jack'.
Started 1 task.
Note: '"Slides for 3pm with Jack"' is a new tag.
Tracking "Slides for 3pm with Jack"
  Started 2021-07-13T12:31:23
  Current                  23
  Total               0:00:00

~ via ⬢ v10.19.0 
➜ timew sum             

Wk  Date       Day Tags                        Start End    Time   Total
W28 2021-07-13 Tue Slides for 3pm with Jack 12:31:23   - 0:00:07 0:00:07
                                                                        
                                                                 0:00:07

```

**Comment by Robinlovelace** [comment]
I'm running these versions:

```
➜ timew --version
1.2.0

~ via ⬢ v10.19.0 
➜ task --version 
2.5.1

```

**Comment by lauft** [comment]
@Robinlovelace 
Sorry, I forgot to mention to add the `:ids` hint to the `timew sum` command. With that you get the id you can use to modify your interval.

### Solution for your problem
Let's assume `timew sum :ids` gives you this output:
```
➜ timew sum :ids            

Wk  Date       Day ID Tags                        Start End    Time   Total
W28 2021-07-13 @1 Tue Slides for 3pm with Jack 12:31:23   - 0:00:07 0:00:07
                                                                        
                                                                 0:00:07
```
Then you can correct the time of your interval e.g. by moving it to the right time with `timew move`:
```
➜ timew move @1 08:00
```
This will move your interval to the start time `08:00` while leaving its length untouched. To change this you could either do
```
➜ timew resize @1 1min
```
or
```
➜ timew modify end 08:01
```

### Some explanations
**Timewarrior and Taskwarrior do not share a common database.** This also means that they reference their respective data in a different way and those references cannot be shared. As you have seen, Timewarrior treats the Taskwarrior reference to task `17` as a tag. To reference the corresponding interval in Timewarrior, you need to look it up with `timew sum :ids`. Also, Timewarrior requires ids to be prefixed with `@`.

**Ids in Timewarrior change.** In Timewarrior, intervals are assigned an id by counting from the most recent interval (which always has id `@1`). This means when you refer to an interval `@X` and add two intervals, the id of this interval shifts by `2` (to `@(X+2)`).

I hope this makes above a bit clearer. Let me know if you have further questions.

### P.S.
Your version of Timewarrior (and Taskwarrior) seems a bit outdated (current Timewarrior is `1.4.3`), so you might consider an upgrade.

**Comment by Robinlovelace** [comment]
Thanks for the explanations. I now see:

```
➜ timew sum :ids                    

Wk  Date       Day ID Tags                        Start      End    Time   Total
W28 2021-07-13 Tue @4 17                        8:00:00  8:01:00 0:01:00
                   @3                           8:02:00  8:03:00 0:01:00
                   @2 ids:                      8:03:00  8:04:00 0:01:00
                   @1 Slides for 3pm with Jack 12:31:23 12:32:44 0:01:21 0:04:21
                                                                                
                                                                         0:04:21

```

Ass you can see my attempts to add a new historic work track have not yet been successful. I tried:

```bash
timew track 08:04 - 08:05 @1 

# which generates this message
Recorded 
  Started 2021-07-13T08:04:00
  Ended                 05:00
  Total               0:01:00

# and seems to have added this line, not the one I wanted:

                   @2                           8:04:00  8:05:00 0:01:00
                   @1 Slides for 3pm with Jack 12:31:23 12:32:44 0:01:21 0:05:21


```

How would I now add an entry for `@1` that starts at 08:05 and ends at 08:06?

Apologies again if I've missed something and happy to upgrade if there's a quick fix in recent versions.

**Comment by lauft** [comment]
Do you want to _modify the existing interval_ or _create a new interval_?
You cannot use the `track` command to modify an existing interval, it is meant to create new intervals.

When you enter
```
timew track 08:04 - 08:05 @1 
```
Timewarrior simply ignores the interval id and enters a new interval with the given tags (here: none) into the database (I have created #439 to address this).

If you want to adjust the interval with the current id `@1`, then use the `move` command as shown above:
```
$ timew move @1 08:05
```
Afterwards you can adjust the end date with `timew modify end @1 08:06` if necessary.

If you want to _add_ a new interval with the same tags as the one referenced by `@1` in your example, you can use `track` like this:
```
$ timew track 08:00 - 08:06 "Slides for 3pm with Jack"
```
(The quotes are necessary, otherwise Timewarrior will add 5 tags (`Slides`, `for`, `3pm`, `with`, and `Jack`) instead of one.)

**Comment by Robinlovelace** [comment]
> Afterwards you can adjust the end date with `timew modify end @1 08:06` if necessary.
> 
> If you want to _add_ a new interval with the same tags as the one referenced by `@1` in your example, you can use `track` like this:
> 
> ```
> $ timew track 08:00 - 08:06 "Slides for 3pm with Jack"
> ```

That is good to know but won't important info like the project the task is part of (imagine that the slides for Jack were part of a project that I was logging hours on) be lost that way?

See reproducible example to show what I mean below.

<details>

```
➜ task add 'task1' pro:pro1 
Created task 18.
The project 'pro1' has changed.  Project 'pro1' is 0% complete (1 task remaining).

~ via ⬢ v10.19.0 
➜ task start 18            
Starting task f2d92ea7 'task1'.
Started 1 task.
Note: 'pro1' is a new tag.
Note: 'task1' is a new tag.
Tracking pro1 task1
  Started 2021-07-13T22:29:41
  Current                  41
  Total               0:00:00
You have more urgent tasks.
Project 'pro1' is 0% complete (1 task remaining).

~ via ⬢ v10.19.0 
➜ task stop 18 
Stopping task f2d92ea7 'task1'.
Stopped 1 task.
Recorded pro1 task1
  Started 2021-07-13T22:29:41
  Ended                    56
  Total               0:00:15
Project 'pro1' is 0% complete (1 task remaining).

~ via ⬢ v10.19.0 
➜ timew track 08:08 - 08:09 "task1"
Recorded task1
  Started 2021-07-13T08:08:00
  Ended                 09:00
  Total               0:01:00

~ via ⬢ v10.19.0 
➜ timew summary pro1               

Wk  Date       Day Tags           Start      End    Time   Total
W28 2021-07-13 Tue pro1, task1 22:29:41 22:29:56 0:00:15 0:00:15
                                                                
                                                         0:00:15


~ via ⬢ v10.19.0 
➜ timew summary task1

Wk  Date       Day Tags           Start      End    Time   Total
W28 2021-07-13 Tue task1        8:08:00  8:09:00 0:01:00
                   pro1, task1 22:29:41 22:29:56 0:00:15 0:01:15
                                                                
                                                         0:01:15

```

**Comment by lauft** [comment]
> That is good to know but will important info like the project the task is part of (imagine that the slides for Jack were part of a project that I was logging hours on) be lost that way?

Well, if you want to _create_ an interval in the same way as the hook, you need to create it with all the required information.

I am starting to get a bit confused about your use case and what you want to achieve.

From your first post I get
* You start a task (after you have already started working on it) (_hook creates an interval with wrong start date_)
* You stop a task (_hook stops interval at given time_)
* You want to correct the time tracked

The last step can be accoomplished by using e.g. `move`, `resize`, `modify` as described above on the _existing_ interval. So there is no need to use `track` here (and `track` is not meant to be used to modify existing intervals)

Do you want to keep the original (incorrect) interval for some reason?

**Comment by Robinlovelace** [comment]
> Do you want to keep the original (incorrect) interval for some reason?

Yes. The original interval was not incorrect. I'm thinking of use cases where you want to add an additional period of working on a task that is in the TaskWarrior database without having to retype, word for word, the title and other tags of the task.

**Comment by lauft** [comment]
If you want to add a copy of an existing interval from 08:05 to 08:06, you may use the `continue` command with a range:
Find the respective id with `timew sum :ids` and call
```
timew cont @<id> 08:05 - 08:06
```
Please consult the command reference for more information on the `continue` command: https://timewarrior.net/reference/timew-continue.1/

**Comment by Robinlovelace** [comment]
Hi @lauft and thanks for your suggestion, really appreciated, that solution looks ideal. Unfortunately it's generating a core dump in my use case. Can you reproduce this behaviour? Happy to upgrade to the latest version of `timew` to test it there, is there a ppa to get the latest version and updates on Ubuntu 20.04?

Reproducible example:

```
➜ timew sum :ids

Wk  Date       Day ID Tags                                   Start End    Time   Total
W28 2021-07-14 Wed @1 Reply to Fred re data, atum.spshared 9:50:52   - 3:51:02 3:51:02
                                                                                      
                                                                               3:51:02


~ via ⬢ v10.19.0 
➜ timew continue @1 08:00 - 09:00

timew: /build/timew-0tjuIQ/timew-1.2.0/src/Range.cpp:359: time_t Range::total() const: Assertion `is_open () || end >= start' failed.
[1]    2777529 abort (core dumped)  timew continue @1 08:00 - 09:00

~ via ⬢ v10.19.0 
➜ timew sum :ids                 

Wk  Date       Day ID Tags                                   Start End    Time   Total
W28 2021-07-14 Wed @1 Reply to Fred re data, atum.spshared 9:50:52   - 3:51:53 3:51:53
                                                                                      
                                                                               3:51:53

```

**Comment by lauft** [comment]
I can confirm this behaviour for version `1.2.0`, it seems to be connected with the open interval. If you stop time tracking before calling the `continue` command, it works. This issue does not occur in `1.4.3`.

> is there a ppa to get the latest version and updates on Ubuntu 20.04?

Not to my knowledge, but packages are the responsibility of the respective maintainers. Maybe the [Ubuntu MOTU Developers](mailto:ubuntu-motu@lists.ubuntu.com) mailling list can help you here.

**Comment by Robinlovelace** [comment]
> If you stop time tracking before calling the `continue` command, it works.

Confirmed that works. Great fix! Regarding the original post, could I make this issue into a feature request: to make 

```
timew track 08:00 - 08:45 @1
```

Work? Seems that's covered in #439 .

Overall, many thanks for the replies, it's been very helpful for me and I'm happy to provide more feedback if that would be useful.
