### ISSUE TITLE
Summary of a tag with hint `:all` ignore current day

### ISSUE THREAD

**Issue by gilles-crealp** [GothenburgBitFactory/timewarrior#440]
When you try to get a summary of a tag with the hint `:all`, the current day is ignored.

- `timew summary :all` show every intervals, including current day.
- `timew summary <tag>` show every tag's intervals for the current day.
- `timew summary <tag> :all` show every tag's intervals except for the current day.

Shouldn't `timew summary <tag> :all` shows also current day, like `:year`, `:week`, etc.?

TimeWarrior version 1.4.2.

**Comment by sruffell** [comment]
I believe this may be fixed in 1.4.3 by commit https://github.com/GothenburgBitFactory/timewarrior/commit/ae5e44c558193a35a1c63e81aadd84273108acf6. Are you able to update to the latest release and retest?

**Comment by gilles-crealp** [comment]
You're right it's working in 1.4.3.
