### ISSUE TITLE
Improve documentation on annotations

### ISSUE THREAD

**Issue by sruffell** [GothenburgBitFactory/timewarrior#444]
Question was asked in discussions, but I didn't find any description on the :annotations hint in the man pages. Also, the [timew-annotate](https://github.com/GothenburgBitFactory/timewarrior/blob/dev/doc/man1/timew-annotate.1.adoc) manpage probably should contain a note about how to read the annotations.

### Discussed in https://github.com/GothenburgBitFactory/timewarrior/discussions/443

<div type='discussions-op-text'>

<sup>Originally posted by **apkawel** August  3, 2021</sup>
Is there an easy way to generate a list of intervals that also shows their annotations? I undestand how to add annotations, but I don't know how to view/retrieve them. Thanks!</div>

**Comment by silvio** [comment]
Can be closed, because this is already documented in 1a6d5cacca75a284d4f0d033b81a03c6fb0f72bf ("Make summary output configurable via rules" / @lauft ).
