### ISSUE TITLE
timew exits with 'Error: expected '{' or '[' at position 0' on corrupted file

### ISSUE THREAD

**Issue by emilianbold** [GothenburgBitFactory/timewarrior#446]
After a power failure `timew` couldn't start anymore and just failed with 'Error: expected '{' or '[' at position 0'.

It would be helpful if `timew` would at least point towards the file that is broken.

Luckily I could run `strace timew` and see which file might it be and just removed `tags.data`:

```
openat(AT_FDCWD, "/home/work/.timewarrior/data/tags.data", O_RDONLY) = 3
read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 8191) = 43
```

```shell
$ timew --version
1.2.0
```

**Comment by sruffell** [comment]
I would strongly suggest updating to a more recent version of timewarrior.  Besides changes that shorten the time that the database is consistent, the tags database is recreated automatically if parsing ever fails (https://github.com/GothenburgBitFactory/timewarrior/commit/4798e6f26bcc08f0f80b60f53f16766f88073df8).


The current release is v1.4.3.

**Comment by emilianbold** [comment]
Honestly, I didn't pick a given version. I'm on Ubuntu 20.04 LTS (a rather recent OS) and this it what it packages: https://packages.ubuntu.com/search?keywords=timewarrior

```
focal (20.04LTS) (utils): feature-rich time tracking utility [universe]
1.2.0-2: amd64 arm64 armhf ppc64el s390x 
```

**Comment by sruffell** [comment]
Hmm... if you could build from source that would be great. Maybe in the next few weeks I can investigate what it would take to feed new release updates into the Ubuntu repos. I personally do not have any experience with that.

**Comment by lauft** [comment]
I asked a question on the Ubuntu launchpad 👉🏻 https://answers.launchpad.net/ubuntu/+source/timew/+question/698568, otherwise we might need to bug the maintainers directly via mail: ubuntu-motu@lists.ubuntu.com

**Comment by lauft** [comment]
@emilianbold you could install the following PPA to get the recent version of Timewarrior: https://launchpad.net/~chronitis/+archive/ubuntu/misc

Otherwise it seems Ubuntu has the concept of "no rolling release" (👉🏻 https://answers.launchpad.net/ubuntu/+faq/3037) which means the versions of the provided packages stay the same.
