### ISSUE TITLE
Man pages not installed with out-of-source build in 1.4.3

### ISSUE THREAD

**Issue by swills** [GothenburgBitFactory/timewarrior#461]
Building 1.4.3 from source and installing, I see that if I use an out of source cmake build, the man pages do not get installed properly. They do get installed if I use an in-source build. Didn't have this issue with 1.4.2.

Also, it seems that there is an empty directory named CMakeFiles installed in the `man/man1` and `man/man7` directories, for both out of source and in-source builds.

**Comment by lauft** [comment]
> ...the man pages do not get installed properly

@swills can you specify how? Missing files? Wrong directory?

**Comment by swills** [comment]
Sorry, should have said, they man pages are not installed. There's the empty CMakeFiles directory, but no man pages.

**Comment by tbabej** [comment]
Is it possible this would occur due to missing `asciidoctor`?

**Comment by swills** [comment]
I don't think so, I had asciidoctor installed. What fixed it was switching from out of source build to in source.

**Comment by lauft** [comment]
Currently, I do not see much need to change to/support out-of-source builds (PRs fixing this are of course welcome). I am therefore closing this issue.
