### ISSUE TITLE
Question: Pointers on converting data to from other system to timewarrior format

### ISSUE THREAD

**Issue by oivvio** [GothenburgBitFactory/timewarrior#475]
Hi!
I'm thinking about scrapping the time tracking script I've been using for 10+ years. It's a python thing that started very simple and has grown into a mess. Before jumping ship I want to to try out generating timewarrior reports on my old data. The files in `~/.timewarrior` look simple enough. It's one file per month. The tags.data file is a json structure with a count for each tag. The undo.data file looks tricker. Will timewarrior get confused if it is missing?

**Comment by lauft** [comment]
Hi @oivvio!

You can omit both `tags.data` and `undo.data`.

The former is automatically generated if missing, the latter is only required if you want to undo Timewarrior commands which is probably not the case with your import.

So simply focus on generating the monthly data files. The format for closed intervals is
```
inc <start time UTC> - <end time UTC> # <tag>... # <annotation>
```
Tags are in between separated by spaces, thus a tag has to be quoted if it contains spaces itself.
The annotation is always last, separated by a `#` from the tag set, i.e. two `#` if the interval has no tags.
e.g.
```
inc 20220205T080000Z - 20220205T110000Z # FOO  BAR # Annotation
inc 20220205T080000Z - 20220205T110000Z # FOO BAR
inc 20220205T080000Z - 20220205T110000Z # # Annotation 
inc 20220205T080000Z - 20220205T110000Z
```

**Comment by lauft** [comment]
Instead of generating the files directly, you might also try to call `timew track <from> - <to> <tag>...` to generate those entries programmatically. However, annotations have to be added in a separate step then.
```
timew track <from> - <to> <tag>...
timew annotate @1 <annotation>
```
Note: `@1` always refers to the latest interval in the database, so you also have to add the intervals in chronological order (from past to present).

**Comment by oivvio** [comment]
Thanks! This worked like a charm. My script exported 10 years of data in 3 minutes. I got a bit tripped up by encoding errors, but that was unrealted to timewarrior. timewarrior seems to be handling it without breaking a sweat. The built in reports are not exactly what I need, but I'll cook something up in combination with your excellent json export feature.

**Comment by lauft** [comment]
> Thanks! This worked like a charm. 

❤️ 

> The built in reports are not exactly what I need, but I'll cook something up in combination with your excellent json export feature.

In case you haven't already found:
👉🏻 https://timewarrior.net/docs/api/
👉🏻 https://github.com/lauft/timew-report

**Comment by oivvio** [comment]
Thanks. timew-report is very helpful!
