### ISSUE TITLE
Add configurable default range for reports

### ISSUE THREAD

**Issue by oivvio** [GothenburgBitFactory/timewarrior#477]
I just started using timewarrior and the first thing I did was import 10+ years of data from my old home grown time tracking system.

I'd like to be able to set a default time range that is used if no other range is given. That way my extensions could default to looking at say the last 6 months of data instead of looking at everything I ever done.

`timew summary` defaults to :day but I can't find I way to override that or set a default for other operations.

**Comment by lauft** [comment]
Duplicate of #394
