### ISSUE TITLE
corupted database after disk full

### ISSUE THREAD

**Issue by jhrcz** [GothenburgBitFactory/timewarrior#480]
it looks like after filling my disk (no space left on device) tags data got corrupted. in fact this file is now zero size. and every timew command ends with error:
```
Error: expected '{' or '[' at position 0
```
quick fix to see current summary is to place `{}` `tags.data`. but then the modification commands and stop command quit with error
```
Trying to decrement non-existent tag 'xxxxxxxx'
```

**Comment by jhrcz** [comment]
@lauft  thank you. this solved the the problem.

i'm using 1.2.0 as is in distro i currently use.

**Comment by lauft** [comment]
> i'm using 1.2.0 as is in distro i currently use.

You might want to try to update to the current version. We have implemented some measures which prevent database corruption in case of Timewarrior is unable to write to disk.

**Comment by sruffell** [comment]
Linking to #155
