### ISSUE TITLE
Make it easier to use the Track command

### ISSUE THREAD

**Issue by grovesteyn** [GothenburgBitFactory/timewarrior#481]
Currently track only allows for limited formats which are slow to enter.
See: [https://timewarrior.net/docs/track/](url).  If you want to log a time slot on a specific time interval on a previous day the full "extended-date T extended-time" specification has to be typed in.

It would assist if it were possible to make entries such as these:

`timew track :yesterday 8am - 10am "My test task"`
or
`timew track :yesterday 8am for 1hr "My test task"`
or
`timew track monday 8am for 1hr "My test task"`

**Comment by grovesteyn** [comment]
Agreed. With #196 being the main one. 

Here is a very similar comment:
[https://github.com/GothenburgBitFactory/timewarrior/issues/196#issuecomment-638524238](url)

**Comment by lauft** [comment]
Closing this as the main discussion will take place in the issues referenced above.
