### ISSUE TITLE
can't install node@10 by brew install --build-from-source node@10

### ISSUE THREAD

**Issue by Dunmysad** [GothenburgBitFactory/timewarrior#486]
brew install --build-from-source node@10
Warning: node@10 has been deprecated because it is not supported upstream!
==> Downloading https://nodejs.org/dist/v10.24.1/node-v10.24.1.tar.xz
Already downloaded: /Users/lishihao/Library/Caches/Homebrew/downloads/ab91b4629ee86931680a7a470a20229aabc5ae2927713f28156225e7e1363db8--node-v10.24.1.tar.xz
==> ./configure --prefix=/opt/homebrew/Cellar/node@10/10.24.1_1 --with-intl=system-icu
Last 15 lines from /Users/lishihao/Library/Logs/Homebrew/node@10/01.configure:
2022-03-23 03:29:34 +0000

./configure
--prefix=/opt/homebrew/Cellar/node@10/10.24.1_1
--with-intl=system-icu

./configure: line 3: exec: python: not found

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
node: migrate to python@3.10 https://github.com/Homebrew/homebrew-core/pull/97458
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.

**Comment by tbabej** [comment]
I am not sure this was reported against correct repository. How does this occur wihen installing `timew`? The code base, as far as I know, has no javascript component :slightly_smiling_face:

**Comment by lauft** [comment]
I agree. @Dunmysad please check the issue tracker on `brew` (👉🏻 https://github.com/Homebrew/homebrew-core/issues) and open an issue there if necessary.
