### ISSUE TITLE
on-modify.timewarrior missing from apt timewarrior package installation

### ISSUE THREAD

**Issue by savaged** [GothenburgBitFactory/timewarrior#488]
The docs at https://timewarrior.net/docs/taskwarrior/ describe copying the file on-modify.timewarrior to the ~/.task/hooks directory for Timewarrior integration. However, with the following environment the folder described as the source is missing.

Env:
OS: Ubuntu 21.10 x86_64
Apt package: timewarrior

Missing:
/usr/local/share/doc/timew/ext/on-modify.timewarrior

**Comment by lauft** [comment]
According to the [file listing of Ubuntu 21.10 (impish)](https://packages.ubuntu.com/impish/amd64/timewarrior/filelist), the hook is located under 
```
/usr/share/doc/timewarrior/ext/on-modify.timewarrior
```
Try this location.

**Comment by savaged** [comment]
There it is! Perhaps the docs need updating?

**Comment by lauft** [comment]
In the documentation it says on [line 16](https://github.com/GothenburgBitFactory/ti.net/blob/09342d91491ce393a7e20b7041f7d4c28aa4c7e8/content/docs/taskwarrior.md?plain=1#L16):
> Depending on your system and installation method, you might need to adjust the path you copy from.

One could move this line a bit further up and maybe replace the [specific path in the example](https://github.com/GothenburgBitFactory/ti.net/blob/09342d91491ce393a7e20b7041f7d4c28aa4c7e8/content/docs/taskwarrior.md?plain=1#L13) (line 14) with something more general like
```
    $ cp /path/to/on-modify.timewarrior ~/.task/hooks/
   ...
```

**Comment by lauft** [comment]
Updated documentation on website 👉🏻 [9e1343eb](https://github.com/GothenburgBitFactory/ti.net/commit/9e1343eb69f8b96102f3633167b422d097af6ab4)
