### ISSUE TITLE
First execution creates database regardless of confirmation response

### ISSUE THREAD

**Issue by RafDevX** [GothenburgBitFactory/timewarrior#489]
Timewarrior version: 1.4.3
OS: Arch Linux x86_64, Kernel 5.17.3-arch1-1
Python version: 3.10.4

The first time timewarrior is run, it prompts the user with `Create new database in /home/USER/.timewarrior? (yes/no)`. However, even if the user answers `no`, a `.timewarrior` folder is created in the specified location _(although the welcome message that would be displayed if the user had answered `yes` is not shown)_.

### Steps to reproduce:
1. `# pacman -S timew` (or distro alternative)
2. `$ ls ~/.timewarrior` **should error as no such folder exists**
3. `$ timew` **answer to prompt with `no`**
4. `$ ls ~/.timewarrior` **folder now exists, despite not being supposed to**
5. `$ timew` - no longer prompts the user to create a new database, as the folder already exists
6. `# pacman -Rnsu timew`

**Comment by lauft** [comment]
`~/.timewarrior` is emtpy, or does it contain any files/subfolders?

**Comment by RafDevX** [comment]
It's created with the same structure as if the response had been `yes`:

```
.timewarrior
├── data
│   ├── tags.data
├── extensions
└── timewarrior.cfg
```

**Comment by lauft** [comment]
Confirmed. Thanks for reporting! 👍🏻 

I guess nobody ever entered 'no' here before. 😅 
With the fix, Timewarrior will now exit with the error message "Initial setup aborted by user".
