### ISSUE TITLE
totals.py incorrectly reports There is no data in the database 

### ISSUE THREAD

**Issue by KingJulianS** [GothenburgBitFactory/timewarrior#496]
Timewarrior 1.4.2 
Debian GNU/Linux 11 (bullseye)
Python 3.9.2

Hi. 
I was working through your tutorial and installed totals.py as per the docs.

However, when I enter $ timew totals ,  it gives a message "There is no data in the database", even though there is test data in the system that I can see with  summary  :

`Wk  Date       Day Tags                       Start      End    Time   Total
W27 2022-07-09 Sat team_manco_meet         10:00:00 13:00:00 3:00:00
                   mf_platform_health_meet 21:26:46 21:26:59 0:00:13
                   mf_platform_health_meet 21:27:05 21:27:11 0:00:06
                   DR_weekly               21:27:28 21:27:31 0:00:03
                   issue, tracking         21:27:46 21:27:56 0:00:10
                   issue, tracking         21:29:50 21:29:57 0:00:07
                   new_test                23:25:25 23:25:34 0:00:09 3:00:48
                                                                            
                                                                     3:00:48
`
when I do tags I get the following, which I used to test with : 
`
Tag                     Description
DR_weekly
break away              -
issue                   -
mf_platform_health_meet -
new_test                -
team_lunch              -
team_lunch_2            -
team_manco_meet         -
test1                   -
tracking                -

`

**Comment by smemsh** [comment]
the script says there's a start and optional end (default now) date/time argument.  example:
```
timew totals `task calc now - 1 week`
```
it appears to also take timew time hints like `:week` and `:lastweek`

**Comment by KingJulianS** [comment]
Thank you, that works.
Where can I learn how-to help update the documentation to make this clear ? ,  in case there are other newbs like me ?

**Comment by lauft** [comment]
The documentation from the website is stored here 👉🏻 https://github.com/GothenburgBitFactory/ti.net

The tutorial you where referring to is this file: https://github.com/GothenburgBitFactory/ti.net/blob/master/content/docs/tutorial.md
