### ISSUE TITLE
Allow blank lines in time entry files

### ISSUE THREAD

**Issue by etcpasswd-dev** [GothenburgBitFactory/timewarrior#497]
Would it be possible to allow blank/empty lines in the time entry file? 

I use timewarrior daily for work. When my time entries get skewed from missing an entry / adding it late, I go look at the raw time entry file to locate the gap. By the end of the month, each time entry file is a wall of text. It would be helpful to be able to insert blank lines between weeks to make it easier to read.

**Comment by lauft** [comment]
You mean the database files (stored in `~/.timewarrior/data/*.data`)?

No, those are internal files that should not be manipulated directly. 

>It would be helpful to be able to insert blank lines between weeks to make it easier to read.

You can achieve such an output via a custom report, e.g. a script like the following:
```
import sys
from timewreport.parser import TimeWarriorParser

parser = TimeWarriorParser(sys.stdin)
previous_week = None

for interval in parser.get_intervals():
    line = ''
    current_week = interval.get_start().isocalendar()[1]

    if (previous_week != current_week):
      line += '\n'

    previous_week = current_week

    line += '{:W%V %Y-%m-%d %H:%M}'.format(interval.get_start())
    line += ' - {:%H:%M}'.format(interval.get_end()) if not interval.is_open() else ''
    line += ' {}'.format(", ".join(interval.get_tags()))

    print(line)

```
(see 👉🏻 https://pypi.org/project/timew-report/ for the timew-report Python package)

**Comment by etcpasswd-dev** [comment]
That will do nicely. Thank you for your time. Please close my issue.

-------- Original Message --------
