### ISSUE TITLE
Can't stop tasks

### ISSUE THREAD

**Issue by jsanz** [GothenburgBitFactory/timewarrior#498]
I have no idea how I get to this, but I cannot stop tasks in timewarrior, let me show an example where I start a clean day, start a task at `10:00`, check the summary, but then I can't stop it. I can only delete it.

![image](https://user-images.githubusercontent.com/188264/180188795-f70ee805-1cc8-4a93-ab2f-1c16835f77f7.png)

Is my entries database somehow corrupted? If I add again the same entry, this is how the `2022-07.data` file ends

![image](https://user-images.githubusercontent.com/188264/180189184-eace6f93-34c1-4689-bd22-f532143f9f2c.png)

One thing to note is that I can start a new task and the previous one will be closed accordingly. 

![image](https://user-images.githubusercontent.com/188264/180189877-01869fec-79e5-4283-ab4e-66ea0a6c0f13.png)

**Comment by sskras** [comment]
Is there some free space on your file system?  Eg. from MSYS2 (non-Linux) environment:
```
$ df -Th .timewarrior
Filesystem     Type  Size  Used Avail Use% Mounted on
C:/msys64      ntfs  238G  238G  174M 100% /
```

I remember something similar occurring when I run completely out of free space on my FS.

**Comment by jsanz** [comment]
> Is there some free space on your file system? Eg. from MSYS2 (non-Linux) environment:

I don't have space issues (I've already seen other issues here related to that). 

Thanks for chiming in!

**Comment by sskras** [comment]
For me it works on MSYS2:
![image](https://user-images.githubusercontent.com/7887758/180201897-23cbec9e-3554-4947-9093-38be8b90a7e2.png)

... and my version is `1.4.3-dev`, commit `8ba588dc`:

![image](https://user-images.githubusercontent.com/7887758/180201392-19ac556c-248e-472d-8a17-286bf0049024.png)

**Comment by jsanz** [comment]
Overriding the database location to start clean makes it work again.


<details><summary>Test a clean db</summary>

![image](https://user-images.githubusercontent.com/188264/180203929-1e20a246-9fb3-4e13-b925-1669fff37b5c.png)

</details>

If I only override the configuration file the error stays so should I assume that somehow my database is corrupted?

<details><summary>Configuration</summary>

```
➜ cat timewarrior.cfg
import /usr/share/doc/timewarrior/doc/themes/dark_green.theme

define exclusions:
  monday    = <10:00 >21:00
  tuesday   = <10:00 >21:00
  wednesday = <10:00 >21:00
  thursday  = <10:00 >21:00
  friday    = <10:00 >21:00
  saturday  = >0:00
  sunday    = >0:00

reports.day.lines=4

reports.week.cell=10
reports.week.hours=auto
reports.week.lines=2

reports.month.hours=auto
```

</details>

<details><summary>Version details</summary>

And I'm on `1.2.0`, installed from Ubuntu packages

![image](https://user-images.githubusercontent.com/188264/180204328-23bb3a78-8a33-4a49-9535-02c4184ed9c7.png)

</details>

**Comment by sruffell** [comment]
Just out of curiosity, do you have any exclusions configured?

**Comment by jsanz** [comment]
> Just out of curiosity, do you have any exclusions configured?

yes, I already passed them in my [previous comment](https://github.com/GothenburgBitFactory/timewarrior/issues/498#issuecomment-1191378900) in the `Configuration` details section. Removing them is not fixing the issue

![image](https://user-images.githubusercontent.com/188264/180231863-b7896504-1310-4558-8117-a9cd86bb811a.png)

**Comment by jsanz** [comment]
OK, I compiled and installed the last release, and the problem is not showing up, so I guess I should have started from there :sweat: 

Sorry for the noise, and thanks again for your time :raised_hands: 

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/188264/180234923-80e768b5-ed6a-4fea-9573-cecf228f17b6.png)

</details>

**Comment by sskras** [comment]
Well it was interesting to read.  Should I have some spare time, I would try to reproduce the error and then do regression testing:)
Not this time though.

**Comment by jsanz** [comment]
I think I finally understood the issue. When recovering extensions I saw in my `data` folder a file `1970-01.data` that had just a single line with this content

```
inc # review
```

No idea how this file got created 🤔 but removing it fixed the reporting extensions, and I can bet something that I could revert to the packaged version and it would also work as well.
