### ISSUE TITLE
timew summary from <datetime> reports error

### ISSUE THREAD

**Issue by iateadonut** [GothenburgBitFactory/timewarrior#501]
I'm looking to track time from yesterday at 9am.  Here's an attempt and the error message:

> timew summary from 2022-08-18T9:00:00 for 24h
Unrecognized date range: 'from for <duration>'.

**Comment by lauft** [comment]
Extended ISO datetime requires double-digit hours. This works:
```
timew summary from 2022-08-18T09:00:00 for 24h
```
