### ISSUE TITLE
report 'totals.py' does not truncate intervals to report range

### ISSUE THREAD

**Issue by eq0cdk** [GothenburgBitFactory/timewarrior#505]
When using 
`timew report totals.py :month/:day/:week`
Timewarrior essentially duplicates tracked time if the task continues into the next day. A task that was started before midnight, that continues into the next day will have its tracked time incremented in both today and yesterday's report at the same time, leading to an overestimation of time tracked.

For example, 
`timew report totals.py :yesterday`
shows "Work" as 2:50:00 and counting

while
`timew report totals.py :today`
shows "Work" as 1:00:00 and counting

---

One minute later,
`timew report totals.py :yesterday`
shows "Work" as 2:51:00 and counting

while
`timew report totals.py :today`
shows "Work" as 1:01:00 and counting

---

Both tasks in both yesterday and today's reports have their time incremented simultaneously. The same problem happens when using :week or :month. Basically, timew summary :month/day/week lists different individual/total tracked times from timew report totals.py.

The correct behavior would be to increment today's time for a task with however long you spent on the task today, and the same with yesterday's time. A task that was started before midnight, that continues into the next day should not be simultaneously incremented on two days at once, but for the appropriate amount of time for each day. The output of timew summary, in terms of amount of time tracked, should be identical to timew report totals.py, not an overestimation.

Timewarrior Version: 1.4.3
OS: EndeavourOS
Python Version: 3.10.7

**Comment by lauft** [comment]
When given a range, Timewarrior returns all intervals whose start or end date are within that range.
In contrast to the `totals` report, `summary` truncates the intervals found at the day border, but only there. If the search range is within a day, both `totals` and `summary` show the same output:

```
$ timew track FOO 2022-10-15T11:00:00 - 2022-10-15T13:00:00
Note: 'FOO' is a new tag.
Recorded FOO
  Started 2022-10-15T11:00:00
  Ended              13:00:00
  Total               2:00:00
$ timew track BAR 2022-10-15T14:00:00 - 2022-10-15T16:00:00
Note: 'BAR' is a new tag.
Recorded BAR
  Started 2022-10-15T14:00:00
  Ended              16:00:00
  Total               2:00:00

$ timew totals 2022-10-15T12:00:00 - 2022-10-15T15:00:00

Total by Tag, for 2022-10-15 12:00:00 - 2022-10-15 15:00:00

Tag        Total
BAR      2:00:00
FOO      2:00:00
                
Total    4:00:00

$ timew summary  2022-10-15T12:00:00 - 2022-10-15T15:00:00

Wk  Date       Day Tags    Start      End    Time   Total
W41 2022-10-15 Sat FOO  11:00:00 13:00:00 2:00:00
                   BAR  14:00:00 16:00:00 2:00:00 4:00:00
                                                         
                                                  4:00:00
```
The specified time range overlaps only with 1h of each tracked interval, yet they are listed in full with both commands.

I wonder whether Timewarrior should always truncate the intervals at the search border, or (especially with commands `export`/`report`) whether there should be configurable (?) exceptions to that rule.

**Comment by eq0cdk** [comment]
I think Timewarrior should truncate the intervals. I think that having tracked time recorded twice is just plain inaccurate. Just to point out the extreme inaccuracy possible with this bug, look at the output of the following commands:
```
$ timew track Work 2022-10-17 - 2022-10-24 # Recording 10 days of Work
Recorded Work
  Started 2022-10-17T00:00:00
  Ended           27T00:00:00
  Total             240:00:00

# 1-week interval summary
$ timew summary 2022-10-17 - 2022-10-24 # Accurate
Wk  Date       Day Tags   Start     End     Time     Total
W42 2022-10-17 Mon Work 0:00:00 0:00:00 24:00:00  24:00:00
W42 2022-10-18 Tue Work 0:00:00 0:00:00 24:00:00  24:00:00
W42 2022-10-19 Wed Work 0:00:00 0:00:00 24:00:00  24:00:00
W42 2022-10-20 Thu Work 0:00:00 0:00:00 24:00:00  24:00:00
W42 2022-10-21 Fri Work 0:00:00 0:00:00 24:00:00  24:00:00
W42 2022-10-22 Sat Work 0:00:00 0:00:00 24:00:00  24:00:00
W42 2022-10-23 Sun Work 0:00:00 0:00:00 24:00:00  24:00:00
                                                          
                                                 168:00:00

# 1-week interval "month" report
$ timew month 2022-10-17 - 2022-10-24 | tail -n 4 # Accurate
               Tracked       168:00:00
               Available       0:00:00
               Total         168:00:00

# 1-week interval totals.py report
$ timew report totals.py 2022-10-17 - 2022-10-24 # Off by 3 days (72 hours)
Total by Tag, for 2022-10-17 00:00:00 - 2022-10-24 00:00:00

Tag        Total
Work   240:00:00
                
Total  240:00:00

# 1-day interval summary
$ timew summary 2022-10-17 # Accurate
Wk  Date       Day Tags   Start     End     Time    Total
W42 2022-10-17 Mon Work 0:00:00 0:00:00 24:00:00 24:00:00
                                                         
                                                 24:00:00

# 1-day interval summary (next day)
$ timew summary 2022-10-18 # Accurate
Wk  Date       Day Tags   Start     End     Time    Total
W42 2022-10-18 Tue Work 0:00:00 0:00:00 24:00:00 24:00:00
                                                         
                                                 24:00:00

# 1-day interval summary (2 days later)
$ timew summary 2022-10-19 # Accurate
Wk  Date       Day Tags   Start     End     Time    Total
W42 2022-10-19 Wed Work 0:00:00 0:00:00 24:00:00 24:00:00
                                                         
                                                 24:00:00

# 1-day interval summary (3 days later)
$ timew summary 2022-10-20 # Accurate
Wk  Date       Day Tags   Start     End     Time    Total
W42 2022-10-20 Thu Work 0:00:00 0:00:00 24:00:00 24:00:00
                                                         
                                                 24:00:00

# 1-day interval totals.py report
$ timew report totals.py 2022-10-17 # Off by 9 days (216 hours)
Total by Tag, for 2022-10-17 00:00:00 - 2022-10-18 00:00:00

Tag        Total
Work   240:00:00
                
Total  240:00:00

# 1-day interval totals.py report (next day)
$ timew report totals.py 2022-10-18 # Off by 9 days (216 hours)
Total by Tag, for 2022-10-18 00:00:00 - 2022-10-19 00:00:00

Tag        Total
Work   240:00:00
                
Total  240:00:00

# 1-day interval totals.py report (2 days later)
$ timew report totals.py 2022-10-19 # Off by 9 days (216 hours)
Total by Tag, for 2022-10-19 00:00:00 - 2022-10-20 00:00:00

Tag        Total
Work   240:00:00
                
Total  240:00:00

# 1-day interval totals.py report (3 days later)
$ timew report totals.py 2022-10-20 # Off by 9 days (216 hours)
Total by Tag, for 2022-10-20 00:00:00 - 2022-10-21 00:00:00

Tag        Total
Work   240:00:00
                
Total  240:00:00

# ... etc.

```
So, if you track 10 days of consecutive time, and you run timew summary or timew month for a 1 week interval, you will get 168 hours, which is exactly 7 days. That's accurate. If you do the same with timew report, you get 240 hours. This is off by 3 days (72 hours). If you do a 1-day timew report, you get 240 hours again. This is off by 9 days (216 hours). And every single day is recorded as 240 hours of work per day, which isn't even physically possible. The same does not happen with timew summary. timew month returns the same results as timew summary, but I didn't bother showing the results here.

As you can see, the output just isn't consistent with the output of the other Timewarrior commands. timew month and summary both report identical/accurate tracked times, unlike totals.py, which is wildly inaccurate.

I have personally observed that from time to time, my daily reports will be off by 1-2 hours, depending on whether or not I had a task that went past midnight. This is quite irritating, to say the least.
