### ISSUE TITLE
timew summary should exit nonzero when no interval data found.

### ISSUE THREAD

**Issue by smemsh** [GothenburgBitFactory/timewarrior#507]
I'm scraping the output of `timew summary` and would like to know about lack of time data for the interval given, based on status (rather than pattern match on the returned strings).  It seems not to indicate:
```
 $ faketime '2022-10-10 00:00:00' timew summary :ids
No filtered data found in the range 2022-10-10T00:00:00 - 2022-10-11T00:00:00.

 $ echo $?
0
```

**Comment by lauft** [comment]
The output of `summary` is intended for humans, not machines. 

For scripts, use `export` (or `report`), and `get`, e.g.
```
$ timew get dom.tracked.count :tomorrow
0
```
Those commands provide more machine readable output.

**Comment by smemsh** [comment]
There's no substitute for the summary output unless you want to do all the calculations yourself from the export.  It doesn't seem to cause any problems to have it return an exit code.  It's an additional datum that is out-of-band.  Would you accept a patch that added it, or just opposed because it's not supposed to be scraped so therefore irrelevant?

**Comment by lauft** [comment]
I would argue that a non-zero exit code should signal an actual error, e.g invalid input, internal errors, ...
Therefore, Timewarrior should not consider "finding no interval in the specified range" as an error. It is the valid answer to what the user requested (and the user has to decide what to make of it).

As this request seem closely related to #508, see also my remarks there.
