### ISSUE TITLE
feature request: JSON export for `timew summary`

### ISSUE THREAD

**Issue by smemsh** [GothenburgBitFactory/timewarrior#508]
would be useful if `timew summary` had a way to output JSON, saving the effort of doing computations from `timew export` data which are already well implemented and debugged in `timew` itself. (and, without need for screen scraping step)

**Comment by lauft** [comment]
Depending on what you need the data for, or what kind of output data, `export` or `get` might be a better choice for an extension, or a custom report (There is the [timew-report](https://pypi.org/project/timew-report/) Python package, which helps with parsing the output).

**Comment by smemsh** [comment]
Just want all the same data `summary` already has, but for import into my own wrapper.  Let's say I want to write my own `summary` with whizbang colors, different formatting and some other fields from the corresponding Taskwarrior tasks (close to my use case).

Sure, I can get some of this with the dom access, and all of it from an export (that I then process), but Timewarrior already has almost all the data I want from it precomputed in the Summary report, so having that in JSON would be nice.  But it's not strictly necessary, it can be reproduced, so, that will have to be my approach :-) Thanks for considering, anyways.

**Comment by lauft** [comment]
When you have a summary like this:
```
Wk  Date       Day ID Tags Annotation     Start      End    Time   Total
W41 2022-10-15 Sat @3 FOO              10:00:00 11:00:00 1:00:00
                   @2 BAR  Lorem ipsum 11:00:00 13:00:00 2:00:00
                   @1 BAZ              15:00:00        - 1:41:47 4:41:47
                                                                        
                                                                 4:41:47
```
then `timew export` would return this:
```
[
{"id":3,"start":"20221015T080000Z","end":"20221015T090000Z","tags":["FOO"]},
{"id":2,"start":"20221015T090000Z","end":"20221015T110000Z","tags":["BAR"],"annotation":"Lorem ipsum"},
{"id":1,"start":"20221015T130000Z","tags":["BAZ"]}
]
```
The question is: What would your JSON export of the summary look like?

**Comment by smemsh** [comment]
I was making the JSON for it, starting with something like this:
```
week [day [{total, intervals [{tags[], notes[], start, end, duration}]}]
```
and realized, I would skip totals fields anyways, it would be easy to count inline in my loop anyways, and then it would end up looking not much different than "export," I think the easy week and day groupings are the only thing it gains but that's easy enough.  So, I take it back, you are right thanks.
