### ISSUE TITLE
How to format date for an interval

### ISSUE THREAD

**Issue by fede-green** [GothenburgBitFactory/timewarrior#509]
Hello, 

sorry, i missed how should i specify a date to specify an interval for a command. For example, i would like to see a summary of all the entries from August 28 of this year until now 21st of October.

How do i do that? Thanks for helping me out :)

**Comment by lauft** [comment]
This should do the trick:
```
$ timew sum 2022-08-28 - 2022-10-22
```
Note that currently the upper bound is exclusive. So to include the 21st of October, you have to specify the 22nd as the upper limit .
