### ISSUE TITLE
[TI-46] Display error in visual reports (day,week,month)

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#51]
_Michael Meier on 2016-09-10T11:12:17Z says:_ 

 Have a look at the attached screenshot. Even though the current day only has entries until 13:01, the `day` report has the remaining day filled with `pysoase tools`. The same happens in the `week` and `month` reports. 

Note that the numbers in the summary report as well as the Tracked number for the `day tools` report are correct, I spend about an hour on a `tools` task today. But still, the charts seem to fill the entire day with that task. 

Perhaps there is a problem because the 00:00:00 - 00:00:54 entry is too short?

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-09-10T11:12:17Z
Modified: 2017-02-18T22:13:34Z
```

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2017-02-18T14:05:28Z says:_ 

 Yes, the interval below 1 minute was causing some problems. This should be fixed now.

**Comment by pbeckingham** [comment]
![ti-46_bug](https://user-images.githubusercontent.com/7963/36635161-2b3e10b4-197e-11e8-91fd-263b7c621261.png)
