### ISSUE TITLE
test help.t failing: timew help with unknown argument should show error message

### ISSUE THREAD

**Issue by eddsalkield** [GothenburgBitFactory/timewarrior#512]
`test_help_with_unknown_argument_should_show_error_message` currently expects the output of `timew help bogus` to contain "No manual entry for timew-bogus".

However, the actual output is "man: No entry for timew-bogus in the manual.", hence the test fails.

**Comment by lauft** [comment]
@eddsalkield Which version of Timewarrior are you using and what is your operating system?
I cannot reproduce this behavior locally and also the [test suite](https://github.com/GothenburgBitFactory/timewarrior/actions/runs/3373234790) show no error... 🤔

**Comment by eddsalkield** [comment]
I'm running Alpine edge, and experienced this on timewarrior 1.4.3 and the master branch. You can see the build commands I'm running here: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/41644/diffs?commit_id=18e787216aed20451f4d3aa0115d3739eb958241

I'll take another look and cross-compare with the test suite if I get some time.

**Comment by lauft** [comment]
It seems that not all `man`s are acting equal...

I played around with the test and a solution I found was to first call `man` with the command to be searched for (`timew-bogus`) and then test that `timew help bogus` does return the same error message.

**Comment by lauft** [comment]
@eddsalkield, I have created a Docker test image for Alpine edge and could reproduce the error. However, only if I use the `mandoc` package. When using package `man-db` (as in the other test images) the error does not show up. 

Lesson: never rely on external output...

**Comment by eddsalkield** [comment]
Huh, nice catch! Thanks for looking into this
