### ISSUE TITLE
repeat-last option

### ISSUE THREAD

**Issue by vantablu3** [GothenburgBitFactory/timewarrior#521]
It would be very cool if there would be an option that would do  `timew start <tags used in last entry/>`, i.e. just copying the last used tags for the new entry (that way, having to manually type in all the previously used tags wouldn't be necessary (personally, i even have to run `timew summary` first because I can't remember the names of the tags I'm using)).

**Comment by sruffell** [comment]
You're in luck since this is the exact intent of the [continue](https://github.com/GothenburgBitFactory/timewarrior/blob/develop/doc/man1/timew-continue.1.adoc) command.

For the use case you mentioned, just entering `timew continue` would be sufficient.
