### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by txtsd** [GothenburgBitFactory/timewarrior#528]
There are [~130 commits](https://github.com/GothenburgBitFactory/timewarrior/compare/v1.4.3...dev) since the [last release](https://github.com/GothenburgBitFactory/timewarrior/releases/tag/v1.4.3), which includes the changes required to adhere to the [XDG Base Directory Specification](https://github.com/GothenburgBitFactory/timewarrior/issues/207).

The [1.5.0 milestone](https://github.com/GothenburgBitFactory/timewarrior/milestone/11) has only [one pending issue](https://github.com/GothenburgBitFactory/task-timewarrior-hook/issues/13), which was opened in 2020. If this can't be fixed right now, it can be fixed in the next version.

**Comment by lauft** [comment]
[Timewarrior](timewarrior.net) 1.5.0 has been [released](https://github.com/GothenburgBitFactory/timewarrior/releases/download/v1.5.0/timew-1.5.0.tar.gz) on 2023-04-04
