### ISSUE TITLE
Update CONTRIBUTING.md to use branch 'develop' instead of 'dev'

### ISSUE THREAD

**Issue by Cup0fCoffee** [GothenburgBitFactory/timewarrior#531]
New branches and PRs [should use `develop` branch](https://github.com/GothenburgBitFactory/timewarrior/discussions/472) instead of `dev`. [`CONTRIBUTING.md`](https://github.com/GothenburgBitFactory/timewarrior/blob/develop/CONTRIBUTING.md#how-to-make-a-pull-request) should be updated to reflect that.

**Comment by lauft** [comment]
Good catch! ❤️
