### ISSUE TITLE
`on-modify.timewarrior` not included with Homebrew package for macOS

### ISSUE THREAD

**Issue by leifericf** [GothenburgBitFactory/timewarrior#543]
I have installed Timewarrior (and Taskwarrior) via Homebrew.

```
$ which task
/opt/homebrew/bin/task

$ which timew
/opt/homebrew/bin/timew
```

And I'm trying to integrate the two, as described in [this guide](https://timewarrior.net/docs/taskwarrior/#:~:text=Taskwarrior%20and%20Timewarrior%20are%20related%2C%20and%20work%20together,part%20of%20the%20Timewarrior%20installation%2C%20usually%20at%20%2Fusr%2Flocal%2Fshare%2Fdoc%2Ftimew%2Fext%2Fon-modify.timewarrior.).

However, I can't find the mentioned script (`on-modify.timewarrior`) anywhere on my system under `/usr`.

Is this script not included with the Homebrew package?

Here is some more details about my Timewarrior installation:

```
$ timew diagnostics

timew 1.5.0
       Platform: Darwin

Compiler:
        Version: Apple LLVM 14.0.0 (clang-1400.0.29.202)
           Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
     Compliance: C++11

Build Features
          Built: Apr  5 2023 03:04:16
          CMake: 3.26.3
     Build type: Release

Configuration
  TIMEWARRIORDB: -
            Cfg: /Users/my-username/.timewarrior/timewarrior.cfg (-rw- 0 bytes)
       Database: /Users/my-username/.timewarrior (drwx 160 bytes)
    Color theme: Built-in default
                 00 01 02 03 04 05 06 07 08 09 10 11 12

Extensions
       Location: /Users/my-username/.timewarrior/extensions (drwx 64 bytes)
```

**Comment by lauft** [comment]
> Is this script not included with the Homebrew package?

The file `on-modify.timewarrior` is included in the [timew-1.5.0.tar.gz](https://github.com/Homebrew/homebrew-core/blob/69f3a9e0ed6e972f58113d2178fb150c5c953d94/Formula/timewarrior.rb#LL4C85-L4C103) tarball used by the formula. However, the formula itself is not maintained by us, so please open an issue [over there](https://github.com/Homebrew/homebrew-core).

As a workaround, you could download the `on-modify.timewarrior` [from here](https://github.com/GothenburgBitFactory/timewarrior/blob/v1.5.0/ext/on-modify.timewarrior).
