### ISSUE TITLE
`on-modify.timewarrior` not working properly with taskwarrior tags

### ISSUE THREAD

**Issue by felixschurk** [GothenburgBitFactory/timewarrior#565]
When I use the `on-modify.timewarrior` script, It does work with the description. However the tags are split completely random and are not captured properly. 
An sample is attached where the `+new` tag results in `e,n,` in the timewarrior tracking.
I am not aware if there is already an issue regarding that, therefore I created this new one.

```sh
❯ task add testtask +new
Created task 68.
❯ task 68 start
Starting task 6f2a39d5 'testtask'.
Started 1 task.
Tracking e n testtask
  Started 2023-10-25T08:15:42
  Current                  42
  Total               0:00:00
You have more urgent tasks.
❯ timew summary

Wk  Date       Day Tags             Start End    Time   Total
W43 2023-10-25 Wed e, n, testtask 8:15:42   - 0:00:10 0:00:10
                                                             
                                                      0:00:10

```

I am running under Fedora 39, with
```sh
task --version: 2.6.2
timew --version: 1.6.0
python --version: 3.12
```

**Comment by felixschurk** [comment]
I had now a proper look after I posted the issue and noticed and it could be fixed with the change off
https://github.com/GothenburgBitFactory/timewarrior/blob/9c49d4df2de121d1b68fef0f7b6be906ab962218/ext/on-modify.timewarrior#L54
to use
`tags.extend([json_obj['tags']])`
to have then a proper list where the extend can work on. 
https://docs.python.org/3/tutorial/datastructures.html

I would create a Pull Request and check with tests to close this, if that is okay.

**Comment by lauft** [comment]
@felixschurk Please note that the `on-modify.timewarrior` hook has its own repository 👉🏻 https://github.com/GothenburgBitFactory/task-timewarrior-hook which also contains its test suite. Please open a PR there then.

**Comment by lauft** [comment]
Fixed with https://github.com/GothenburgBitFactory/task-timewarrior-hook/pull/34
