### ISSUE TITLE
:lastweek report omits Sunday records

### ISSUE THREAD

**Issue by catanadj** [GothenburgBitFactory/timewarrior#567]
Hello everyone. Recently I've updated from 1.4.3 to 1.6.0 and found out that the :lastweek report is not including Sunday data. I've tried version 1.5.0 but it seems that the issue is present there as well so I'm reverting back to version 1.4.3.

Does anyone know what could be the issue ?

Thank you.

**Comment by sskras** [comment]
You probably need version 1.7.0 to include the fix: https://github.com/GothenburgBitFactory/timewarrior/issues/493#ref-commit-d61f399
