### ISSUE TITLE
[Question] How to specify database directory?

### ISSUE THREAD

**Issue by sdifru** [GothenburgBitFactory/timewarrior#589]
I installed timewarrior on arch linux. The database is in `~/.local/share/timewarrior`. I want to use another directory as the database. How do I do it?

**Comment by lauft** [comment]
Timewarrior uses [XDG Base Directory](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) to determine the DB location.

 If you haven't configured XDG for your system, you can switch to another location by setting the environment variable `XDG_DATA_HOME` (but this may affect other applications adhering to XDG as well). There is also `XDG_CONFIG_HOME` which determines where Timewarrior stores its configuration (in `timewarrior.cfg`) and extensions.

As an alternative, you can move both, database and configuration, to the legacy directory `~/.timewarrior` - or define a custom path with the environment variable `TIMEWARRIORDB`.

**Comment by sdifru** [comment]
@lauft Alright, Thanks!
