### ISSUE TITLE
Review CONTRIBUTIING.md for applicability

### ISSUE THREAD

**Issue by pbeckingham** [GothenburgBitFactory/timewarrior#6]
With Github and the pull request model, the CONTRIBUTING.md file is probably not needed, or could be reduced.

**Comment by recollir** [comment]
It is still a good file. As it is linked to/referred to from the create issue/pr page. See https://help.github.com/articles/setting-guidelines-for-repository-contributors

Prominent place for people to see it.

**Comment by pbeckingham** [comment]
My point was that is goes into detail showing how to generate and email patch files, which is no longer the preferred approach.  Thomas's call.

**Comment by lauft** [comment]
CONTRIBUTING updated
