### ISSUE TITLE
Add retag command to internal help

### ISSUE THREAD

**Issue by stherold** [GothenburgBitFactory/timewarrior#600]
Very often I have to replace a tag I have on my time trackings: 
- I start with time tracking and later recognize I need to split it since I forgot to start tracking for the new project
- I started tracking with the tag lets say `review` but shortly after that I turned my focus more to `coding` and I want to replace the tag. I use these 2 tags to track how much time I spend coding, reviewing and for other things (tag: `misc`)

In all of the cases I have to call `tw tag @1 project_b && tw untag @1 project_a` 😭

It would be easier when I could run a simple command `tw retag @1 project_a project_b` 💡

**Comment by lauft** [comment]
There already is a `retag` command. It is [listed on the website](https://timewarrior.net/reference/timew-retag.1/) but not in the internal help. 😔

**Comment by Blackjacx** [comment]
Thanks! I found and heavily use it 😅
