### ISSUE TITLE
[TI-57] `timew track` with future interval records nothing or incomplete interval

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#62]
_Thomas Lauf on 2016-12-29T10:22:27Z says:_ 

 Suppose it is 2016-12-29T10:00. When I enter

`timew track 2016-12-29T08:00 - 2016-12-29T16:00 TIMEOFF`

`timew` reports back
```
Recorded TIMEOFF
  Started 2016-12-29T08:00:00
  Ended              16:00:00
  Total              67:24:05
```

however the database contains
```
...
inc 20161229T070000Z - 20161229T090000Z # TIMEOFF
```

When I call `timew track` with an interval which does not contain my current point in time, there is no entry at all in the database - despite the positive feedback...

`timew track` should either report correctly on the tracked time entered to the datapase or - preferred - allow future timetracking (use-cases: holiday, timeoff, sickness...)

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-12-29T10:22:27Z
Modified: 2018-01-15T20:28:20Z
```

**Comment by JonasDralle** [comment]
I don't think this works correctly. Time in future still cannot be billed correctly. For example when it's 11:58 one cannot end an interval at 12:00 without editing the `.data` file.
