### ISSUE TITLE
Passing arguments or flags to an extension report

### ISSUE THREAD

**Issue by matm** [GothenburgBitFactory/timewarrior#640]
I am writing a couple of extensions to Timewarrior. According to the [documentation](https://timewarrior.net/reference/timew-report.1/), it appears there is no way to pass an argument or optional flag(s) to my extension.

Using a `cat` extension defined in a `cat.sh` file as
```shell
#!/bin/sh
echo "ARGS: $@"
cat
```
I can see the `ARGS:` line is always empty no matter what I pass on the command line, like
```shell
$ timew cat 1 | head
ARGS:
color: off
...
```
Same output if I run `timew cat --trythis | head`.

Is there a way to achieve this?

**Comment by lauft** [comment]
Currently, Timewarrior sends the current configuration and the filtered time intervals to the extension.

As a workaround you can use [command line overrides](https://timewarrior.net/docs/overrides/) to pass arguments:
```
$ timew cat rc.my_value=1 
```
should give you
```
ARGS:
...
my_value: 1
...
```

**Comment by matm** [comment]
Oh I missed this overrides section in the documentation. Thanks you! This is a good enough workaround to me :+1:
