### ISSUE TITLE
[TI-60] Build error on termux

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#65]
_Paul Beckingham on 2016-08-27T01:01:35Z says:_ 

 On Aug 26, 2016 6:20 PM, "Fredrik Fornwall" <notifications(at)github.com> wrote:
Thanks for the suggestion!

I tried building timewarrior and encountered a problem described by the following note:

In src/libshared/src/FS.cpp the <glob.h> file is included
which is not provided by the Android platform. In Termux
we have it in $TERMUX_PREFIX/include, which sould be found
by DCMAKE_FIND_ROOT_PATH=$TERMUX_
PREFIX? Works in
taskwarrior for the src/FS.cpp file there.

Are you involved with the project and can look at this build problem (or could ask the right people)? I'm not that used to cmake, so it may be me missing something.

**Comment by lauft** [comment]
If somebody revives the termux package, a new issue can be created.
