### ISSUE TITLE
[TI-62] TimeWarrior should not ignore invalid command

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#67]
_Thomas Lauf on 2017-01-27T17:13:44Z says:_ 

 When I call timew with an invalid command, it behaves as if no command was given. I think, it should issue an error message like
{code}
'foo' is not a timew command. See 'timew help'
{code}

This would be helpful to spot typos. Consider the case I started a time interval and want to stop it, but mistype the command. The output in this case is:
{code}
$ timew stpo
Tracking 
  Started 2017-01-27T18:12:00
  Current               14:30
  Total               0:02:30
{code}
The output for the correct command would be:
{code}
$ timew stop
Recorded 
  Started 2017-01-27T18:12:00
  Ended                    00
  Total               0:00:00
{code}
On a quick glace one might not spot the `Tracking` instead of `Recorded` and the different Time values.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-01-27T17:13:44Z
Modified: 2017-04-11T05:20:22Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-01-27T20:45:55Z says:_ 

 I agree.  Thanks.

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2017-01-28T14:28:54Z says:_ 

 Took the liberty to supply some tests for cli.t which also cover this use case.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-01-29T02:48:07Z says:_ 

 Nice tests, thank you for doing that.  You're in the AUTHORS file now - no going back!

**Comment by pbeckingham** [comment]
[TI-62_0001-TI-62-TimeWarrior-should-not-ignore-invalid-command.patch.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755266/TI-62_0001-TI-62-TimeWarrior-should-not-ignore-invalid-command.patch.txt)

**Comment by sskras** [comment]
I am not sure how/where this was fixed, but when I run `make test` with latest `dev` version I get this:

```
not ok 3 - template.t: Test foo
# ERROR: CommandError on file /home/saukrs/src/timewarrior/test/template.t line 74 in test_foo: 'code, out, err = self.t("foo")':
#        Command '['/home/saukrs/src/timewarrior/src/timew', 'foo']' finished with unexpected exit code '255'.
#
#        *** Start STDOUT ***
#
#        *** End STDOUT ***
#
#        *** Start STDERR ***
#        'foo' is not a timew command. See 'timew help'.
#
#        *** End STDERR ***
```

I work in Msys2 environment, a fork of Cygwin:

```
$ uname -a
MSYS_NT-10.0 SAUKRSXM1 2.11.1(0.329/5/3) 2018-09-10 14:19 x86_64 Msys
```

Current `timew` version:

```
$ src/timew diag

timew 1.2.0
       Platform: <unknown>

Compiler:
        Version: 7.3.0
           Caps: +stdc +stdc_hosted +200809 +200809 +LP64 +c8 +i32 +l64 +vp64 +time_t64
     Compliance: C++11

Build Features
          Built: Apr 15 2020 20:15:11
         Commit: d73143b
          CMake: 3.13.2
     Build type: debug

Configuration
  TIMEWARRIORDB: -
            Cfg: /home/saukrs/.timewarrior/timewarrior.cfg (-rw- 64 bytes)
       Database: /home/saukrs/.timewarrior (drwx 0 bytes)
    Color theme: Built-in default
                 00 01 02 03 04 05 06 07 08 09 10 11 12

Extensions
       Location: /home/saukrs/.timewarrior/extensions (drwx 0 bytes)
               (None)
```

Is this related to the old bug? Should I open new one?

**Comment by lauft** [comment]
`template.t` is not meant to be run. This file should thus not be executable. Can you check this?

**Comment by sskras** [comment]
Yes, the file has `x` set:
```
$ ll /home/saukrs/src/timewarrior/test/template.t
-rwxr-xr-x 1 saukrs Domain Users 3.9K Mar  1 00:07 /home/saukrs/src/timewarrior/test/template.t
```

Can this be related to the specifics of **Msys2** environment which isn't real *NIX OS ?
I am not able to test this in a Linux VM at the moment.

**Comment by lauft** [comment]
@sskras *Msys2* may have its fingers in the pie but I cannot confirm that. Anyway, `template.t` is now removed from the repository (7e11fde9) so this should not bother anyone... 🙂

**Comment by sskras** [comment]
Thanks for informing.
I am trying to build the new version now from the scratch.
