### ISSUE TITLE
[TI-64] Command 'stop' with date before current interval's start date causes segfault

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#69]
_Thomas Lauf on 2017-02-09T08:06:19Z says:_ 

 When I call `timew stop` with a date that is before the current interval's start date I get a segfault:
{code}
$ timew start 20160516T100200
Tracking 
  Started 2016-05-16T10:02:00
  Current 2017-02-09T09:03:41
  Total            6456:01:41
$ timew stop 20160516T100100
timew: ***/timew/src/Range.cpp:326: time_t Range::total() const: Assertion `is_open () || end >= start' failed.
Aborted (core dumped)
{code}

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-02-09T08:06:19Z
Modified: 2017-02-09T14:01:36Z
```

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2017-02-09T08:20:38Z says:_ 

 Patch with test for this use case and also a fix.

**Comment by pbeckingham** [comment]
[TI-64_0001-TI-64-Command-stop-with-date-before-current-interval.patch.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755265/TI-64_0001-TI-64-Command-stop-with-date-before-current-interval.patch.txt)
