### ISSUE TITLE
Sync via taskserver planned

### ISSUE THREAD

**Issue by igor-krawczuk** [GothenburgBitFactory/timewarrior#7]
Salut,

is adding syncing via taskserver on the roadmap/in the scope of this project?

Cheers,
Igor

**Comment by davemachado** [comment]
+1, would love to know if this is something planned. I use taskwarrior on several clients and would like to start coupling timewarrior with it, but syncing will definitely be an issue...

**Comment by davemachado** [comment]
Just read through some issue, and in #88 ([TI-84]), it says:
```
...there is no sync support, and I would be very reluctant to add that to Taskserver. 
This would represent a lot of work, and even more support,
and there just aren't enough volunteers to make this happen.
```

**Comment by lauft** [comment]
No plans on sync support for the near future. Sorry.

**Comment by lauft** [comment]
@davemachado If this topic is still relevant to you, you might be interested in https://github.com/timewarrior-synchronize
