### ISSUE TITLE
[TI-66] Move with :adjust leaves overlapping intervals.

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#71]
_A M on 2017-03-02T20:15:57Z says:_ 

 Test case patch attached.  timew move with :adjust may leave two intervals which overlap.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-03-02T20:15:57Z
Modified: 2017-12-14T21:00:26Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-03-02T23:06:33Z says:_ 

 Good test.  Thank you!  Patch applied and pushed.

**Comment by taskwarrior** [comment]
_Harald Ellingsen on 2017-07-28T19:38:36Z says:_ 

 Hi, was this resolved?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-07-30T11:05:03Z says:_ 

 The issue is currently unresolved - see the `resolution` field of this issue.

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2017-11-21T20:40:28Z says:_ 

 I see a relation with TI-85 as it also deals with overlap resolution.

**Comment by pbeckingham** [comment]
[TI-66_move-test.patch.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755264/TI-66_move-test.patch.txt)
