### ISSUE TITLE
[TI-68] Cannot shorten interval which has been moved into an exclusion.

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#73]
_A M on 2017-03-09T16:23:54Z says:_ 

 Test patch attached.  The test doe:
*  Creates some exclusions.
*  Tracks an interval not spanning any exclusions.
*  Moves the interval so that it spans an exclusion.
*  Attempts to shorten the moved interval.

The last step fails.  Debug output indicates that the interval we are trying to create via shortening conflicts (overlaps) with the existing unshortened interval.

not ok 3 - shorten.t: test_shorten_interval_straddling_exclusion (TestShorten)
1.  ERROR: CommandError on file ./shorten.t line 84 in test_shorten_interval_straddling_exclusion: 'self.t("shorten @1 5min :debug") # Does not work.':
1.         Command '['/home/icarus/code/timew/src/timew', 'shorten', '@1', '5min', ':debug']' finished with unexpected exit code '255'.
1.         
1.         *** Start STDOUT ***
1.         CLI Parser
1.           _original_args
1.             /home/icarus/code/timew/src/timew shorten @1 5min :debug
1.           _args
1.             word basename='timew' raw='/home/icarus/code/timew/src/timew' BINARY 
1.             word canonical='shorten' raw='shorten' ORIGINAL CMD 
1.             word raw='@1' value='1' ORIGINAL ID FILTER 
1.             duration raw='5min' ORIGINAL FILTER 
1.             word canonical=':debug' raw=':debug' ORIGINAL HINT FILTER 
1.         
1.         >> 2017-03.data: 1 intervals
1.         >> Found 0 holidays
1.         >> Found 7 exclusions
1.         >> Loaded 2 tracked intervals
1.         >> Found 0 holidays
1.         >> Found 7 exclusions
1.         >> Loaded 2 tracked intervals
1.         >> Input         interval @1 2017-03-08T13:00:00 - 2017-03-08T13:35:00
1.         >> Overlaps with
1.         >>              interval @1 2017-03-08T13:00:00 - 2017-03-08T13:40:00
1.         >> Timer timew 0.003249 sec
1.         
1.         
1.         *** End STDOUT ***
1.         
1.         *** Start STDERR ***
1.         You cannot overlap intervals. Correct the start/end time, or specify the :adjust hint.
1.         
1.         *** End STDERR ***

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-03-09T16:23:54Z
Modified: 2017-04-08T17:25:07Z
```

**Comment by taskwarrior** [comment]
_A M on 2017-03-09T16:55:35Z says:_ 

 Forgot to mention, I trigger this all the time using taskwarrior.  I frequently do:
*  task start x # Gives me a timewarrior block with all tags defined on that task.
*  timew move @x # Move to when I actually started working on the task.
*  <forget to task stop>
*  task stop x
*  timew shorten @x

Without the taskwarrior integration it's probably very unusual to trigger this bug.

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2017-03-09T19:27:25Z says:_ 

 I haven't looked into it in detail, but to me the issue seem related with TI-58, where exclusions prevent intervals to be deleted.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-03-10T13:35:32Z says:_ 

 Patch applied, thank you.

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2017-04-06T07:30:16Z says:_ 

 According to the definition of intervals, exclusions should not be applied to closed intervals. This is what happens here.
The other issue that needs to be investigated here is whether shortening a synthetic interval works. In this case, the interval needs to be converted to a real interval and then shortened.

**Comment by pbeckingham** [comment]
[TI-66_move-test.patch.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755262/TI-66_move-test.patch.txt)
[TI-68_move-shorten.patch.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755263/TI-68_move-shorten.patch.txt)
