### ISSUE TITLE
[TI-73] timew move with a specific time broken on 1.1.0

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#78]
_A M on 2017-04-10T19:50:37Z says:_ 

 This works in 1.0.0 but is broken on 1.1.0 as of SHA 6ade46085ed3b54828d926e4c59b140eeeabca4f

Test patch attached.  timew move @1 12:01am gives an error:
"The end of a date range must be after the start."

This works in the same environment with the same database in 1.0.0

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-04-10T19:50:37Z
Modified: 2017-05-21T17:15:48Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-05-21T17:11:53Z says:_ 

 Patch applied, thank you.  There is a bug in the patch, where 'T00:00:00' should be 'T00:01:00', fixed.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-05-21T17:15:48Z says:_ 

 Was fixed when TI-77 was addressed.

**Comment by pbeckingham** [comment]
[TI-73_bad-move.patch.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755261/TI-73_bad-move.patch.txt)
