### ISSUE TITLE
[TI-78] Tag parsing broken for tags starting with "or_"

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#82]
_Lukas Barth on 2017-06-12T19:16:34Z says:_ 

 Hi, 

it looks like something breaks when I start tracking with the tags "or_c1" and "or_root". Consider this:
{code:java}
tinloaf(at)janeway /m/d/h/t/s/moder $ timew
There is no active time tracking.
tinloaf(at)janeway /m/d/h/t/s/moder $ timew summary
No filtered data found in the range 2017-06-12T00:00:00 - 2017-06-13T00:00:00.
tinloaf(at)janeway /m/d/h/t/s/moder $ timew start 'test_t1' 'test_t2'
Tracking test_t1 test_t2
 Started 2017-06-12T21:07:14
 Current 14
 Total 0:00:00
tinloaf(at)janeway /m/d/h/t/s/moder $ timew
Tracking test_t1 test_t2
 Started 2017-06-12T21:07:14
 Current 17
 Total 0:00:03
tinloaf(at)janeway /m/d/h/t/s/moder $ timew stop
Recorded test_t1 test_t2
 Started 2017-06-12T21:07:14
 Ended 23
 Total 0:00:09
tinloaf(at)janeway /m/d/h/t/s/moder $ timew start 'or_c1' 'or_root'
Tracking or_c1 or_root
 Started 2017-06-12T21:07:36
 Current 36
 Total 0:00:00
tinloaf(at)janeway /m/d/h/t/s/moder $ timew
Tracking _c1 _root or
 Started 2017-06-12T21:07:36
 Current 38
 Total 0:00:02
tinloaf(at)janeway /m/d/h/t/s/moder $ timew stop
You cannot overlap intervals. Correct the start/end time, or specify the :adjust hint.{code}
The underscore does not seem to be the problem, since 'test_t1' and 'test_t2' work. However, it is also strange how the message right after "start 'or_c1' 'or_root'" says "Tracking or_c1 or_root", and the next message says "Trackung _c1 _root or", as if the tags were split at the underscore.

Also, for some reason this seems to break timewarrior completely: I can't stop the time tracking afterwards.

If I can help in any way with debugging this, please let me know.

Kind regards,

Lukas

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-06-12T19:16:34Z
Modified: 2017-08-05T09:18:08Z
```

**Comment by taskwarrior** [comment]
_Lukas Barth on 2017-06-14T12:50:45Z says:_ 

 The problem is that the lexer (which is used to tokenize the line read from the datafile) does not accept "_" in words. Thus, tags containing underscores must be quoted in the data file. See my attached patch.

**Comment by taskwarrior** [comment]
_Lukas Barth on 2017-06-16T13:29:28Z says:_ 

 Forgot to do unit testing. Added a test for underscore escaping, all tests passing.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-06-16T22:29:33Z says:_ 

 Nice, thank you.  Will take a look shortly.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-08-05T09:18:08Z says:_ 

 Patches applied, thank you.

**Comment by pbeckingham** [comment]
[TI-78_0001-Quote-tags-containing-underscores.patch.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755253/TI-78_0001-Quote-tags-containing-underscores.patch.txt)
[TI-78_0002-Add-test-for-underscore-escaping.patch.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755254/TI-78_0002-Add-test-for-underscore-escaping.patch.txt)
