### ISSUE TITLE
[TI-84] It would be convenient to have a mobile timewarrior app

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#88]
_Yury Vidineev on 2017-07-28T23:04:02Z says:_ 

 Just an idea that came to my head each time when I remember that I forgot to run "timew stop" before closing the lid of my laptop. In that case I have to get laptop from backpack, open lid, login, timew stop. It would be much more convenient to have android app and some sort of synchronization.

 

P.S. Thanks for all your work, guys!

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-07-28T23:04:02Z
Modified: 2017-08-07T18:52:02Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-07-30T10:02:51Z says:_ 

 I'm going to keep this issue open, in case someone feels inspired and willing to donate months of work.

But we are not mobile developers, so will not be writing a mobile app.  Even with a mobile app, there is no sync support, and I would be very reluctant to add that to Taskserver.  This would represent a lot of work, and even more support, and there just aren't enough volunteers to make this happen.

For the purpose you describe, it might be sufficient to use simple file sync services to copy the Timewarrior data files around, but this will not be directly supported.

**Comment by taskwarrior** [comment]
_Yury Vidineev on 2017-08-07T18:52:02Z says:_ 

 Sure I understand it. And I really appreciate what you're already did (I have very convenient app for time tracking already). Thanks!

It was just an idea for backlog :)

**Comment by lauft** [comment]
I am closing this issue as "out of scope". Contributions are welcome, but a Timewarrior-App is a totally new/different project.

**Comment by arooni** [comment]
well that's too bad, would definitely love an easier interface than opening up my ssh app then tapping some commands.  time warrior is so good i couldn't imagine my life without it now.

**Comment by xxxserxxx** [comment]
I'd like that too, and I may look into it over the next few weeks.  However, if I *do* take this up, it'll probably be:

- A simple start/stop -- *maybe* with the ability to set an annotation or tag
- Syncing the data will be left to a different program.  For example, I use SyncThing for most things.  Adding support for syncing would require a server, diffs are hard to manage correctly, and it's all-around a ton of work that would easily dwarf a simple start/stop program

If anyone else takes this up, please post here so I don't duplicate work.

And, no promises; my time available for free projects is rapidly dwindling.

**Comment by arooni** [comment]
would love to see a mobile client for timewarrior!!!  happy to use syncthing to manage syncing (i already use it).
