### ISSUE TITLE
[TI-87] Added exclusions caused total time to grow

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#91]
_Arden Christian Hines Rasmussen on 2017-09-12T03:10:47Z says:_ 

 Adding times to exclusions in timewarrior.cfg causes the report to report more time in the total, instead of less. In the day report, it claims a total of 25 hours, as can be seen in the image

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-09-12T03:10:47Z
Modified: 2017-09-15T06:56:34Z
```

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2017-09-12T15:42:46Z says:_ 

 To reproduce your bug, could you please tell me how your exclusions are defined? E.g. by posting the output of your `timew config` command. Thanks!

**Comment by taskwarrior** [comment]
_Arden Christian Hines Rasmussen on 2017-09-12T21:59:20Z says:_ 

 Here is the result of timew config. For some context, I am a student, and am attempting to use the exclusions to exclude my class times.
{code}
color = on
confirmation = on
debug = off

define exclusions:
  friday = <7:00 9:10-10:10 12:50-1:40 13:50-14:50 >23:00
  monday = <7:00 9:10-10:10 12:50-1:40 13:50-14:50 >23:00
  thursday = <7:00 9:40-11:10 12:50-1:40 >23:00
  tuesday = <7:00 9:40-11:10 12:50-1:40 >23:00
  wednesday = <7:00 9:10-10:10 1:50-2:50 >23:00

define holidays:
  US:
    2016_01_01 = New Year's Day
    2016_01_18 = Birthday of Martin Luther King, Jr.
    2016_02_15 = Washington's Birthday
    2016_04_18 = Patriots' Day
    2016_05_30 = Memorial Day
    2016_07_04 = Independence Day
    2016_09_05 = Labor Day
    2016_10_10 = Columbus Day
    2016_11_11 = Veterans Day
    2016_11_24 = Thanksgiving Day
    2016_12_25 = Christmas Day

define reports:
  day:
    axis = internal
    cell = 15
    day = yes
    holidays = no
    hours = all
    lines = 2
    month = no
    spacing = 1
    summary = yes
    totals = no
    week = no
    weekday = yes
  gaps:
    range = :day
  month:
    cell = 15
    day = yes
    holidays = yes
    hours = all
    lines = 1
    month = yes
    spacing = 1
    summary = yes
    totals = yes
    week = yes
    weekday = yes
  summary:
    holidays = yes
  week:
    cell = 15
    day = yes
    holidays = yes
    hours = all
    lines = 1
    month = no
    spacing = 1
    summary = yes
    totals = yes
    week = yes
    weekday = yes

define theme:
  colors:
    exclusion = gray8 on gray4
    holiday = gray4
    label = gray4
    today = white
  description = Built-in default

verbose = on

{code}

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2017-09-14T20:32:23Z says:_ 

 Could your exclusions be malformed? You defined one exclusion interval to be `12:50 - 1:40` which should rather be `12:50 - 13:40` in my opinion.

**Comment by taskwarrior** [comment]
_Arden Christian Hines Rasmussen on 2017-09-14T21:12:50Z says:_ 

 You are completely correct, that was the issue

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2017-09-15T06:56:27Z says:_ 

 Follow-up TI-88: Add validation to exclusions

**Comment by pbeckingham** [comment]
![ti-87_screnshot1](https://user-images.githubusercontent.com/7963/36635072-faf94faa-197c-11e8-9f9f-ed464f3883a3.png)
