### ISSUE TITLE
[TI-91] Timewarrior does not compile on DragonFly

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#95]
_Michael Neumann on 2017-11-16T12:31:55Z says:_

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-11-16T12:31:55Z
Modified: 2017-12-10T05:26:01Z
```

**Comment by taskwarrior** [comment]
_Michael Neumann on 2017-11-16T12:37:20Z says:_ 

 The two patches above fixes it for me.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-12-10T05:26:01Z says:_ 

 Thanks for the patch.

Applied to all other projects.

**Comment by pbeckingham** [comment]
[TI-91_0001-TI-91-Fix-compilation-on-DragonFly-libshared.patch.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755245/TI-91_0001-TI-91-Fix-compilation-on-DragonFly-libshared.patch.txt)
[TI-91_0001-TI-91-Fix-compilation-on-DragonFly.patch.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755246/TI-91_0001-TI-91-Fix-compilation-on-DragonFly.patch.txt)
