### ISSUE TITLE
[TI-92] Include Bash completion for timewarrior

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#96]
_lumbric on 2017-11-27T18:35:13Z says:_ 

 AFAICS there is no shell completion script out there yet.

I guess there are two steps:
 * easy: support commands
 * advanced: support tags already used before

For the latter a plain list of tags would be useful (maybe something like timew tags --porcelain like git status --porcelain), but maybe it makes sense to do a quick and dirty version without touching the C code before.

References I've found so far:

https://bug.tasktools.org/browse/TI-14?focusedCommentId=16717&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16717

[https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850046]

 

(I've already started building a shell completion script for my own usage. I would be happy to share it as soon it is reasonable functional.)

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-11-27T18:35:13Z
Modified: 2017-12-03T20:05:12Z
```

**Comment by taskwarrior** [comment]
_lumbric on 2017-11-30T16:41:57Z says:_ 

 I got a first draft. It does not handle spaces in tags properly and has some other minor flaws. For example the command must be the first parameter for completion to work (although "timew my_tag start" seems to work equivalently to "timew start my_tag"), short forms (such as "s" instead of "summary") are not supported and probably some other similar things.


[^timew.bash-completion]

 

(Note that there is an easy way to use [the same script for zsh|https://stackoverflow.com/a/8492043/859591[]|https://stackoverflow.com/a/8492043/859591].)

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-12-02T18:51:59Z says:_ 

 This is good.  I'd be happy to include it.  Are you planning on completing it?  I'm referring to the TODO comments in there.

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2017-12-02T23:50:31Z says:_ 

 There is also a bash-completion-script here: [https://github.com/lauft/timew-bashcompletion]

Maybe we can join forces?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-12-02T23:58:48Z says:_ 

 Of course, I forgot.  Yes, let's combine.

**Comment by taskwarrior** [comment]
_lumbric on 2017-12-03T14:21:43Z says:_ 

 Oh, didn't know that someone else has started already something like this. Unfortunately I found only the mentioned links above, when googling it before I started. Your script is suprisingly similar, I think this is a good sign, that we did it the right way :)

I guess your repository is the place where we can join forces? There only tiny differences between our script. I can create a pull request in your repository if I find something woth extending (eg. limitting the number of ids past to join).

**Comment by taskwarrior** [comment]
_Thomas Lauf on 2017-12-03T20:05:12Z says:_ 

 The repository sure is not a bad place to combine efforts for bash-completion in TimeWarrior. :)

Pull request are definitely welcome.

**Comment by pbeckingham** [comment]
[TI-92_timew.bash-completion.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1755219/TI-92_timew.bash-completion.txt)

**Comment by varac** [comment]
- zsh completion: https://github.com/svenXY/timewarrior
- bash completion: https://github.com/lauft/timew-bashcompletion
