### ISSUE TITLE
[TI-94] Command Injection Security Vulnerability in on-modify.timewarrior

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#98]
_Aaron Fields on 2017-11-29T21:24:24Z says:_ 

 The `on-modify.timewarrior` script uses the deprecated `os.system()` call to execute the `timew` command. The `timew` command string consists of concatenated strings. One of the components of the concatenated `timew` command string is user-supplied.

 

Any task which contains Bash special characters (i.e. dollar signs, backticks, etc.) may be interpreted by the shell started by `os.system()`.

 

This is especially concerning for folks who use BugWarrior (https://github.com/ralphbean/bugwarrior), which may allow a third party to insert tasks into one's tasklist via a maliciously-crafted Issue filed in an issue tracker.

Attached is the on-modify.timewarrior hook I use on my system, which fixes the issue by using `subprocess.call` and `shlex.split` to safely handle the `timew` command string.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-11-29T21:24:24Z
Modified: 2017-12-02T18:53:25Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-12-02T18:53:25Z says:_ 

 Thanks.  Will review.

**Comment by pbeckingham** [comment]
[TI-94_on-modify.timewarrior.txt](https://github.com/GothenburgBitFactory/timewarrior/files/1738273/TI-94_on-modify.timewarrior.txt)
