### ISSUE TITLE
[TI-95] update link to libshared submodule

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#99]
_nate z on 2017-12-02T01:52:18Z says:_

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-12-02T01:52:18Z
Modified: 2017-12-02T20:36:46Z
```

**Comment by taskwarrior** [comment]
_nate z on 2017-12-02T01:55:15Z says:_ 

 In .gitmodules, it currently has this: https://git.tasktools.org/scm/tm/libshared.git
I believe it should be this: https://git.tasktools.org/TM/libshared

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-12-02T18:48:51Z says:_ 

 You're looking at the `master` branch, which represents what is currently released.  You should never be in this branch for any development, and if you want to build the latest release from source, download the 1.0.0 tarball.

The URL is fixed in the 1.1.0 development branch.

**Comment by taskwarrior** [comment]
_nate z on 2017-12-02T20:36:46Z says:_ 

 Oh, my mistake. Thanks for letting me know.

**Comment by harleypig** [comment]
This does not seem to be fixed. Also, I had to add --init to the submodule update command.

    $ git clone https://github.com/GothenburgBitFactory/timewarrior.git ; cd timewarrior ; git checkout 1.2.0 ; git pull --recurse-submodules ; git submodule update --init
    Cloning into 'timewarrior'...
    remote: Counting objects: 11133, done.
    remote: Compressing objects: 100% (2656/2656), done.
    remote: Total 11133 (delta 8446), reused 11121 (delta 8435), pack-reused 0
    Receiving objects: 100% (11133/11133), 1.36 MiB | 1.53 MiB/s, done.
    Resolving deltas: 100% (8446/8446), done.
    Checking connectivity... done.
    /home/harleypig/projects/taskwarrior/timewarrior
    Branch 1.2.0 set up to track remote branch 1.2.0 from origin.
    Switched to a new branch '1.2.0'
    Already up-to-date.
    Submodule 'src/libshared' (https://git.tasktools.org/TM/libshared.git) registered for path 'src/libshared'
    Cloning into 'src/libshared'...
    fatal: https://git.tasktools.org/TM/libshared.git/info/refs not valid: is this a git repository?
    fatal: clone of 'https://git.tasktools.org/TM/libshared.git' into submodule path 'src/libshared' failed

After `git checkout 1.2.0`, modifying `.gitmodules` to `url = https://github.com/GothenburgBitFactory/libshared.git` made cmake and make work, and tests passed:

    Passed:                           849
    Failed:                             0
    Unexpected successes:               0
    Skipped:                            0
    Expected failures:                  0
    Runtime:                         1.91 seconds
    [100%] Built target test

**Comment by recollir** [comment]
1.2.0 and dev branches have now been updated with the correct GitHub url for libshared. Version 1.1.1 has already been released and should be built from the release tar ball that contains libshared. Once 1.2.0 (or any other version) is released and merged to master also master will built accordingly with the new libshared url.
